{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03007-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03007-SNAPSHOT.jar",
          "url": "embedded-mas-0.03007-SNAPSHOT.jar",
          "size": 53525,
          "sha512": "1881bf09cb40fd742acb4eeda95449a648d4307a4d9f05e5c56cb871e7e462722b0751b9426bc8ee406f3f16334c23fc76d623f04047a95cf886d4208c754f22",
          "sha256": "3bcc035058268223faff9b8466a1e2938261c6c2f7edaece7b228ebbf0bad7cd",
          "sha1": "05dfc6d0d3ad611e2c66d484f89bed2465f71a07",
          "md5": "c02f37d1c84962b5859ba2f06563a701"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03007-SNAPSHOT.jar",
          "url": "embedded-mas-0.03007-SNAPSHOT.jar",
          "size": 53525,
          "sha512": "1881bf09cb40fd742acb4eeda95449a648d4307a4d9f05e5c56cb871e7e462722b0751b9426bc8ee406f3f16334c23fc76d623f04047a95cf886d4208c754f22",
          "sha256": "3bcc035058268223faff9b8466a1e2938261c6c2f7edaece7b228ebbf0bad7cd",
          "sha1": "05dfc6d0d3ad611e2c66d484f89bed2465f71a07",
          "md5": "c02f37d1c84962b5859ba2f06563a701"
        }
      ]
    }
  ]
}
