{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04206-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04206-SNAPSHOT.jar",
          "url": "embedded-mas-0.04206-SNAPSHOT.jar",
          "size": 73074,
          "sha512": "46fd6ccf6f8b21876083b8a3afd3d31be4ff61b5a9e61faff11e437b0fa2fcfc8fd78f43e88ea744862182a800935897e0b04df9df32392fd0e87bb4434a7029",
          "sha256": "f959a60b9ba911d96e2ae1cc37d749bc45ab2b552cacb5ae4abd41ff0ad20cbb",
          "sha1": "90563360cd41c461bc1bca8c3ebe755999f7d117",
          "md5": "e35cafd938b4df558c774d4d08070329"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04206-SNAPSHOT.jar",
          "url": "embedded-mas-0.04206-SNAPSHOT.jar",
          "size": 73074,
          "sha512": "46fd6ccf6f8b21876083b8a3afd3d31be4ff61b5a9e61faff11e437b0fa2fcfc8fd78f43e88ea744862182a800935897e0b04df9df32392fd0e87bb4434a7029",
          "sha256": "f959a60b9ba911d96e2ae1cc37d749bc45ab2b552cacb5ae4abd41ff0ad20cbb",
          "sha1": "90563360cd41c461bc1bca8c3ebe755999f7d117",
          "md5": "e35cafd938b4df558c774d4d08070329"
        }
      ]
    }
  ]
}
