{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04629-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04629-DEV.jar",
          "url": "embedded-mas-0.04629-DEV.jar",
          "size": 77036,
          "sha512": "5f6500f3cbbcaec2d3ebd964aef5e64b1122baef51ccc10b395a20a1c8271a2b6f01b0321b00a642832381c95f5b704e6fbde7a79aaa05a7ee8423502656c874",
          "sha256": "2006ea23803c9fe9c45eec563998d4d7c8ac5c2d9d66c13f4d69037ee06dfb9a",
          "sha1": "0bc15e376f0934d0cc766c293d26cc404125a4cd",
          "md5": "4377ff2f9943a0c3a8507c5b46c4e13e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04629-DEV.jar",
          "url": "embedded-mas-0.04629-DEV.jar",
          "size": 77036,
          "sha512": "5f6500f3cbbcaec2d3ebd964aef5e64b1122baef51ccc10b395a20a1c8271a2b6f01b0321b00a642832381c95f5b704e6fbde7a79aaa05a7ee8423502656c874",
          "sha256": "2006ea23803c9fe9c45eec563998d4d7c8ac5c2d9d66c13f4d69037ee06dfb9a",
          "sha1": "0bc15e376f0934d0cc766c293d26cc404125a4cd",
          "md5": "4377ff2f9943a0c3a8507c5b46c4e13e"
        }
      ]
    }
  ]
}
