{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03608-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03608-SNAPSHOT.jar",
          "url": "embedded-mas-0.03608-SNAPSHOT.jar",
          "size": 65336,
          "sha512": "114b43cfc31b6d603ad0c3327a1324f64915d6523e88e3a7a382e1cb87633dfa32d6d7d31c5c2a66211e8db5716c984dc9ae426a444cd7e8f1164d3627f341b3",
          "sha256": "7cb26e01d66c5b55b165bd837582fe7b28fa0cf2b8972d95b09782a80bb62b92",
          "sha1": "a5b51b027680d953664d98f1540046659d6a691b",
          "md5": "67ca5db27504d6d92917dd7b0429ee4e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03608-SNAPSHOT.jar",
          "url": "embedded-mas-0.03608-SNAPSHOT.jar",
          "size": 65336,
          "sha512": "114b43cfc31b6d603ad0c3327a1324f64915d6523e88e3a7a382e1cb87633dfa32d6d7d31c5c2a66211e8db5716c984dc9ae426a444cd7e8f1164d3627f341b3",
          "sha256": "7cb26e01d66c5b55b165bd837582fe7b28fa0cf2b8972d95b09782a80bb62b92",
          "sha1": "a5b51b027680d953664d98f1540046659d6a691b",
          "md5": "67ca5db27504d6d92917dd7b0429ee4e"
        }
      ]
    }
  ]
}
