{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03203-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03203-SNAPSHOT.jar",
          "url": "embedded-mas-0.03203-SNAPSHOT.jar",
          "size": 62199,
          "sha512": "92e228451bb04d2596d063b324ca03b390394db93fcfd06377c93403f3b9c9ab7e69cf03f5fe2d2c48ba572b95142fdb5734eef11490eb24c61178da1ceaf778",
          "sha256": "5eb10c312be70b4152854c06e81522fe506aebd42923d9d838994c4d9a67341e",
          "sha1": "f716cfb3c121413100e5c457b6dc9b9f7ca138c7",
          "md5": "f554c41a61517504c71be75357a6cade"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03203-SNAPSHOT.jar",
          "url": "embedded-mas-0.03203-SNAPSHOT.jar",
          "size": 62199,
          "sha512": "92e228451bb04d2596d063b324ca03b390394db93fcfd06377c93403f3b9c9ab7e69cf03f5fe2d2c48ba572b95142fdb5734eef11490eb24c61178da1ceaf778",
          "sha256": "5eb10c312be70b4152854c06e81522fe506aebd42923d9d838994c4d9a67341e",
          "sha1": "f716cfb3c121413100e5c457b6dc9b9f7ca138c7",
          "md5": "f554c41a61517504c71be75357a6cade"
        }
      ]
    }
  ]
}
