{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04639-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04639-DEV.jar",
          "url": "embedded-mas-0.04639-DEV.jar",
          "size": 77416,
          "sha512": "a1df579746f5d9bfb8aabebf8fa752d67392c38821f9d20476257aa68d2ae25d34e88ee77893b935228c71ead44f56c2a72666a564db1836bb933661962f6727",
          "sha256": "6881452ba82ee42997f027943a684ed0affea49db16f28e0771e6639906cb882",
          "sha1": "c8c5ebfe380f75b46b1fef9bb1a849c14cd62a10",
          "md5": "952f4ac336afbf6ee3ca702dfdefd67e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04639-DEV.jar",
          "url": "embedded-mas-0.04639-DEV.jar",
          "size": 77416,
          "sha512": "a1df579746f5d9bfb8aabebf8fa752d67392c38821f9d20476257aa68d2ae25d34e88ee77893b935228c71ead44f56c2a72666a564db1836bb933661962f6727",
          "sha256": "6881452ba82ee42997f027943a684ed0affea49db16f28e0771e6639906cb882",
          "sha1": "c8c5ebfe380f75b46b1fef9bb1a849c14cd62a10",
          "md5": "952f4ac336afbf6ee3ca702dfdefd67e"
        }
      ]
    }
  ]
}
