{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.060b-TEMP",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.060b-TEMP.jar",
          "url": "embedded-mas-0.060b-TEMP.jar",
          "size": 103722,
          "sha512": "bfa45aab89036705c7f3f3a0f3d4e0e3dd490e403ed763894fd9cc2d8159a1e7398c000f4f05c255b1241660a7c2dbe8ca5002993e5d9f46a48e67b9a54a4cf7",
          "sha256": "779598e96ae00026f3a3ab6eee54671ed39d09e43a1eabcf577953b7f69486c4",
          "sha1": "0d455a5e90000865970dadc480520c5240fc2fc8",
          "md5": "67fab33154a03dcecbe8c2e50ff9e148"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.30"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.060b-TEMP.jar",
          "url": "embedded-mas-0.060b-TEMP.jar",
          "size": 103722,
          "sha512": "bfa45aab89036705c7f3f3a0f3d4e0e3dd490e403ed763894fd9cc2d8159a1e7398c000f4f05c255b1241660a7c2dbe8ca5002993e5d9f46a48e67b9a54a4cf7",
          "sha256": "779598e96ae00026f3a3ab6eee54671ed39d09e43a1eabcf577953b7f69486c4",
          "sha1": "0d455a5e90000865970dadc480520c5240fc2fc8",
          "md5": "67fab33154a03dcecbe8c2e50ff9e148"
        }
      ]
    }
  ]
}
