{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.02805-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02805-SNAPSHOT.jar",
          "url": "embedded-mas-0.02805-SNAPSHOT.jar",
          "size": 31786,
          "sha512": "8c70d679d956b93fccddc898c9cd582c22466ef07f6aad41d7b3944f4db93639436409fca239fc8827fc58c03c8bd4a22907b60d9373fa7034adf146924012e7",
          "sha256": "c9eaa37fcf12f68feb1761452fbe8f47c0d6d8927c6a71752d5b6219096e02d8",
          "sha1": "ab13355815ad260ebcc2a8f1fed84a12d3495664",
          "md5": "91ede2cc5a86eccd8e292dedca007be0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02805-SNAPSHOT.jar",
          "url": "embedded-mas-0.02805-SNAPSHOT.jar",
          "size": 31786,
          "sha512": "8c70d679d956b93fccddc898c9cd582c22466ef07f6aad41d7b3944f4db93639436409fca239fc8827fc58c03c8bd4a22907b60d9373fa7034adf146924012e7",
          "sha256": "c9eaa37fcf12f68feb1761452fbe8f47c0d6d8927c6a71752d5b6219096e02d8",
          "sha1": "ab13355815ad260ebcc2a8f1fed84a12d3495664",
          "md5": "91ede2cc5a86eccd8e292dedca007be0"
        }
      ]
    }
  ]
}
