{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03105-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03105-SNAPSHOT.jar",
          "url": "embedded-mas-0.03105-SNAPSHOT.jar",
          "size": 63504,
          "sha512": "014f8b496a0d9c3109fe522cb75d316b98af67d8ab7156a99de588529f167775596f01dd6788d68354303c16781d3b3a2066549766c6093e06694a65458b5042",
          "sha256": "2799f0f56334dc8411abca43b591c571d56db920a95c03409054c5bd068f4552",
          "sha1": "03d6c65ee89cc2c32d4c9e4805cc8f3c450fadd7",
          "md5": "8a12d76c0f98c0a6e6bcb1df760dce19"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03105-SNAPSHOT.jar",
          "url": "embedded-mas-0.03105-SNAPSHOT.jar",
          "size": 63504,
          "sha512": "014f8b496a0d9c3109fe522cb75d316b98af67d8ab7156a99de588529f167775596f01dd6788d68354303c16781d3b3a2066549766c6093e06694a65458b5042",
          "sha256": "2799f0f56334dc8411abca43b591c571d56db920a95c03409054c5bd068f4552",
          "sha1": "03d6c65ee89cc2c32d4c9e4805cc8f3c450fadd7",
          "md5": "8a12d76c0f98c0a6e6bcb1df760dce19"
        }
      ]
    }
  ]
}
