{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03105-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03105-SNAPSHOT.jar",
          "url": "embedded-mas-0.03105-SNAPSHOT.jar",
          "size": 63553,
          "sha512": "74bd84338924c2dff4ff5bd829351322620cf80f011c729f6a03bd486100fe8550b371f1f2c51b1d1392afd20bbf0baa76b8627b497f0581eff311be023862c9",
          "sha256": "4e84d9b45dde44e69e26dc50875381a8814090fd7e6121a93d8dc5ffa3b5c1b3",
          "sha1": "f2368800dfade9238ab792a1dedddb395bdd4a0a",
          "md5": "2e1b5716866011780b1787c863cfad14"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03105-SNAPSHOT.jar",
          "url": "embedded-mas-0.03105-SNAPSHOT.jar",
          "size": 63553,
          "sha512": "74bd84338924c2dff4ff5bd829351322620cf80f011c729f6a03bd486100fe8550b371f1f2c51b1d1392afd20bbf0baa76b8627b497f0581eff311be023862c9",
          "sha256": "4e84d9b45dde44e69e26dc50875381a8814090fd7e6121a93d8dc5ffa3b5c1b3",
          "sha1": "f2368800dfade9238ab792a1dedddb395bdd4a0a",
          "md5": "2e1b5716866011780b1787c863cfad14"
        }
      ]
    }
  ]
}
