{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04633-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04633-DEV.jar",
          "url": "embedded-mas-0.04633-DEV.jar",
          "size": 77333,
          "sha512": "7d552b704eb9cb5d8a887d69dd5582bc7a2d487975052aff1fcc8503e76c9ef1c5d0ae6320e1fade992ebdf5482443fa8235e2fe186b7aa4c3728d1b43728391",
          "sha256": "79f5b00c745d00bda32609753748ec4a787eb65e0dff4047f1f02cf27c32b0fe",
          "sha1": "ef65961d6afac32c2b716fc993b703f99f1214ab",
          "md5": "78a418b5ab82344d62b9ac8beb6b1664"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04633-DEV.jar",
          "url": "embedded-mas-0.04633-DEV.jar",
          "size": 77333,
          "sha512": "7d552b704eb9cb5d8a887d69dd5582bc7a2d487975052aff1fcc8503e76c9ef1c5d0ae6320e1fade992ebdf5482443fa8235e2fe186b7aa4c3728d1b43728391",
          "sha256": "79f5b00c745d00bda32609753748ec4a787eb65e0dff4047f1f02cf27c32b0fe",
          "sha1": "ef65961d6afac32c2b716fc993b703f99f1214ab",
          "md5": "78a418b5ab82344d62b9ac8beb6b1664"
        }
      ]
    }
  ]
}
