{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.027060703-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.027060703-SNAPSHOT.jar",
          "url": "embedded-mas-0.027060703-SNAPSHOT.jar",
          "size": 29966,
          "sha512": "a80bc9a7d0d69fd715fc60e3d8b1d6e84c499d5b20642a7e0abbaeb70b7df1ed29918e03b0f86e4e6fecf4d064c666f56714c7e81ed4fb846d491c115d5cb9c2",
          "sha256": "7115ae3913eba3a9b621e5c71eaf973d34c2e3a379669720dcf69dd483d5b3a6",
          "sha1": "06e8168612ab39f10beb7ff887eb21034d666f92",
          "md5": "b6ad9872fe9ec6ef531134f3bf3a35ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.027060703-SNAPSHOT.jar",
          "url": "embedded-mas-0.027060703-SNAPSHOT.jar",
          "size": 29966,
          "sha512": "a80bc9a7d0d69fd715fc60e3d8b1d6e84c499d5b20642a7e0abbaeb70b7df1ed29918e03b0f86e4e6fecf4d064c666f56714c7e81ed4fb846d491c115d5cb9c2",
          "sha256": "7115ae3913eba3a9b621e5c71eaf973d34c2e3a379669720dcf69dd483d5b3a6",
          "sha1": "06e8168612ab39f10beb7ff887eb21034d666f92",
          "md5": "b6ad9872fe9ec6ef531134f3bf3a35ab"
        }
      ]
    }
  ]
}
