{
  "formatVersion": "1.1",
  "component": {
    "group": "javard",
    "module": "javard",
    "version": "0.027-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "javard-0.031-2-SNAPSHOT.jar",
          "url": "javard-0.031-2-SNAPSHOT.jar",
          "size": 4690,
          "sha512": "d08b304995051df63d72cbc3a99621e1288818e62ca9bfec91bfc22e13d597570ffa3e77d89de56b98ed927867e7b37743f297e6a2da4779a7c4b93a8ea8be51",
          "sha256": "e5e16b78362b99d429c968065926168509821efa029508c6f91bdf2b0f7c29d2",
          "sha1": "74b737207b98bf2fb9757dff7dbb79f8ec7b1af3",
          "md5": "62c11cdb147703777862febf6b4acc11"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "javard-0.031-2-SNAPSHOT.jar",
          "url": "javard-0.031-2-SNAPSHOT.jar",
          "size": 4690,
          "sha512": "d08b304995051df63d72cbc3a99621e1288818e62ca9bfec91bfc22e13d597570ffa3e77d89de56b98ed927867e7b37743f297e6a2da4779a7c4b93a8ea8be51",
          "sha256": "e5e16b78362b99d429c968065926168509821efa029508c6f91bdf2b0f7c29d2",
          "sha1": "74b737207b98bf2fb9757dff7dbb79f8ec7b1af3",
          "md5": "62c11cdb147703777862febf6b4acc11"
        }
      ]
    }
  ]
}
