{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03302-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03302-SNAPSHOT.jar",
          "url": "embedded-mas-0.03302-SNAPSHOT.jar",
          "size": 61739,
          "sha512": "fa09bd8303b81c2cc1870e1b6406efe6f834cf13e3ca618e6a9432f537773c6f6cc323e5e036f38f5ece77f188635c69039d64aba267b6b7b81e3eb72d73835e",
          "sha256": "74e3033646aa15adacd48d13184de883f98ccc3dbca23938d915706077a3ccf1",
          "sha1": "97944ea08774670c0eee8d86629ff5ad2001f8dd",
          "md5": "573273fbf7f07bfae62f1acc34683408"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03302-SNAPSHOT.jar",
          "url": "embedded-mas-0.03302-SNAPSHOT.jar",
          "size": 61739,
          "sha512": "fa09bd8303b81c2cc1870e1b6406efe6f834cf13e3ca618e6a9432f537773c6f6cc323e5e036f38f5ece77f188635c69039d64aba267b6b7b81e3eb72d73835e",
          "sha256": "74e3033646aa15adacd48d13184de883f98ccc3dbca23938d915706077a3ccf1",
          "sha1": "97944ea08774670c0eee8d86629ff5ad2001f8dd",
          "md5": "573273fbf7f07bfae62f1acc34683408"
        }
      ]
    }
  ]
}
