{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03502-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03502-SNAPSHOT.jar",
          "url": "embedded-mas-0.03502-SNAPSHOT.jar",
          "size": 64172,
          "sha512": "b3617cbca12bfe5e50782100aaa6481ff09f800403c2f964917acee0dcc5eecdfca2c7d04674a37307c2e908252e2365d6bf508ab742f46f120551147f53a43a",
          "sha256": "a04a8e8f2321f5ac4ba329ba8b4d7e76259a62188b015dcb1f909989008ba9e0",
          "sha1": "9819f99bcfb6d70de3bcc389bae81323be0283c5",
          "md5": "a8956c38e3deb2034635b169bed70a36"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03502-SNAPSHOT.jar",
          "url": "embedded-mas-0.03502-SNAPSHOT.jar",
          "size": 64172,
          "sha512": "b3617cbca12bfe5e50782100aaa6481ff09f800403c2f964917acee0dcc5eecdfca2c7d04674a37307c2e908252e2365d6bf508ab742f46f120551147f53a43a",
          "sha256": "a04a8e8f2321f5ac4ba329ba8b4d7e76259a62188b015dcb1f909989008ba9e0",
          "sha1": "9819f99bcfb6d70de3bcc389bae81323be0283c5",
          "md5": "a8956c38e3deb2034635b169bed70a36"
        }
      ]
    }
  ]
}
