{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.031-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.031-SNAPSHOT.jar",
          "url": "embedded-mas-0.031-SNAPSHOT.jar",
          "size": 60380,
          "sha512": "5c1a1843c8978e56e82b64d9eda06ffc2742eb415d743081fd8b5e694ee988d9b4191344633c4ea05508ed2ec45847af8c1d9958b7738e3c85b2af20522e2e44",
          "sha256": "005769114e70ccfd1b54c758e06f88e63a64ad166b568f70bb68c18039190513",
          "sha1": "9b535d91cb15511262e7c185d59073e5a5edc4cc",
          "md5": "809de98eb526754e403ffc34f8c8e70a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.031-SNAPSHOT.jar",
          "url": "embedded-mas-0.031-SNAPSHOT.jar",
          "size": 60380,
          "sha512": "5c1a1843c8978e56e82b64d9eda06ffc2742eb415d743081fd8b5e694ee988d9b4191344633c4ea05508ed2ec45847af8c1d9958b7738e3c85b2af20522e2e44",
          "sha256": "005769114e70ccfd1b54c758e06f88e63a64ad166b568f70bb68c18039190513",
          "sha1": "9b535d91cb15511262e7c185d59073e5a5edc4cc",
          "md5": "809de98eb526754e403ffc34f8c8e70a"
        }
      ]
    }
  ]
}
