{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04607-DEVX",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04607-DEVX.jar",
          "url": "embedded-mas-0.04607-DEVX.jar",
          "size": 69440,
          "sha512": "ee92de61a5f00cde424738949f188ff59e127288e7d8e8a90f526e066e2b53a46237295330996cdfdae1152aa43df61fda317eb631934bb4832c417ef6b5befd",
          "sha256": "17116ca631133f9796e9c4042ac60589b0a83f0ea506c3016e832500116923b2",
          "sha1": "c10fa86dd901b7c13c178504e63d2f8c95a7fc6d",
          "md5": "59a805b709c23756570ef69ba74a07bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04607-DEVX.jar",
          "url": "embedded-mas-0.04607-DEVX.jar",
          "size": 69440,
          "sha512": "ee92de61a5f00cde424738949f188ff59e127288e7d8e8a90f526e066e2b53a46237295330996cdfdae1152aa43df61fda317eb631934bb4832c417ef6b5befd",
          "sha256": "17116ca631133f9796e9c4042ac60589b0a83f0ea506c3016e832500116923b2",
          "sha1": "c10fa86dd901b7c13c178504e63d2f8c95a7fc6d",
          "md5": "59a805b709c23756570ef69ba74a07bd"
        }
      ]
    }
  ]
}
