{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04650-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04650-DEV.jar",
          "url": "embedded-mas-0.04650-DEV.jar",
          "size": 69039,
          "sha512": "22dadc7ec93c97799190e7497e868834dd9457966492389c8bf0065f402786823353e0a5a06917d52dad71418ea16a5f8c7487a934b91551a8fa65d0e0d8c41d",
          "sha256": "a158bedfcf0f5860ba73bec867baef4c701d6d7f664ae7a84f61fbe4b1639d18",
          "sha1": "74c19aad5c0be7689f10659c3240cb0a7d03ba8e",
          "md5": "cf8c55cefbd8a7eba02220ad098be06c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04650-DEV.jar",
          "url": "embedded-mas-0.04650-DEV.jar",
          "size": 69039,
          "sha512": "22dadc7ec93c97799190e7497e868834dd9457966492389c8bf0065f402786823353e0a5a06917d52dad71418ea16a5f8c7487a934b91551a8fa65d0e0d8c41d",
          "sha256": "a158bedfcf0f5860ba73bec867baef4c701d6d7f664ae7a84f61fbe4b1639d18",
          "sha1": "74c19aad5c0be7689f10659c3240cb0a7d03ba8e",
          "md5": "cf8c55cefbd8a7eba02220ad098be06c"
        }
      ]
    }
  ]
}
