{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.027060701-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.027060701-SNAPSHOT.jar",
          "url": "embedded-mas-0.027060701-SNAPSHOT.jar",
          "size": 29966,
          "sha512": "ff8c894207fc39b16871f37b0dd4079e86d08d48d90ce8fda08f6329f4755e219c5f81e909af41e7b6c02009dd2539164b5ba1e5ff7d5a4f9673f5ba0531df0f",
          "sha256": "b07e10d39935f78dea66fcf1d36a913d9e4babb7bcb7dc00bf4f6803a94171d6",
          "sha1": "b824526041d8910f38b89b020a0c78066cfc37cb",
          "md5": "aae6fd2f75895a6042dde763d08203d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.027060701-SNAPSHOT.jar",
          "url": "embedded-mas-0.027060701-SNAPSHOT.jar",
          "size": 29966,
          "sha512": "ff8c894207fc39b16871f37b0dd4079e86d08d48d90ce8fda08f6329f4755e219c5f81e909af41e7b6c02009dd2539164b5ba1e5ff7d5a4f9673f5ba0531df0f",
          "sha256": "b07e10d39935f78dea66fcf1d36a913d9e4babb7bcb7dc00bf4f6803a94171d6",
          "sha1": "b824526041d8910f38b89b020a0c78066cfc37cb",
          "md5": "aae6fd2f75895a6042dde763d08203d1"
        }
      ]
    }
  ]
}
