{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04677-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04677-DEV.jar",
          "url": "embedded-mas-0.04677-DEV.jar",
          "size": 70963,
          "sha512": "3771cd610fe0cb36d968574d9275d155ccde6affcb5cb8888e99ae39bd544434ed91e050ab43bd2dcbe4439c7e923a23b2524998ff067a38346c8345c03ad64b",
          "sha256": "c6f596432e4b4534f29dc4e36645c57905e5c8962d476fb2c052499b14923b6d",
          "sha1": "51dc5b8b4a8f5927ce66c25fe499f6aec2c50c7c",
          "md5": "6cca8351ab1345555b40ab981a81bd61"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04677-DEV.jar",
          "url": "embedded-mas-0.04677-DEV.jar",
          "size": 70963,
          "sha512": "3771cd610fe0cb36d968574d9275d155ccde6affcb5cb8888e99ae39bd544434ed91e050ab43bd2dcbe4439c7e923a23b2524998ff067a38346c8345c03ad64b",
          "sha256": "c6f596432e4b4534f29dc4e36645c57905e5c8962d476fb2c052499b14923b6d",
          "sha1": "51dc5b8b4a8f5927ce66c25fe499f6aec2c50c7c",
          "md5": "6cca8351ab1345555b40ab981a81bd61"
        }
      ]
    }
  ]
}
