{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271542-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271542-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271542-SNAPSHOT.jar",
          "size": 30616,
          "sha512": "14d35c7ac4641bd16cf1393011faa604b7aa7472d7db617b786de920fa818475b219322566a3482ee1254d4c62217e6b70c744353ccc1133d189f03de94635d8",
          "sha256": "826868133e51ee30c853898ec1c6d99d2674ac24cb041167342cb95daaef091c",
          "sha1": "b9139829e2049dcb14f666817b3cef862f1f66d1",
          "md5": "6a9ea630f80b508176fb12d1e6f1a944"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271542-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271542-SNAPSHOT.jar",
          "size": 30616,
          "sha512": "14d35c7ac4641bd16cf1393011faa604b7aa7472d7db617b786de920fa818475b219322566a3482ee1254d4c62217e6b70c744353ccc1133d189f03de94635d8",
          "sha256": "826868133e51ee30c853898ec1c6d99d2674ac24cb041167342cb95daaef091c",
          "sha1": "b9139829e2049dcb14f666817b3cef862f1f66d1",
          "md5": "6a9ea630f80b508176fb12d1e6f1a944"
        }
      ]
    }
  ]
}
