{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04668-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04668-DEV.jar",
          "url": "embedded-mas-0.04668-DEV.jar",
          "size": 70725,
          "sha512": "d2b9cc467aad85173a6162ffc9e3a78ee23c49c3033a835adc559fc92c58360fa4cda64e8c809b0fac69d6170a46e3e44d7d1afa5cbc55f3f697402fa9154d0d",
          "sha256": "ab228f88c5baaa16c14406b30411e77508906967a4619eb1d7c7993eecadc5d7",
          "sha1": "5712294afee284438ca0fe65fdf41dbbd793e85c",
          "md5": "d96a9a94596980d10259d479e2c68a2b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04668-DEV.jar",
          "url": "embedded-mas-0.04668-DEV.jar",
          "size": 70725,
          "sha512": "d2b9cc467aad85173a6162ffc9e3a78ee23c49c3033a835adc559fc92c58360fa4cda64e8c809b0fac69d6170a46e3e44d7d1afa5cbc55f3f697402fa9154d0d",
          "sha256": "ab228f88c5baaa16c14406b30411e77508906967a4619eb1d7c7993eecadc5d7",
          "sha1": "5712294afee284438ca0fe65fdf41dbbd793e85c",
          "md5": "d96a9a94596980d10259d479e2c68a2b"
        }
      ]
    }
  ]
}
