{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04602-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04602-SNAPSHOT.jar",
          "url": "embedded-mas-0.04602-SNAPSHOT.jar",
          "size": 72832,
          "sha512": "ed2a9b6c4ce0ec6311071d47af8653ade05400179a6253daa95b1dc9ee52d843eb50bb709cff7aa3468d864154e3f4334992a602bb2097f3cf7e28539622d71b",
          "sha256": "a25f6ffe3eaf4c60ed7bc5d7269bb05a869405056af8c235573c1b05d5f691fb",
          "sha1": "f7a38725d67ae810843c4876f4eb2c7247d77ce3",
          "md5": "9b1fdd50e4c583fff30e6c374f13beb8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04602-SNAPSHOT.jar",
          "url": "embedded-mas-0.04602-SNAPSHOT.jar",
          "size": 72832,
          "sha512": "ed2a9b6c4ce0ec6311071d47af8653ade05400179a6253daa95b1dc9ee52d843eb50bb709cff7aa3468d864154e3f4334992a602bb2097f3cf7e28539622d71b",
          "sha256": "a25f6ffe3eaf4c60ed7bc5d7269bb05a869405056af8c235573c1b05d5f691fb",
          "sha1": "f7a38725d67ae810843c4876f4eb2c7247d77ce3",
          "md5": "9b1fdd50e4c583fff30e6c374f13beb8"
        }
      ]
    }
  ]
}
