{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04209-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04209-SNAPSHOT.jar",
          "url": "embedded-mas-0.04209-SNAPSHOT.jar",
          "size": 73138,
          "sha512": "bc1ee3ccc2a16c6fd597f0d1c8ab7aa42c42cef5f95918e7b1c02860e7e570502a650f598b6feb892b73c5c8a7e13f6a9e2664ea9b3e586d263ab2a1527394d2",
          "sha256": "7548d27ae71e0b19b6e63201aca5513eb7b208e611ad265b47e40c87bc53bb15",
          "sha1": "73d766a83f9dd7ce444a2ba481f5111f9eb53594",
          "md5": "f430bcc4c58d271fdd026d68f3941d68"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04209-SNAPSHOT.jar",
          "url": "embedded-mas-0.04209-SNAPSHOT.jar",
          "size": 73138,
          "sha512": "bc1ee3ccc2a16c6fd597f0d1c8ab7aa42c42cef5f95918e7b1c02860e7e570502a650f598b6feb892b73c5c8a7e13f6a9e2664ea9b3e586d263ab2a1527394d2",
          "sha256": "7548d27ae71e0b19b6e63201aca5513eb7b208e611ad265b47e40c87bc53bb15",
          "sha1": "73d766a83f9dd7ce444a2ba481f5111f9eb53594",
          "md5": "f430bcc4c58d271fdd026d68f3941d68"
        }
      ]
    }
  ]
}
