{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04609-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04609-SNAPSHOT.jar",
          "url": "embedded-mas-0.04609-SNAPSHOT.jar",
          "size": 69071,
          "sha512": "18b5c3b0ead513d7a293f5302e0f2c020d956f417828db879cc3996532e790ab90699cc29abe93fe53c0be41c79345bd952ce22e2d6c56b74d2f3c5f9f0757ea",
          "sha256": "5afbdd10860eee91032cf56dd1b1b37e080e57fde44f3b1d6a0cdf5a52eb3728",
          "sha1": "fba2bc4c4a84e2adf9674405fe22f1db77fe4442",
          "md5": "3171d19668696ecc809fae401552d7a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04609-SNAPSHOT.jar",
          "url": "embedded-mas-0.04609-SNAPSHOT.jar",
          "size": 69071,
          "sha512": "18b5c3b0ead513d7a293f5302e0f2c020d956f417828db879cc3996532e790ab90699cc29abe93fe53c0be41c79345bd952ce22e2d6c56b74d2f3c5f9f0757ea",
          "sha256": "5afbdd10860eee91032cf56dd1b1b37e080e57fde44f3b1d6a0cdf5a52eb3728",
          "sha1": "fba2bc4c4a84e2adf9674405fe22f1db77fe4442",
          "md5": "3171d19668696ecc809fae401552d7a2"
        }
      ]
    }
  ]
}
