{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271543-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271543-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271543-SNAPSHOT.jar",
          "size": 30616,
          "sha512": "634797a6da91be90a863fc50c504f8e1c590825a639dc24697b25cfeeaa5e35ed0861b529628a7e7ebf2ac615473dd5b7bdca269a3e5a391095b4b7f91514a79",
          "sha256": "1a77594dc7a42851ebc484eeba737a3e6a95294d7850aa1fa5d6d6ca30562373",
          "sha1": "104692cf029d5fa27023527940e6ffa78dd120dc",
          "md5": "cc0a9e8c699a76132e70a59401bdf81b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271543-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271543-SNAPSHOT.jar",
          "size": 30616,
          "sha512": "634797a6da91be90a863fc50c504f8e1c590825a639dc24697b25cfeeaa5e35ed0861b529628a7e7ebf2ac615473dd5b7bdca269a3e5a391095b4b7f91514a79",
          "sha256": "1a77594dc7a42851ebc484eeba737a3e6a95294d7850aa1fa5d6d6ca30562373",
          "sha1": "104692cf029d5fa27023527940e6ffa78dd120dc",
          "md5": "cc0a9e8c699a76132e70a59401bdf81b"
        }
      ]
    }
  ]
}
