{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03907-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03907-SNAPSHOT.jar",
          "url": "embedded-mas-0.03907-SNAPSHOT.jar",
          "size": 71393,
          "sha512": "6009ff7d72e14cc8eb20a133bd85b874493612218e12bdadd98d3c2dfd6290b414923544c5fb0cd315af280ebcbde15457ca8d01083fbab736805eb07b9180d3",
          "sha256": "a50531dd280c6070da20c11f22da55ab2e0fb1de727e673e2703781a7f4c601d",
          "sha1": "c85607511fd51966dc5c663c9c03f603886d5bdd",
          "md5": "1087d9f268be7844244f56b1c84bd346"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03907-SNAPSHOT.jar",
          "url": "embedded-mas-0.03907-SNAPSHOT.jar",
          "size": 71393,
          "sha512": "6009ff7d72e14cc8eb20a133bd85b874493612218e12bdadd98d3c2dfd6290b414923544c5fb0cd315af280ebcbde15457ca8d01083fbab736805eb07b9180d3",
          "sha256": "a50531dd280c6070da20c11f22da55ab2e0fb1de727e673e2703781a7f4c601d",
          "sha1": "c85607511fd51966dc5c663c9c03f603886d5bdd",
          "md5": "1087d9f268be7844244f56b1c84bd346"
        }
      ]
    }
  ]
}
