{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271535-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271535-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271535-SNAPSHOT.jar",
          "size": 31108,
          "sha512": "c5b7139337e60c53ddb5385918b15769619b8d5438977a8c82d6dff9d41791b363d8830e84074876adde561f0f09cdf1feb18fc45b26296d8a091a4b85363fc2",
          "sha256": "177f4600a6b43144c45e21a5dc5d663ece3f05949e17627e02dc477241817825",
          "sha1": "389af14b7f8d982e2dcbc57a16a19671b0994d30",
          "md5": "6517135dd618cfe638e10f31fa1e778c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271535-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271535-SNAPSHOT.jar",
          "size": 31108,
          "sha512": "c5b7139337e60c53ddb5385918b15769619b8d5438977a8c82d6dff9d41791b363d8830e84074876adde561f0f09cdf1feb18fc45b26296d8a091a4b85363fc2",
          "sha256": "177f4600a6b43144c45e21a5dc5d663ece3f05949e17627e02dc477241817825",
          "sha1": "389af14b7f8d982e2dcbc57a16a19671b0994d30",
          "md5": "6517135dd618cfe638e10f31fa1e778c"
        }
      ]
    }
  ]
}
