{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03054-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03054-SNAPSHOT.jar",
          "url": "embedded-mas-0.03054-SNAPSHOT.jar",
          "size": 60614,
          "sha512": "e3733420afb6b30409d55235ca04daaaf825a24c2e0a7081705abe89397115e0601f89ce9bce9522f6fd8e9d77faa3c3d6b565234e732837fe569bd1c86b1e14",
          "sha256": "2cf2ecf54cfa0c581a0d894d61f405c05585f7ff4fe745879de1a7d70aef2702",
          "sha1": "bbc7b95b9e9df8da2fdbb56ee18efe0cc6c02e8d",
          "md5": "901d7be0a9ab69ffe1435184de498867"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03054-SNAPSHOT.jar",
          "url": "embedded-mas-0.03054-SNAPSHOT.jar",
          "size": 60614,
          "sha512": "e3733420afb6b30409d55235ca04daaaf825a24c2e0a7081705abe89397115e0601f89ce9bce9522f6fd8e9d77faa3c3d6b565234e732837fe569bd1c86b1e14",
          "sha256": "2cf2ecf54cfa0c581a0d894d61f405c05585f7ff4fe745879de1a7d70aef2702",
          "sha1": "bbc7b95b9e9df8da2fdbb56ee18efe0cc6c02e8d",
          "md5": "901d7be0a9ab69ffe1435184de498867"
        }
      ]
    }
  ]
}
