{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271536-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271536-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271536-SNAPSHOT.jar",
          "size": 31116,
          "sha512": "acdd91761e1072b687671677f86ef758beac2fc8052033a38b07067f043f36f5b9c19a12b4c02c152599b8f15675d9e627b2138c352c0983c728aaa0880571b5",
          "sha256": "faa5500e8b43124f6dc61a1008e06e854d3a841bd30fa83439a957db94c13f7e",
          "sha1": "63fe3aa9ef2ee834bcdeedfd787e1d7a4a32e6c6",
          "md5": "f25d1533e1477101a8292c8b7b84b7c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271536-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271536-SNAPSHOT.jar",
          "size": 31116,
          "sha512": "acdd91761e1072b687671677f86ef758beac2fc8052033a38b07067f043f36f5b9c19a12b4c02c152599b8f15675d9e627b2138c352c0983c728aaa0880571b5",
          "sha256": "faa5500e8b43124f6dc61a1008e06e854d3a841bd30fa83439a957db94c13f7e",
          "sha1": "63fe3aa9ef2ee834bcdeedfd787e1d7a4a32e6c6",
          "md5": "f25d1533e1477101a8292c8b7b84b7c5"
        }
      ]
    }
  ]
}
