{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.038008-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038008-SNAPSHOT.jar",
          "url": "embedded-mas-0.038008-SNAPSHOT.jar",
          "size": 74512,
          "sha512": "46e79412b7ea66bbddbdbcd6ccfbeacdb8f88383ef134d06102249971b5332ba1f7fd7251e18cd0230602b2e7bd84085e3913f500a69b86ec85a3bd611d347dd",
          "sha256": "581573fe8a6374c9e65c854f9dbda1413aeb60209051a8bb954cf25b8d9f7d90",
          "sha1": "628744d2de1f165f9dabd286ff366cd6d63a6473",
          "md5": "68f3cfe7307026174af286489b44df3d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038008-SNAPSHOT.jar",
          "url": "embedded-mas-0.038008-SNAPSHOT.jar",
          "size": 74512,
          "sha512": "46e79412b7ea66bbddbdbcd6ccfbeacdb8f88383ef134d06102249971b5332ba1f7fd7251e18cd0230602b2e7bd84085e3913f500a69b86ec85a3bd611d347dd",
          "sha256": "581573fe8a6374c9e65c854f9dbda1413aeb60209051a8bb954cf25b8d9f7d90",
          "sha1": "628744d2de1f165f9dabd286ff366cd6d63a6473",
          "md5": "68f3cfe7307026174af286489b44df3d"
        }
      ]
    }
  ]
}
