{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271201-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271201-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271201-SNAPSHOT.jar",
          "size": 29999,
          "sha512": "cb95308977e916ab4a47bf65332e4661e82770108e75810728781aea14c548331169cc0df1404ceb3f0b0b436a15ce29c9f5f0965b31ede9643392b3ef985b22",
          "sha256": "427b1616ec6f19b316f1d64f89478a3ab665d6fa9e5a8bdafebd665af1afc74c",
          "sha1": "e7b6026df86ac0a51e5bab92d38a0f186f447a1e",
          "md5": "4a344398ea6b91ceb78784871014716a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271201-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271201-SNAPSHOT.jar",
          "size": 29999,
          "sha512": "cb95308977e916ab4a47bf65332e4661e82770108e75810728781aea14c548331169cc0df1404ceb3f0b0b436a15ce29c9f5f0965b31ede9643392b3ef985b22",
          "sha256": "427b1616ec6f19b316f1d64f89478a3ab665d6fa9e5a8bdafebd665af1afc74c",
          "sha1": "e7b6026df86ac0a51e5bab92d38a0f186f447a1e",
          "md5": "4a344398ea6b91ceb78784871014716a"
        }
      ]
    }
  ]
}
