{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03029-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03029-SNAPSHOT.jar",
          "url": "embedded-mas-0.03029-SNAPSHOT.jar",
          "size": 59744,
          "sha512": "cec173a0c9e8ac1ef1e3203a429da51f00f7e39de99a820f8f40dfacd9011f904c02eb2c3eb8ec736cc2ed379e008ec8ba5fd5b86cc5fdb5f6a5d6265d8d6859",
          "sha256": "dd0125114aa20208b7b7c818396dc9bdd37aa02f456c40f196d596ebbdff463f",
          "sha1": "b71bae56e20b5288ea8664155ca9295820a01cee",
          "md5": "cfd1f2ec8dfd6800a01c585b97cdad88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03029-SNAPSHOT.jar",
          "url": "embedded-mas-0.03029-SNAPSHOT.jar",
          "size": 59744,
          "sha512": "cec173a0c9e8ac1ef1e3203a429da51f00f7e39de99a820f8f40dfacd9011f904c02eb2c3eb8ec736cc2ed379e008ec8ba5fd5b86cc5fdb5f6a5d6265d8d6859",
          "sha256": "dd0125114aa20208b7b7c818396dc9bdd37aa02f456c40f196d596ebbdff463f",
          "sha1": "b71bae56e20b5288ea8664155ca9295820a01cee",
          "md5": "cfd1f2ec8dfd6800a01c585b97cdad88"
        }
      ]
    }
  ]
}
