{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04207-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04207-SNAPSHOT.jar",
          "url": "embedded-mas-0.04207-SNAPSHOT.jar",
          "size": 73215,
          "sha512": "21c4dd24d9730025ce12af504015d60181f83f900b95f1f27eba5a4b142f9283c5435705e176fc66a06ac63063dea3bbcb3f36fe12f71393468ae046c571dd78",
          "sha256": "9428d955905d80b205c8a917c451e3db67f5f3c287bfa5b0b33298fddef9cf7a",
          "sha1": "b37179e3b2c7198e70038c116add483dfbc2832f",
          "md5": "ebaea15379b96a761546a65a49633061"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04207-SNAPSHOT.jar",
          "url": "embedded-mas-0.04207-SNAPSHOT.jar",
          "size": 73215,
          "sha512": "21c4dd24d9730025ce12af504015d60181f83f900b95f1f27eba5a4b142f9283c5435705e176fc66a06ac63063dea3bbcb3f36fe12f71393468ae046c571dd78",
          "sha256": "9428d955905d80b205c8a917c451e3db67f5f3c287bfa5b0b33298fddef9cf7a",
          "sha1": "b37179e3b2c7198e70038c116add483dfbc2832f",
          "md5": "ebaea15379b96a761546a65a49633061"
        }
      ]
    }
  ]
}
