{
  "formatVersion": "1.1",
  "component": {
    "group": "javard",
    "module": "javard",
    "version": "0.027-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "javard-0.031-3-SNAPSHOT.jar",
          "url": "javard-0.031-3-SNAPSHOT.jar",
          "size": 4690,
          "sha512": "db57425cb18c9459ec1ddfb31cac55ae4e8039a87c9b5f543bb39731586fbde5a108b938d0a274bcb5d5627a75469f92ee3906ad8adcc7cf2a3510134f52b560",
          "sha256": "af51f626385635690dcf39ad0375928e3a5a0d40d725057959273d8253df8cd4",
          "sha1": "19c7d2e45f9ab47130bffa6cbb5896687761a463",
          "md5": "8578a446034071c83f7880244365c4ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "javard-0.031-3-SNAPSHOT.jar",
          "url": "javard-0.031-3-SNAPSHOT.jar",
          "size": 4690,
          "sha512": "db57425cb18c9459ec1ddfb31cac55ae4e8039a87c9b5f543bb39731586fbde5a108b938d0a274bcb5d5627a75469f92ee3906ad8adcc7cf2a3510134f52b560",
          "sha256": "af51f626385635690dcf39ad0375928e3a5a0d40d725057959273d8253df8cd4",
          "sha1": "19c7d2e45f9ab47130bffa6cbb5896687761a463",
          "md5": "8578a446034071c83f7880244365c4ed"
        }
      ]
    }
  ]
}
