{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03050-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03050-SNAPSHOT.jar",
          "url": "embedded-mas-0.03050-SNAPSHOT.jar",
          "size": 60543,
          "sha512": "643b05b3ca4a54adc9ba977395a510b99094e31af9106fd25c5b3c3f6ba647b472542ffbf9af6565315a84d2c04510de162182e4869b0ff58be44f498671ccb8",
          "sha256": "8d2e8d34e6343593852686f470871a00db409a16ba96d8c9a3fd4fb84d4dc857",
          "sha1": "8806610ca4eef23e94c5a2484f5f8227f8d72363",
          "md5": "acdb26cb4402fdf0eece793c66abe8be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03050-SNAPSHOT.jar",
          "url": "embedded-mas-0.03050-SNAPSHOT.jar",
          "size": 60543,
          "sha512": "643b05b3ca4a54adc9ba977395a510b99094e31af9106fd25c5b3c3f6ba647b472542ffbf9af6565315a84d2c04510de162182e4869b0ff58be44f498671ccb8",
          "sha256": "8d2e8d34e6343593852686f470871a00db409a16ba96d8c9a3fd4fb84d4dc857",
          "sha1": "8806610ca4eef23e94c5a2484f5f8227f8d72363",
          "md5": "acdb26cb4402fdf0eece793c66abe8be"
        }
      ]
    }
  ]
}
