{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04666-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04666-DEV.jar",
          "url": "embedded-mas-0.04666-DEV.jar",
          "size": 70702,
          "sha512": "f49befa457a2727a884accd3ff3ddd40b8c08e85af3f6bfd8f86a40a5348bb15e6971ed3802a725cdf3a371fea69eadfc848c0747b640f8bea0f50a0b759ca44",
          "sha256": "6b92022887b6164f686ca1a40e27575dfdc2b7961be786422e99c8a16f241c39",
          "sha1": "5f63e9910bbfb3085196145b4db774260adf4646",
          "md5": "92033142f507f7253672c85fd3fe001d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04666-DEV.jar",
          "url": "embedded-mas-0.04666-DEV.jar",
          "size": 70702,
          "sha512": "f49befa457a2727a884accd3ff3ddd40b8c08e85af3f6bfd8f86a40a5348bb15e6971ed3802a725cdf3a371fea69eadfc848c0747b640f8bea0f50a0b759ca44",
          "sha256": "6b92022887b6164f686ca1a40e27575dfdc2b7961be786422e99c8a16f241c39",
          "sha1": "5f63e9910bbfb3085196145b4db774260adf4646",
          "md5": "92033142f507f7253672c85fd3fe001d"
        }
      ]
    }
  ]
}
