{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03037-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03037-SNAPSHOT.jar",
          "url": "embedded-mas-0.03037-SNAPSHOT.jar",
          "size": 61638,
          "sha512": "821818d92c1dafeefcdb4ed1fbd399905739e19611553782ea6383a6cb4e5f1ce622e29485cc45ac8f01fffc09633fc8f6e27c635de98942d1d16e0bfb4b937a",
          "sha256": "13d69c91890260d2ee621ee260e1ad74f3c9208f3207c9c9923811ff5fdec315",
          "sha1": "2e631747745c65f46d772c88adbad718c846253b",
          "md5": "30765bcf5dd45bd78d5b2939470553fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03037-SNAPSHOT.jar",
          "url": "embedded-mas-0.03037-SNAPSHOT.jar",
          "size": 61638,
          "sha512": "821818d92c1dafeefcdb4ed1fbd399905739e19611553782ea6383a6cb4e5f1ce622e29485cc45ac8f01fffc09633fc8f6e27c635de98942d1d16e0bfb4b937a",
          "sha256": "13d69c91890260d2ee621ee260e1ad74f3c9208f3207c9c9923811ff5fdec315",
          "sha1": "2e631747745c65f46d772c88adbad718c846253b",
          "md5": "30765bcf5dd45bd78d5b2939470553fb"
        }
      ]
    }
  ]
}
