{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03027-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03027-SNAPSHOT.jar",
          "url": "embedded-mas-0.03027-SNAPSHOT.jar",
          "size": 58760,
          "sha512": "42ec12a0fed55f9c54fee78998673f8d81b2911e7234959fce04435a3e5bb0771b1fa08cea6751ca051e29842919ae9e3d39d822e29a7e02296e1b7db72b7d8c",
          "sha256": "db87aa385952cec19d2ab1440be0c67fb3ee0b18a15936464e2ce5b545109d1c",
          "sha1": "a6d546ba1522e5be2fa792a64c95059d4e938ee3",
          "md5": "b4ff01837752d9fc357c928c2a981340"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03027-SNAPSHOT.jar",
          "url": "embedded-mas-0.03027-SNAPSHOT.jar",
          "size": 58760,
          "sha512": "42ec12a0fed55f9c54fee78998673f8d81b2911e7234959fce04435a3e5bb0771b1fa08cea6751ca051e29842919ae9e3d39d822e29a7e02296e1b7db72b7d8c",
          "sha256": "db87aa385952cec19d2ab1440be0c67fb3ee0b18a15936464e2ce5b545109d1c",
          "sha1": "a6d546ba1522e5be2fa792a64c95059d4e938ee3",
          "md5": "b4ff01837752d9fc357c928c2a981340"
        }
      ]
    }
  ]
}
