{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.02804-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02804-SNAPSHOT.jar",
          "url": "embedded-mas-0.02804-SNAPSHOT.jar",
          "size": 31804,
          "sha512": "4f11fc065522b4a69ed9ac78df284799b07aa6d19fb94dbc32ee0f2b3b29b2a894443eb84ed2e032c78b6a846e4f4067a8ac588ba8a90f11c30312a7a6cbcca6",
          "sha256": "4f33a684260b5f3c30f9ead139c09b9fe148aebf8fda3451c0fb4cb9d64470cc",
          "sha1": "65f5b3ea74368196f2ce8862ffe407ecb37d3a2e",
          "md5": "73e9b75be3e592a3a457344596c3111f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02804-SNAPSHOT.jar",
          "url": "embedded-mas-0.02804-SNAPSHOT.jar",
          "size": 31804,
          "sha512": "4f11fc065522b4a69ed9ac78df284799b07aa6d19fb94dbc32ee0f2b3b29b2a894443eb84ed2e032c78b6a846e4f4067a8ac588ba8a90f11c30312a7a6cbcca6",
          "sha256": "4f33a684260b5f3c30f9ead139c09b9fe148aebf8fda3451c0fb4cb9d64470cc",
          "sha1": "65f5b3ea74368196f2ce8862ffe407ecb37d3a2e",
          "md5": "73e9b75be3e592a3a457344596c3111f"
        }
      ]
    }
  ]
}
