{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03017-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03017-SNAPSHOT.jar",
          "url": "embedded-mas-0.03017-SNAPSHOT.jar",
          "size": 53466,
          "sha512": "e9f1d541dddc37482ae1803f27bf9fc6bd80894badf0a663d7df42288874f2287e26c5838977af0405a47c103aea098126bd2cfc2d93882ca844040f6120f5ea",
          "sha256": "8f03d1f9403a971a9cb4426cc8a42bdaa7f202c6c708c22e50f77421141410b9",
          "sha1": "ab6b1265dff98cff1e77abbba2a55fffd93cefb0",
          "md5": "23b57cba80fc47c933fcf8d141819ae4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03017-SNAPSHOT.jar",
          "url": "embedded-mas-0.03017-SNAPSHOT.jar",
          "size": 53466,
          "sha512": "e9f1d541dddc37482ae1803f27bf9fc6bd80894badf0a663d7df42288874f2287e26c5838977af0405a47c103aea098126bd2cfc2d93882ca844040f6120f5ea",
          "sha256": "8f03d1f9403a971a9cb4426cc8a42bdaa7f202c6c708c22e50f77421141410b9",
          "sha1": "ab6b1265dff98cff1e77abbba2a55fffd93cefb0",
          "md5": "23b57cba80fc47c933fcf8d141819ae4"
        }
      ]
    }
  ]
}
