{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0401-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0401-SNAPSHOT.jar",
          "url": "embedded-mas-0.0401-SNAPSHOT.jar",
          "size": 72645,
          "sha512": "dfc6fa98f766249c9ccc3136bc80afc6b60a329f2f3848ddb9a9e503a55e1ad5fe59fe83cec8d6652f98bbe6a273aa76c9875649fecc4e4473375b3a95f2d1a6",
          "sha256": "58e3d2147d589c971cf29c0a63447e01a00426fd8a972ed7a9f2a2d2b9988357",
          "sha1": "2590aa0eb7e9c057b1b764e015decde9be413129",
          "md5": "a810916b3cca360f606eac5f7bf45d71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0401-SNAPSHOT.jar",
          "url": "embedded-mas-0.0401-SNAPSHOT.jar",
          "size": 72645,
          "sha512": "dfc6fa98f766249c9ccc3136bc80afc6b60a329f2f3848ddb9a9e503a55e1ad5fe59fe83cec8d6652f98bbe6a273aa76c9875649fecc4e4473375b3a95f2d1a6",
          "sha256": "58e3d2147d589c971cf29c0a63447e01a00426fd8a972ed7a9f2a2d2b9988357",
          "sha1": "2590aa0eb7e9c057b1b764e015decde9be413129",
          "md5": "a810916b3cca360f606eac5f7bf45d71"
        }
      ]
    }
  ]
}
