{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04640-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04640-DEV.jar",
          "url": "embedded-mas-0.04640-DEV.jar",
          "size": 77431,
          "sha512": "1552939fda251b5296a1370e4622e7b53570d4854b4dc682d7abbde36ada45e80c37ce72292eca0f2d31fdd45baa88a62769282d09d5d6e5cee6b0adc8962de8",
          "sha256": "61d196c7608e4f6641ba5ecd985c65f207db923f41da81dd3423e77dfd8c5b5a",
          "sha1": "7b29f16b28e88486bfdc26ef3b90eadccd7826fc",
          "md5": "7d15fab74dec14926e5c26502693cb1c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04640-DEV.jar",
          "url": "embedded-mas-0.04640-DEV.jar",
          "size": 77431,
          "sha512": "1552939fda251b5296a1370e4622e7b53570d4854b4dc682d7abbde36ada45e80c37ce72292eca0f2d31fdd45baa88a62769282d09d5d6e5cee6b0adc8962de8",
          "sha256": "61d196c7608e4f6641ba5ecd985c65f207db923f41da81dd3423e77dfd8c5b5a",
          "sha1": "7b29f16b28e88486bfdc26ef3b90eadccd7826fc",
          "md5": "7d15fab74dec14926e5c26502693cb1c"
        }
      ]
    }
  ]
}
