{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04801-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04801-SNAPSHOT.jar",
          "url": "embedded-mas-0.04801-SNAPSHOT.jar",
          "size": 73672,
          "sha512": "fc6f41bea891453e2bc946bbf5442d7419b18baf295c75b6711eb4324242f86e4326cb7ff48e3363cb53be8bcfda115e2fa51be0ceeb92e6bf65b2afc08eb68f",
          "sha256": "69a4dbd0a57ac8ba946aeffc1c56c87ee0f7800baf65d57f09172fffd0bdb743",
          "sha1": "cbcd6526d01018f7b227a647303a9da441816279",
          "md5": "ae75fcc825e393b2047ed8c568e0e87b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04801-SNAPSHOT.jar",
          "url": "embedded-mas-0.04801-SNAPSHOT.jar",
          "size": 73672,
          "sha512": "fc6f41bea891453e2bc946bbf5442d7419b18baf295c75b6711eb4324242f86e4326cb7ff48e3363cb53be8bcfda115e2fa51be0ceeb92e6bf65b2afc08eb68f",
          "sha256": "69a4dbd0a57ac8ba946aeffc1c56c87ee0f7800baf65d57f09172fffd0bdb743",
          "sha1": "cbcd6526d01018f7b227a647303a9da441816279",
          "md5": "ae75fcc825e393b2047ed8c568e0e87b"
        }
      ]
    }
  ]
}
