{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.02803-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02803-SNAPSHOT.jar",
          "url": "embedded-mas-0.02803-SNAPSHOT.jar",
          "size": 30581,
          "sha512": "a25524c1e9ce23b5bd5e42a780fbfbc93f6f466b4b7fe51f98741bfe15cc060137a987e5b34a15d5fa0cffdccabf245b652aac2e0b4bc3381718a2bbf956086c",
          "sha256": "b748c45d2bcebb2f907027ab84e8e5ef29c8159dfd37e9f3b6c1f58ccc86c6a2",
          "sha1": "d6cab391768ac2f04cba2d953a061d006e93579e",
          "md5": "e0a1bf9c7930e482b633b384241d25df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02803-SNAPSHOT.jar",
          "url": "embedded-mas-0.02803-SNAPSHOT.jar",
          "size": 30581,
          "sha512": "a25524c1e9ce23b5bd5e42a780fbfbc93f6f466b4b7fe51f98741bfe15cc060137a987e5b34a15d5fa0cffdccabf245b652aac2e0b4bc3381718a2bbf956086c",
          "sha256": "b748c45d2bcebb2f907027ab84e8e5ef29c8159dfd37e9f3b6c1f58ccc86c6a2",
          "sha1": "d6cab391768ac2f04cba2d953a061d006e93579e",
          "md5": "e0a1bf9c7930e482b633b384241d25df"
        }
      ]
    }
  ]
}
