{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04642-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04642-DEV.jar",
          "url": "embedded-mas-0.04642-DEV.jar",
          "size": 77345,
          "sha512": "94b85ea79e679ca778d79438292f852acc4cd2f971b456cc4e1f51085d5af81a72d3bb0cabb0b76e346fd77cc9314af0777d9e1c4221fb681f50b6fa6fc62408",
          "sha256": "190a65c0a65bf930806cb024e666bf810930fd44f15c5112537017a08aa0d036",
          "sha1": "45bb0f3c1487a42ede1167f4715848bd00b2dc9b",
          "md5": "211b3602688d1cc241925923b26d4de9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04642-DEV.jar",
          "url": "embedded-mas-0.04642-DEV.jar",
          "size": 77345,
          "sha512": "94b85ea79e679ca778d79438292f852acc4cd2f971b456cc4e1f51085d5af81a72d3bb0cabb0b76e346fd77cc9314af0777d9e1c4221fb681f50b6fa6fc62408",
          "sha256": "190a65c0a65bf930806cb024e666bf810930fd44f15c5112537017a08aa0d036",
          "sha1": "45bb0f3c1487a42ede1167f4715848bd00b2dc9b",
          "md5": "211b3602688d1cc241925923b26d4de9"
        }
      ]
    }
  ]
}
