{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04627-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04627-SNAPSHOT.jar",
          "url": "embedded-mas-0.04627-SNAPSHOT.jar",
          "size": 74054,
          "sha512": "85b29a9ca826271bff2272189cb2dcfd4ab02ebdb203122713ce324ee04660223761c31f5e7caf6adce2e564bcd76f70a6cfac4de92b3d1d872d3867df599b3f",
          "sha256": "c0018ab671dca74ad28286e29d584aaca3b9147db06ff58cf44009fbc6b8067b",
          "sha1": "fcee4ae83f080b6331f4e0a2137411d1932e1f30",
          "md5": "dccf3a969db06dc710f77008e759869b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04627-SNAPSHOT.jar",
          "url": "embedded-mas-0.04627-SNAPSHOT.jar",
          "size": 74054,
          "sha512": "85b29a9ca826271bff2272189cb2dcfd4ab02ebdb203122713ce324ee04660223761c31f5e7caf6adce2e564bcd76f70a6cfac4de92b3d1d872d3867df599b3f",
          "sha256": "c0018ab671dca74ad28286e29d584aaca3b9147db06ff58cf44009fbc6b8067b",
          "sha1": "fcee4ae83f080b6331f4e0a2137411d1932e1f30",
          "md5": "dccf3a969db06dc710f77008e759869b"
        }
      ]
    }
  ]
}
