{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271518-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271518-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271518-SNAPSHOT.jar",
          "size": 30725,
          "sha512": "84bbaa37dfbf29d4eadd47284528e66329f921a26fa0fe2c5f085abcfe88c620299aef1f09fc927771d1c6e3731400343dd7c42ac21f9ffbc1c60c802035da0d",
          "sha256": "060956b7410e745d041e317473cb945b7ced517a563a0ed06970a65935e2a6c8",
          "sha1": "aec9ee7320bbb38bf009de3fd6a694489a2e0e30",
          "md5": "6a80df39bcd08465351375acfaa6bd9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271518-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271518-SNAPSHOT.jar",
          "size": 30725,
          "sha512": "84bbaa37dfbf29d4eadd47284528e66329f921a26fa0fe2c5f085abcfe88c620299aef1f09fc927771d1c6e3731400343dd7c42ac21f9ffbc1c60c802035da0d",
          "sha256": "060956b7410e745d041e317473cb945b7ced517a563a0ed06970a65935e2a6c8",
          "sha1": "aec9ee7320bbb38bf009de3fd6a694489a2e0e30",
          "md5": "6a80df39bcd08465351375acfaa6bd9c"
        }
      ]
    }
  ]
}
