{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.038012-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038012-SNAPSHOT.jar",
          "url": "embedded-mas-0.038012-SNAPSHOT.jar",
          "size": 74593,
          "sha512": "fe190fb2dbbaccd9400a727e0552efd3603c84b1ea95b05670675adf0ffe25a5e759896aeb8f3e30840bbeb4098b1a77b5c1f61ebe5c09232fa88f1ec775dc01",
          "sha256": "55ab2b21d50767849b13fd0e4d4577580f3634320a6e57ae0bc44b3136c4dd4b",
          "sha1": "348c650db12fd7f8b8d603498d41ea7b8401bc9c",
          "md5": "b48970e66989b8df01921d3cef307858"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038012-SNAPSHOT.jar",
          "url": "embedded-mas-0.038012-SNAPSHOT.jar",
          "size": 74593,
          "sha512": "fe190fb2dbbaccd9400a727e0552efd3603c84b1ea95b05670675adf0ffe25a5e759896aeb8f3e30840bbeb4098b1a77b5c1f61ebe5c09232fa88f1ec775dc01",
          "sha256": "55ab2b21d50767849b13fd0e4d4577580f3634320a6e57ae0bc44b3136c4dd4b",
          "sha1": "348c650db12fd7f8b8d603498d41ea7b8401bc9c",
          "md5": "b48970e66989b8df01921d3cef307858"
        }
      ]
    }
  ]
}
