{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271541-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271541-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271541-SNAPSHOT.jar",
          "size": 30673,
          "sha512": "74a1eb85896c99e173a08dd0fa7f29b869907e0696588a8fe6a1173bee65883bf93ec2a2b8f4d673f82f61aeb4eb1bd7c64bcd41ad9782c0d0fc430a39bbe5cf",
          "sha256": "612634b4ee3dd13b3f9f43ce6267dadb5d47a311aa0f7fd93bac4dca7726fc23",
          "sha1": "6a758ad3c560f1f6bf12498b784be87ea033ce20",
          "md5": "f199aa321bad34e234b88f40fc0f05b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271541-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271541-SNAPSHOT.jar",
          "size": 30673,
          "sha512": "74a1eb85896c99e173a08dd0fa7f29b869907e0696588a8fe6a1173bee65883bf93ec2a2b8f4d673f82f61aeb4eb1bd7c64bcd41ad9782c0d0fc430a39bbe5cf",
          "sha256": "612634b4ee3dd13b3f9f43ce6267dadb5d47a311aa0f7fd93bac4dca7726fc23",
          "sha1": "6a758ad3c560f1f6bf12498b784be87ea033ce20",
          "md5": "f199aa321bad34e234b88f40fc0f05b2"
        }
      ]
    }
  ]
}
