{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03048-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03048-SNAPSHOT.jar",
          "url": "embedded-mas-0.03048-SNAPSHOT.jar",
          "size": 60458,
          "sha512": "1c3bb6c9f29843cb8fad69affa849865f3b05c76d93ce72eda6c774170999fcfbeb8aae44fd0caf97b2df316f1576df70cf7522a81ff379d3f2c24fc97cc4a09",
          "sha256": "785f657c50e4401ee62a721ac78a381f2d8dbde564eeaf0c001ceedad171af30",
          "sha1": "fe6638bacbe36c9f4a9733378a703c533b86c2a0",
          "md5": "56e3f7c8a24759dc816d9b3785532732"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03048-SNAPSHOT.jar",
          "url": "embedded-mas-0.03048-SNAPSHOT.jar",
          "size": 60458,
          "sha512": "1c3bb6c9f29843cb8fad69affa849865f3b05c76d93ce72eda6c774170999fcfbeb8aae44fd0caf97b2df316f1576df70cf7522a81ff379d3f2c24fc97cc4a09",
          "sha256": "785f657c50e4401ee62a721ac78a381f2d8dbde564eeaf0c001ceedad171af30",
          "sha1": "fe6638bacbe36c9f4a9733378a703c533b86c2a0",
          "md5": "56e3f7c8a24759dc816d9b3785532732"
        }
      ]
    }
  ]
}
