{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271528-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271528-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271528-SNAPSHOT.jar",
          "size": 30972,
          "sha512": "8989dd8a2781e32d4d9347e5e1476457af0dbecd2ee068d8a1ea732c2a09044aeba034512cd9e6c79718f721cf87172c39f072cb85aa0de14f3f375e9b4e4650",
          "sha256": "bae44f0fcd6f7fb4504da84a7211ee1256888486f5ae78bd7ce62f9e7412324c",
          "sha1": "c1eaa670561854f0cc0beab86956a5f1562e417f",
          "md5": "60afa9d7a8a76a9c3af9100bfd037005"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271528-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271528-SNAPSHOT.jar",
          "size": 30972,
          "sha512": "8989dd8a2781e32d4d9347e5e1476457af0dbecd2ee068d8a1ea732c2a09044aeba034512cd9e6c79718f721cf87172c39f072cb85aa0de14f3f375e9b4e4650",
          "sha256": "bae44f0fcd6f7fb4504da84a7211ee1256888486f5ae78bd7ce62f9e7412324c",
          "sha1": "c1eaa670561854f0cc0beab86956a5f1562e417f",
          "md5": "60afa9d7a8a76a9c3af9100bfd037005"
        }
      ]
    }
  ]
}
