{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.038016-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038016-SNAPSHOT.jar",
          "url": "embedded-mas-0.038016-SNAPSHOT.jar",
          "size": 74512,
          "sha512": "09995b97ccd08cec04b20781a9c3552be763d4808d7f24ed2a828ab6e5c07b5448613e6e860c814bc720524b00072843f5c0ecc0636921c64627e028a3970975",
          "sha256": "ebf81c424d98c47bcf528b9ca6423de6257ec0f74b8e0b9d782e6f41603d75c4",
          "sha1": "4ba0e3a1b301225a75232331c0af8d093aec822b",
          "md5": "99d8371849255715113406ce536e5485"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038016-SNAPSHOT.jar",
          "url": "embedded-mas-0.038016-SNAPSHOT.jar",
          "size": 74512,
          "sha512": "09995b97ccd08cec04b20781a9c3552be763d4808d7f24ed2a828ab6e5c07b5448613e6e860c814bc720524b00072843f5c0ecc0636921c64627e028a3970975",
          "sha256": "ebf81c424d98c47bcf528b9ca6423de6257ec0f74b8e0b9d782e6f41603d75c4",
          "sha1": "4ba0e3a1b301225a75232331c0af8d093aec822b",
          "md5": "99d8371849255715113406ce536e5485"
        }
      ]
    }
  ]
}
