{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271507-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271507-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271507-SNAPSHOT.jar",
          "size": 30364,
          "sha512": "3e56f03c2c81947fa274be9d77882380884cd7eaccd2d86f18fbb2a8c9b18a8330ab7ec0500c712e881cfa3be6c52c42f01d41bea92bf80f3af8bef350bfa9d6",
          "sha256": "efabcd4c36b47ca5ad7f3389fd3f4e08c2fbac5daf50d6f3db39db495dfcd522",
          "sha1": "dd3c1e595c0a4e5c41010c96145cc4bd54b38eb6",
          "md5": "f958300e22fc8d83b6ad1d69b43c2a7b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271507-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271507-SNAPSHOT.jar",
          "size": 30364,
          "sha512": "3e56f03c2c81947fa274be9d77882380884cd7eaccd2d86f18fbb2a8c9b18a8330ab7ec0500c712e881cfa3be6c52c42f01d41bea92bf80f3af8bef350bfa9d6",
          "sha256": "efabcd4c36b47ca5ad7f3389fd3f4e08c2fbac5daf50d6f3db39db495dfcd522",
          "sha1": "dd3c1e595c0a4e5c41010c96145cc4bd54b38eb6",
          "md5": "f958300e22fc8d83b6ad1d69b43c2a7b"
        }
      ]
    }
  ]
}
