{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03013-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03013-SNAPSHOT.jar",
          "url": "embedded-mas-0.03013-SNAPSHOT.jar",
          "size": 53978,
          "sha512": "d9926f29fea580c53c79920445589f4c888e1b29ea2f608a2718823aad6b2ff5cdd183c9b9346a7b42cc6fd515223b30189363728b7a986d345de90283b28e9a",
          "sha256": "29a697dabf27b72e218ac5c160efa973f43b0418c59a7db5ac888beb5eef9efa",
          "sha1": "187f75770a5cdc340b0bb9e5bbff2261e39e26da",
          "md5": "e579e0470545a117bdc1bdd42193249b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03013-SNAPSHOT.jar",
          "url": "embedded-mas-0.03013-SNAPSHOT.jar",
          "size": 53978,
          "sha512": "d9926f29fea580c53c79920445589f4c888e1b29ea2f608a2718823aad6b2ff5cdd183c9b9346a7b42cc6fd515223b30189363728b7a986d345de90283b28e9a",
          "sha256": "29a697dabf27b72e218ac5c160efa973f43b0418c59a7db5ac888beb5eef9efa",
          "sha1": "187f75770a5cdc340b0bb9e5bbff2261e39e26da",
          "md5": "e579e0470545a117bdc1bdd42193249b"
        }
      ]
    }
  ]
}
