{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03053-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03053-SNAPSHOT.jar",
          "url": "embedded-mas-0.03053-SNAPSHOT.jar",
          "size": 60526,
          "sha512": "9d0d46deca45ed4e79f184c22043842ebc345a9a7b73faf0fa5a8de21cf67127a2b647753c782502b2d0c3e1577aa6c4690cd3ec7f62de0564897c6ff86373ba",
          "sha256": "f7d389ac6f70c1231a31d7ee88e175f107c9bbf51793a0fefaafadf42a70b6f0",
          "sha1": "0a3b754df3545ab77b68ed1b105ff235fd4f58f6",
          "md5": "4cfce761b83232ff2f3bfac91ef76b39"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03053-SNAPSHOT.jar",
          "url": "embedded-mas-0.03053-SNAPSHOT.jar",
          "size": 60526,
          "sha512": "9d0d46deca45ed4e79f184c22043842ebc345a9a7b73faf0fa5a8de21cf67127a2b647753c782502b2d0c3e1577aa6c4690cd3ec7f62de0564897c6ff86373ba",
          "sha256": "f7d389ac6f70c1231a31d7ee88e175f107c9bbf51793a0fefaafadf42a70b6f0",
          "sha1": "0a3b754df3545ab77b68ed1b105ff235fd4f58f6",
          "md5": "4cfce761b83232ff2f3bfac91ef76b39"
        }
      ]
    }
  ]
}
