{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04657-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04657-DEV.jar",
          "url": "embedded-mas-0.04657-DEV.jar",
          "size": 70624,
          "sha512": "ee7cb0dbf9e4d384aa2f20f6986e610526566c39167e78689b0bd17308eea1bd01f4b871cc65c51891e400f9d2ff5cda5cc66739cb3d7be25a2d03580648008e",
          "sha256": "4aceb7c4c3e0b7e6a5746f396124912296a62b416b38fc58335a3c4751a3916a",
          "sha1": "336dbe2b465f9e33d6ea0fd891eca0c9bda56afd",
          "md5": "81ab217615032f9ece6cf907c2beab2e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04657-DEV.jar",
          "url": "embedded-mas-0.04657-DEV.jar",
          "size": 70624,
          "sha512": "ee7cb0dbf9e4d384aa2f20f6986e610526566c39167e78689b0bd17308eea1bd01f4b871cc65c51891e400f9d2ff5cda5cc66739cb3d7be25a2d03580648008e",
          "sha256": "4aceb7c4c3e0b7e6a5746f396124912296a62b416b38fc58335a3c4751a3916a",
          "sha1": "336dbe2b465f9e33d6ea0fd891eca0c9bda56afd",
          "md5": "81ab217615032f9ece6cf907c2beab2e"
        }
      ]
    }
  ]
}
