{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04663-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04663-DEV.jar",
          "url": "embedded-mas-0.04663-DEV.jar",
          "size": 70571,
          "sha512": "a753efb855f28b56b479ba0b7e9e07f5a08785e6f35643904bd5bb33d9448dd39e7eda9967f375b9cbc3cd4fe9835dd644aed6fd57d77559d39c53025e8d5a90",
          "sha256": "184009e46f8cd28506d2e4c28c91370624a782e6925dfe6e47c1fdeb3ef1232d",
          "sha1": "64be480e2cdecbfa0081d9272ef351ce86804fbf",
          "md5": "d4fc86a15f27cde1b2aabc1bb098acc7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04663-DEV.jar",
          "url": "embedded-mas-0.04663-DEV.jar",
          "size": 70571,
          "sha512": "a753efb855f28b56b479ba0b7e9e07f5a08785e6f35643904bd5bb33d9448dd39e7eda9967f375b9cbc3cd4fe9835dd644aed6fd57d77559d39c53025e8d5a90",
          "sha256": "184009e46f8cd28506d2e4c28c91370624a782e6925dfe6e47c1fdeb3ef1232d",
          "sha1": "64be480e2cdecbfa0081d9272ef351ce86804fbf",
          "md5": "d4fc86a15f27cde1b2aabc1bb098acc7"
        }
      ]
    }
  ]
}
