{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.028-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.028-SNAPSHOT.jar",
          "url": "embedded-mas-0.028-SNAPSHOT.jar",
          "size": 30548,
          "sha512": "dc6e6469c0eca49e6b38e8d6b910ac30361c2370baf68f346c2c1ba86ac893cf5d6d505da8b0d5cb9b4b7c4cdd71dcb86d5e67fd8d197835c19e6eb2f00c3363",
          "sha256": "943be4f5ee72ef399a0113a32648902adf3c8227233e386ce9cbed995ed68237",
          "sha1": "718e3e3e51e10fa166b28972b3f29117eb73781a",
          "md5": "0dfed17523bc708c65e67d2e3072f0e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.028-SNAPSHOT.jar",
          "url": "embedded-mas-0.028-SNAPSHOT.jar",
          "size": 30548,
          "sha512": "dc6e6469c0eca49e6b38e8d6b910ac30361c2370baf68f346c2c1ba86ac893cf5d6d505da8b0d5cb9b4b7c4cdd71dcb86d5e67fd8d197835c19e6eb2f00c3363",
          "sha256": "943be4f5ee72ef399a0113a32648902adf3c8227233e386ce9cbed995ed68237",
          "sha1": "718e3e3e51e10fa166b28972b3f29117eb73781a",
          "md5": "0dfed17523bc708c65e67d2e3072f0e6"
        }
      ]
    }
  ]
}
