{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271523-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271523-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271523-SNAPSHOT.jar",
          "size": 30966,
          "sha512": "70880fc2313f1013d73b1e7b4caa4ee12c3d7fda5a671f7fc7f72e421be4d6aa5cfc39d297281650853de1695f6e5760ba0b5e7107b7f326b19948788514f697",
          "sha256": "46c710a91fb28d7ecb0bfe8d9350918ab996d41146bfcdaf1eda10254d9e5dbc",
          "sha1": "1346e50fab65f59ea90e43597e5d2029cef4f428",
          "md5": "e1faca0c68100d007220e66356aea67c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271523-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271523-SNAPSHOT.jar",
          "size": 30966,
          "sha512": "70880fc2313f1013d73b1e7b4caa4ee12c3d7fda5a671f7fc7f72e421be4d6aa5cfc39d297281650853de1695f6e5760ba0b5e7107b7f326b19948788514f697",
          "sha256": "46c710a91fb28d7ecb0bfe8d9350918ab996d41146bfcdaf1eda10254d9e5dbc",
          "sha1": "1346e50fab65f59ea90e43597e5d2029cef4f428",
          "md5": "e1faca0c68100d007220e66356aea67c"
        }
      ]
    }
  ]
}
