{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03042-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03042-SNAPSHOT.jar",
          "url": "embedded-mas-0.03042-SNAPSHOT.jar",
          "size": 61771,
          "sha512": "14665550fb6905e430a2fd66ac34290ea0f3017871e3c3b4823fb456849e6b70b78e811c991058227c41ac2b4e4e366b08d34937e85f1929d39bdbee6fbab690",
          "sha256": "5715fda007ee6dbfec05a083c75f5e84ef922a937b3c13fc44907be41c1e2199",
          "sha1": "cbc531245683b78be4d6bf1207accf4145270fc3",
          "md5": "db5b56f8730da05cb86af0bdd28652eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03042-SNAPSHOT.jar",
          "url": "embedded-mas-0.03042-SNAPSHOT.jar",
          "size": 61771,
          "sha512": "14665550fb6905e430a2fd66ac34290ea0f3017871e3c3b4823fb456849e6b70b78e811c991058227c41ac2b4e4e366b08d34937e85f1929d39bdbee6fbab690",
          "sha256": "5715fda007ee6dbfec05a083c75f5e84ef922a937b3c13fc44907be41c1e2199",
          "sha1": "cbc531245683b78be4d6bf1207accf4145270fc3",
          "md5": "db5b56f8730da05cb86af0bdd28652eb"
        }
      ]
    }
  ]
}
