{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04630-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04630-DEV.jar",
          "url": "embedded-mas-0.04630-DEV.jar",
          "size": 76992,
          "sha512": "3ee53ea015558f28e4aa0eee8cc4d15073e5050d15c77667dbf8758b036245d9a79d4fa9d51bee9e35d152131521a8fdfdec90c0f834d3ee4dbf554a94633ee2",
          "sha256": "4287be270f76e55cfb1a8863643df84187dafc778e9acb4875533aca833d7ccb",
          "sha1": "d666a2bc6130fe680bb4c856bd1b4af54a14c816",
          "md5": "973f8fa4e9ec68ba2096f357f856496e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04630-DEV.jar",
          "url": "embedded-mas-0.04630-DEV.jar",
          "size": 76992,
          "sha512": "3ee53ea015558f28e4aa0eee8cc4d15073e5050d15c77667dbf8758b036245d9a79d4fa9d51bee9e35d152131521a8fdfdec90c0f834d3ee4dbf554a94633ee2",
          "sha256": "4287be270f76e55cfb1a8863643df84187dafc778e9acb4875533aca833d7ccb",
          "sha1": "d666a2bc6130fe680bb4c856bd1b4af54a14c816",
          "md5": "973f8fa4e9ec68ba2096f357f856496e"
        }
      ]
    }
  ]
}
