{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04630-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04630-DEV.jar",
          "url": "embedded-mas-0.04630-DEV.jar",
          "size": 77114,
          "sha512": "831d9b2da85702e52d9322ca98f38303f317687370dbe33daa2303ed5f03e39c041cebd551a835af3c9b7ea793767d67a766a3601837f2e14ca77c14558e2a23",
          "sha256": "5e0d590da65d5f9160e4df5e25ab430f9b088d690d1e490eb4d546bacb2bf4d7",
          "sha1": "8f03681ea1777c3428f31187d5237fdd213fa66b",
          "md5": "c6c66107896fa8912a6136816fdb71ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04630-DEV.jar",
          "url": "embedded-mas-0.04630-DEV.jar",
          "size": 77114,
          "sha512": "831d9b2da85702e52d9322ca98f38303f317687370dbe33daa2303ed5f03e39c041cebd551a835af3c9b7ea793767d67a766a3601837f2e14ca77c14558e2a23",
          "sha256": "5e0d590da65d5f9160e4df5e25ab430f9b088d690d1e490eb4d546bacb2bf4d7",
          "sha1": "8f03681ea1777c3428f31187d5237fdd213fa66b",
          "md5": "c6c66107896fa8912a6136816fdb71ee"
        }
      ]
    }
  ]
}
