{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03046-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03046-SNAPSHOT.jar",
          "url": "embedded-mas-0.03046-SNAPSHOT.jar",
          "size": 60228,
          "sha512": "ed31acb4ebea8605cf7fcb7127f5a8929b40dea50fa770eea09e94d5abf74fe689aae0341868fd82832aa688ea8741078105bcf78ec6d38ad8d1cbc021f199f8",
          "sha256": "7a12d930da0fc31a24c972f134f383e0f79d0a0094e53339e57641c0f0c56b39",
          "sha1": "76f777e117ae869973a660cc6ae2eaed4a6f5970",
          "md5": "84a3603b20b67219261240dff52942f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03046-SNAPSHOT.jar",
          "url": "embedded-mas-0.03046-SNAPSHOT.jar",
          "size": 60228,
          "sha512": "ed31acb4ebea8605cf7fcb7127f5a8929b40dea50fa770eea09e94d5abf74fe689aae0341868fd82832aa688ea8741078105bcf78ec6d38ad8d1cbc021f199f8",
          "sha256": "7a12d930da0fc31a24c972f134f383e0f79d0a0094e53339e57641c0f0c56b39",
          "sha1": "76f777e117ae869973a660cc6ae2eaed4a6f5970",
          "md5": "84a3603b20b67219261240dff52942f1"
        }
      ]
    }
  ]
}
