{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271511-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271511-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271511-SNAPSHOT.jar",
          "size": 30725,
          "sha512": "8043719af4504b7852b51f06cd10e39cef840e1af39da2aff0fe21b125ea8c547ded94908034a4f83536c11d2474aad917b00d5ad2b9b62a00d0a41b52ee0336",
          "sha256": "60c55007474c2498980f4a11b647a7d7fa4fb37ad6c5ee0f34bd8470dd65f8b4",
          "sha1": "b7ed5440c6b22b859a8f460c6f6502b4e17936ad",
          "md5": "885d978061ed0a1c55d079be27133e85"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271511-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271511-SNAPSHOT.jar",
          "size": 30725,
          "sha512": "8043719af4504b7852b51f06cd10e39cef840e1af39da2aff0fe21b125ea8c547ded94908034a4f83536c11d2474aad917b00d5ad2b9b62a00d0a41b52ee0336",
          "sha256": "60c55007474c2498980f4a11b647a7d7fa4fb37ad6c5ee0f34bd8470dd65f8b4",
          "sha1": "b7ed5440c6b22b859a8f460c6f6502b4e17936ad",
          "md5": "885d978061ed0a1c55d079be27133e85"
        }
      ]
    }
  ]
}
