{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271513-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271513-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271513-SNAPSHOT.jar",
          "size": 30653,
          "sha512": "3b8cd9604fcc3654dcdee0c5194ac3e4f816bdb299d42415ca84437018583ee964dc944a8af078b2fa98588382f5ee7da3b4d36f444ccc5f4b2421528917dc31",
          "sha256": "a446502b81b32d74a5235eb0293db8adf3d4fc10a98bfebfffe3f111ed6c4e03",
          "sha1": "9d7c06715332432aa10fcfffde52dd4fc082e4e8",
          "md5": "79bbd87aff454f442a798833f8413a92"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271513-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271513-SNAPSHOT.jar",
          "size": 30653,
          "sha512": "3b8cd9604fcc3654dcdee0c5194ac3e4f816bdb299d42415ca84437018583ee964dc944a8af078b2fa98588382f5ee7da3b4d36f444ccc5f4b2421528917dc31",
          "sha256": "a446502b81b32d74a5235eb0293db8adf3d4fc10a98bfebfffe3f111ed6c4e03",
          "sha1": "9d7c06715332432aa10fcfffde52dd4fc082e4e8",
          "md5": "79bbd87aff454f442a798833f8413a92"
        }
      ]
    }
  ]
}
