{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.02715-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02715-SNAPSHOT.jar",
          "url": "embedded-mas-0.02715-SNAPSHOT.jar",
          "size": 30582,
          "sha512": "9ef9087f43ba8292df47bd377f4b27023a858826f240f1c1ebcbe4be567bbce1c990046cd48bc7db0481917d6ac8d0a0ca3a8ec66440cf31a5c7988eba79f5c1",
          "sha256": "a410a41111f8a8db3f84da0ab2eba346c38e1f897cde4bd28e24031ff1923f71",
          "sha1": "c52567020031ebe35a04d036d44cffcaf04ded31",
          "md5": "6203cfc3ad1258a335d376e286f34e89"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02715-SNAPSHOT.jar",
          "url": "embedded-mas-0.02715-SNAPSHOT.jar",
          "size": 30582,
          "sha512": "9ef9087f43ba8292df47bd377f4b27023a858826f240f1c1ebcbe4be567bbce1c990046cd48bc7db0481917d6ac8d0a0ca3a8ec66440cf31a5c7988eba79f5c1",
          "sha256": "a410a41111f8a8db3f84da0ab2eba346c38e1f897cde4bd28e24031ff1923f71",
          "sha1": "c52567020031ebe35a04d036d44cffcaf04ded31",
          "md5": "6203cfc3ad1258a335d376e286f34e89"
        }
      ]
    }
  ]
}
