{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03041-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03041-SNAPSHOT.jar",
          "url": "embedded-mas-0.03041-SNAPSHOT.jar",
          "size": 61783,
          "sha512": "6e42617629076d50990c89afa0ba73e293616470c83a4d48d97488d2b4b484b8b2a53dcac086299291516af25054831fde40d1afaa7477e9e3832bf865ced959",
          "sha256": "78da1ea5ea76d4e8fa4dc925445bf198431c129852c1506ea6f1f91db7a16680",
          "sha1": "cef95c45df7d9736479871caac3e82d603318f41",
          "md5": "28861d131345e9ce38300e0df49d89bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03041-SNAPSHOT.jar",
          "url": "embedded-mas-0.03041-SNAPSHOT.jar",
          "size": 61783,
          "sha512": "6e42617629076d50990c89afa0ba73e293616470c83a4d48d97488d2b4b484b8b2a53dcac086299291516af25054831fde40d1afaa7477e9e3832bf865ced959",
          "sha256": "78da1ea5ea76d4e8fa4dc925445bf198431c129852c1506ea6f1f91db7a16680",
          "sha1": "cef95c45df7d9736479871caac3e82d603318f41",
          "md5": "28861d131345e9ce38300e0df49d89bd"
        }
      ]
    }
  ]
}
