{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04614-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04614-SNAPSHOT.jar",
          "url": "embedded-mas-0.04614-SNAPSHOT.jar",
          "size": 69292,
          "sha512": "0727a07fb1b2679c45c99a045ba25add1a7390012fce56a57fee7aec142e9862b2f5e81d0125fe977f8070004b40cd40a789e8f355ead039bd46b17d7263c2e3",
          "sha256": "c81ca21460e80616df3fbcbe7227633a0496f4c85d53aea8969fd6a084310ca0",
          "sha1": "e2939dca500e9200906b289b024e7d10d1f2e563",
          "md5": "962a1b31a243a7deb667e59369a74981"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04614-SNAPSHOT.jar",
          "url": "embedded-mas-0.04614-SNAPSHOT.jar",
          "size": 69292,
          "sha512": "0727a07fb1b2679c45c99a045ba25add1a7390012fce56a57fee7aec142e9862b2f5e81d0125fe977f8070004b40cd40a789e8f355ead039bd46b17d7263c2e3",
          "sha256": "c81ca21460e80616df3fbcbe7227633a0496f4c85d53aea8969fd6a084310ca0",
          "sha1": "e2939dca500e9200906b289b024e7d10d1f2e563",
          "md5": "962a1b31a243a7deb667e59369a74981"
        }
      ]
    }
  ]
}
