{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.02806-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02806-SNAPSHOT.jar",
          "url": "embedded-mas-0.02806-SNAPSHOT.jar",
          "size": 31791,
          "sha512": "159aff9fa0a283f13fe52e5c18c45894de3b008fb74deb78ecb4a018f0d0657d3bd808272681685e165f6695b7b64f81ef24232030df3e55b1bf53f1264368e9",
          "sha256": "901e63eae8b672c4cf8e4c64eaedcf248025493238ccc3adca0cdb89aad06fdf",
          "sha1": "4933d27702eecfcd0873031f96c665a30c3d7eaa",
          "md5": "c8b2485fd4a0d2a77c55a5c9e4e36d37"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02806-SNAPSHOT.jar",
          "url": "embedded-mas-0.02806-SNAPSHOT.jar",
          "size": 31791,
          "sha512": "159aff9fa0a283f13fe52e5c18c45894de3b008fb74deb78ecb4a018f0d0657d3bd808272681685e165f6695b7b64f81ef24232030df3e55b1bf53f1264368e9",
          "sha256": "901e63eae8b672c4cf8e4c64eaedcf248025493238ccc3adca0cdb89aad06fdf",
          "sha1": "4933d27702eecfcd0873031f96c665a30c3d7eaa",
          "md5": "c8b2485fd4a0d2a77c55a5c9e4e36d37"
        }
      ]
    }
  ]
}
