{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03003-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03003-SNAPSHOT.jar",
          "url": "embedded-mas-0.03003-SNAPSHOT.jar",
          "size": 52640,
          "sha512": "481656d51bf017898023b3a93e81153a1327683cb55905796bb729ea82e842bb9d4d6cba77680ca500d7ec29e154dcdf7eec88f94778e0f061397961ad2dea12",
          "sha256": "fa5c9f3c57fa507b5859b804d7c162a679ac3ea268eab15b468975c88b04d000",
          "sha1": "9a85329cd5ad9b5d340e2b67bcda6da0bc622c45",
          "md5": "e4d855837437b9597599b1ab5612353a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03003-SNAPSHOT.jar",
          "url": "embedded-mas-0.03003-SNAPSHOT.jar",
          "size": 52640,
          "sha512": "481656d51bf017898023b3a93e81153a1327683cb55905796bb729ea82e842bb9d4d6cba77680ca500d7ec29e154dcdf7eec88f94778e0f061397961ad2dea12",
          "sha256": "fa5c9f3c57fa507b5859b804d7c162a679ac3ea268eab15b468975c88b04d000",
          "sha1": "9a85329cd5ad9b5d340e2b67bcda6da0bc622c45",
          "md5": "e4d855837437b9597599b1ab5612353a"
        }
      ]
    }
  ]
}
