{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03044-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03044-SNAPSHOT.jar",
          "url": "embedded-mas-0.03044-SNAPSHOT.jar",
          "size": 60396,
          "sha512": "e7fdd252a722f9b708e2bd620a4c4110324ad3627abf3686956daa3907596331b188aa9f812aefc6014de5d0d1ab49a08f97f2f4c8a4eb0292dd9c662093bea2",
          "sha256": "e1f4502e9fe168e2ecbec0b68d695f8c8e9c82cc599fe49a05359f829e1e1aff",
          "sha1": "f803df0a43e655c2e1da7b100b983bdd9382528d",
          "md5": "4f36e9f56d3d603229afb69d44d02f11"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03044-SNAPSHOT.jar",
          "url": "embedded-mas-0.03044-SNAPSHOT.jar",
          "size": 60396,
          "sha512": "e7fdd252a722f9b708e2bd620a4c4110324ad3627abf3686956daa3907596331b188aa9f812aefc6014de5d0d1ab49a08f97f2f4c8a4eb0292dd9c662093bea2",
          "sha256": "e1f4502e9fe168e2ecbec0b68d695f8c8e9c82cc599fe49a05359f829e1e1aff",
          "sha1": "f803df0a43e655c2e1da7b100b983bdd9382528d",
          "md5": "4f36e9f56d3d603229afb69d44d02f11"
        }
      ]
    }
  ]
}
