{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03601-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03601-SNAPSHOT.jar",
          "url": "embedded-mas-0.03601-SNAPSHOT.jar",
          "size": 64141,
          "sha512": "8c65703c894b21151f01d59ec9edda3e68beedd08b3d793a2acc69f7b2cf7e45edda0f6f815a068c50b203bd87e1b0ce7b56aefb2c13d466edc958287fd6a4c8",
          "sha256": "fe6a64608c3129520173546c408ec47f8890cfa4cfee7dace0677c91d23c648f",
          "sha1": "40b66f7cab8d919462f507077fb942f8329c4bb7",
          "md5": "3c4752ba8ae638a45a89c4821ab03a6e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03601-SNAPSHOT.jar",
          "url": "embedded-mas-0.03601-SNAPSHOT.jar",
          "size": 64141,
          "sha512": "8c65703c894b21151f01d59ec9edda3e68beedd08b3d793a2acc69f7b2cf7e45edda0f6f815a068c50b203bd87e1b0ce7b56aefb2c13d466edc958287fd6a4c8",
          "sha256": "fe6a64608c3129520173546c408ec47f8890cfa4cfee7dace0677c91d23c648f",
          "sha1": "40b66f7cab8d919462f507077fb942f8329c4bb7",
          "md5": "3c4752ba8ae638a45a89c4821ab03a6e"
        }
      ]
    }
  ]
}
