{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.027060705-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.027060705-SNAPSHOT.jar",
          "url": "embedded-mas-0.027060705-SNAPSHOT.jar",
          "size": 29966,
          "sha512": "61f207dda0714590c56048712f479fd07484190832016b736e136cb3ee563a91362630ba30936cd2a4f769716394db897a3c412615b9932479141b0f15d83baf",
          "sha256": "c3f03fc4ba975de2f4d898dceaca9999afc2f1a6ad64c6419d587e008518243e",
          "sha1": "c90c45f79e8452084433f0f4b48b781507410c24",
          "md5": "f6119252a3ecfce31789ed2eeceb9717"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.027060705-SNAPSHOT.jar",
          "url": "embedded-mas-0.027060705-SNAPSHOT.jar",
          "size": 29966,
          "sha512": "61f207dda0714590c56048712f479fd07484190832016b736e136cb3ee563a91362630ba30936cd2a4f769716394db897a3c412615b9932479141b0f15d83baf",
          "sha256": "c3f03fc4ba975de2f4d898dceaca9999afc2f1a6ad64c6419d587e008518243e",
          "sha1": "c90c45f79e8452084433f0f4b48b781507410c24",
          "md5": "f6119252a3ecfce31789ed2eeceb9717"
        }
      ]
    }
  ]
}
