{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04635-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04635-DEV.jar",
          "url": "embedded-mas-0.04635-DEV.jar",
          "size": 77330,
          "sha512": "f52aeb08522dcd4f83db623f69132553fbb7ac09d0ed6eb0d42d409004bd194ae031966bacc512403ab0f8d777649ec97de3ab8b40d6fa3137474a4b5e83c0df",
          "sha256": "65f35037969d431d24ab8154d03bcded71639f6f9c893369ed0c1d013cc168fc",
          "sha1": "eabf3ff2a7002010085f24d4ab150de1b88fcebf",
          "md5": "3150fcfa00ff529ecfe55c19e0bd5b26"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04635-DEV.jar",
          "url": "embedded-mas-0.04635-DEV.jar",
          "size": 77330,
          "sha512": "f52aeb08522dcd4f83db623f69132553fbb7ac09d0ed6eb0d42d409004bd194ae031966bacc512403ab0f8d777649ec97de3ab8b40d6fa3137474a4b5e83c0df",
          "sha256": "65f35037969d431d24ab8154d03bcded71639f6f9c893369ed0c1d013cc168fc",
          "sha1": "eabf3ff2a7002010085f24d4ab150de1b88fcebf",
          "md5": "3150fcfa00ff529ecfe55c19e0bd5b26"
        }
      ]
    }
  ]
}
