{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03503-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03503-SNAPSHOT.jar",
          "url": "embedded-mas-0.03503-SNAPSHOT.jar",
          "size": 64076,
          "sha512": "2f7cd060af5cff660260939a5311a7c196b0989fff9d2335b1d6dc3ea5b2f6e6d510e906e49df9a664df49e9df5ead120faea9ab286a9cf4c46b3e749e9123c5",
          "sha256": "04505d194dc8d110eaf893bc1f42bc49578a2f0376251195eb82693503c385bc",
          "sha1": "c839759faf90c839b54f2987b73aecd255cf4400",
          "md5": "307788bdf794d87805835ba80d0e8883"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03503-SNAPSHOT.jar",
          "url": "embedded-mas-0.03503-SNAPSHOT.jar",
          "size": 64076,
          "sha512": "2f7cd060af5cff660260939a5311a7c196b0989fff9d2335b1d6dc3ea5b2f6e6d510e906e49df9a664df49e9df5ead120faea9ab286a9cf4c46b3e749e9123c5",
          "sha256": "04505d194dc8d110eaf893bc1f42bc49578a2f0376251195eb82693503c385bc",
          "sha1": "c839759faf90c839b54f2987b73aecd255cf4400",
          "md5": "307788bdf794d87805835ba80d0e8883"
        }
      ]
    }
  ]
}
