{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.038011-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038011-SNAPSHOT.jar",
          "url": "embedded-mas-0.038011-SNAPSHOT.jar",
          "size": 74577,
          "sha512": "2743991bf2268470c1718f67e5e301153c6d279c655cddd1d6acf08e35ab053d3e119efd5db5c96e7498d9fda9adbc41d89ea5efb6266d09438b2151f6270dd5",
          "sha256": "94de1a7ffc61c33553bd6cfd9548684204d105f352882c08ec4490c0117367f5",
          "sha1": "c05f62fa0e93463ee3e6e64f0a44a5ddaa2a3319",
          "md5": "1b7965e1cd525b1c44ba429a3d3a882d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038011-SNAPSHOT.jar",
          "url": "embedded-mas-0.038011-SNAPSHOT.jar",
          "size": 74577,
          "sha512": "2743991bf2268470c1718f67e5e301153c6d279c655cddd1d6acf08e35ab053d3e119efd5db5c96e7498d9fda9adbc41d89ea5efb6266d09438b2151f6270dd5",
          "sha256": "94de1a7ffc61c33553bd6cfd9548684204d105f352882c08ec4490c0117367f5",
          "sha1": "c05f62fa0e93463ee3e6e64f0a44a5ddaa2a3319",
          "md5": "1b7965e1cd525b1c44ba429a3d3a882d"
        }
      ]
    }
  ]
}
