{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03014-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03014-SNAPSHOT.jar",
          "url": "embedded-mas-0.03014-SNAPSHOT.jar",
          "size": 53978,
          "sha512": "0d4d00264139e901138fcedb74c47a09a2a947d10a96a263d5d47b06610333c1c696adc0b45ea5cda1da1c9d8604057981769d2591b83d40d0c93ee044363aef",
          "sha256": "10045d98cd8181c8fe7b88045b21b573b6834835160c642263962d256f6130d3",
          "sha1": "5381759f9b632c7557ebcdbf693c96a9bbf408c0",
          "md5": "ce89180846ee586f994540e81a842a3b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03014-SNAPSHOT.jar",
          "url": "embedded-mas-0.03014-SNAPSHOT.jar",
          "size": 53978,
          "sha512": "0d4d00264139e901138fcedb74c47a09a2a947d10a96a263d5d47b06610333c1c696adc0b45ea5cda1da1c9d8604057981769d2591b83d40d0c93ee044363aef",
          "sha256": "10045d98cd8181c8fe7b88045b21b573b6834835160c642263962d256f6130d3",
          "sha1": "5381759f9b632c7557ebcdbf693c96a9bbf408c0",
          "md5": "ce89180846ee586f994540e81a842a3b"
        }
      ]
    }
  ]
}
