{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03012-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03012-SNAPSHOT.jar",
          "url": "embedded-mas-0.03012-SNAPSHOT.jar",
          "size": 53630,
          "sha512": "45b2d17c804c18f6fa6647f9bb87f542391866339e91d87e0b80383b8213b007ce856e54976e11c8f46d56d621da5f43526fb7fb7e5befd1847ef1c64fb144c8",
          "sha256": "e31b666969e007f97fdabb3fb1dc667d8d5f54b64912426519f5302f2cc9ab02",
          "sha1": "4b02c7877d37693f81eca807c4ac1ff37bf08559",
          "md5": "12c55e0705693ce9fbc91c944c25e5ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03012-SNAPSHOT.jar",
          "url": "embedded-mas-0.03012-SNAPSHOT.jar",
          "size": 53630,
          "sha512": "45b2d17c804c18f6fa6647f9bb87f542391866339e91d87e0b80383b8213b007ce856e54976e11c8f46d56d621da5f43526fb7fb7e5befd1847ef1c64fb144c8",
          "sha256": "e31b666969e007f97fdabb3fb1dc667d8d5f54b64912426519f5302f2cc9ab02",
          "sha1": "4b02c7877d37693f81eca807c4ac1ff37bf08559",
          "md5": "12c55e0705693ce9fbc91c944c25e5ce"
        }
      ]
    }
  ]
}
