{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03701-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03701-SNAPSHOT.jar",
          "url": "embedded-mas-0.03701-SNAPSHOT.jar",
          "size": 68500,
          "sha512": "4367a50b005040eeec9c5f86181408ff96784332b8d085e456655bb3fea17e137635c77ba70425648cb0c5a5e7728ce0e59f1182f073f6453a1862e28085d949",
          "sha256": "ee9ff52deedcc79d40d42a1ceb880816670061bbaa9d2885af2485f7448e2ec4",
          "sha1": "277603d662cc40a6a2c08853d56e0613a19dc67f",
          "md5": "834ef0adf8cba6dab03b9b92d54f7ea3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03701-SNAPSHOT.jar",
          "url": "embedded-mas-0.03701-SNAPSHOT.jar",
          "size": 68500,
          "sha512": "4367a50b005040eeec9c5f86181408ff96784332b8d085e456655bb3fea17e137635c77ba70425648cb0c5a5e7728ce0e59f1182f073f6453a1862e28085d949",
          "sha256": "ee9ff52deedcc79d40d42a1ceb880816670061bbaa9d2885af2485f7448e2ec4",
          "sha1": "277603d662cc40a6a2c08853d56e0613a19dc67f",
          "md5": "834ef0adf8cba6dab03b9b92d54f7ea3"
        }
      ]
    }
  ]
}
