{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04627-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04627-DEV.jar",
          "url": "embedded-mas-0.04627-DEV.jar",
          "size": 75102,
          "sha512": "c57ae6bcf895a85eec7ad99728d1e997bc737ab6e2977b79c41c00becd29df517ba54ee0b13d6e475b9862633b19e7c479ecfc1e0bdad1a700886672ab19c250",
          "sha256": "c7cf5f790fc11ad5ce4e1aee0b68a151ddcbab9b0217e3332144da73d0f7d711",
          "sha1": "1d4d143167efe00080e5010b9081382d4695ddbc",
          "md5": "b6f53ba9f679704810148170445b18f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04627-DEV.jar",
          "url": "embedded-mas-0.04627-DEV.jar",
          "size": 75102,
          "sha512": "c57ae6bcf895a85eec7ad99728d1e997bc737ab6e2977b79c41c00becd29df517ba54ee0b13d6e475b9862633b19e7c479ecfc1e0bdad1a700886672ab19c250",
          "sha256": "c7cf5f790fc11ad5ce4e1aee0b68a151ddcbab9b0217e3332144da73d0f7d711",
          "sha1": "1d4d143167efe00080e5010b9081382d4695ddbc",
          "md5": "b6f53ba9f679704810148170445b18f0"
        }
      ]
    }
  ]
}
