{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03023-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03023-SNAPSHOT.jar",
          "url": "embedded-mas-0.03023-SNAPSHOT.jar",
          "size": 58505,
          "sha512": "df3ebb9b99acaae8061e72df4690c70e539cc79e630cbb5441d3e627ea7600922c7a967bed6c2aa58af7c1cc74ff3fc33c1a71484ec2a97283761abbe0879860",
          "sha256": "6dd394179680bc484d5e3af491e5850c342664031b404903dc1241b0d4e2e7f7",
          "sha1": "42fa5509e45a4bd4023a31ccd39b26b6d2276afb",
          "md5": "2423eaf39af56bd0bebf25bd75007474"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03023-SNAPSHOT.jar",
          "url": "embedded-mas-0.03023-SNAPSHOT.jar",
          "size": 58505,
          "sha512": "df3ebb9b99acaae8061e72df4690c70e539cc79e630cbb5441d3e627ea7600922c7a967bed6c2aa58af7c1cc74ff3fc33c1a71484ec2a97283761abbe0879860",
          "sha256": "6dd394179680bc484d5e3af491e5850c342664031b404903dc1241b0d4e2e7f7",
          "sha1": "42fa5509e45a4bd4023a31ccd39b26b6d2276afb",
          "md5": "2423eaf39af56bd0bebf25bd75007474"
        }
      ]
    }
  ]
}
