{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.02904-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02904-SNAPSHOT.jar",
          "url": "embedded-mas-0.02904-SNAPSHOT.jar",
          "size": 30750,
          "sha512": "4c39b287011338d7d199ca95732bdd820cc5c7efdc273b1510843bd5b9abd8d504967fbbc2ab530f08f12f6407343c61148b5ce1587163421f42cb3c37809ff2",
          "sha256": "68750c30cb7edd4051af560f6cb50baf5c3bc7600f90bc33337f1a4d0f47dc7c",
          "sha1": "682677cce4a05b417534a589c26e12eeda7db138",
          "md5": "51b72c2602d3466f2b8d63df8a654f7f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02904-SNAPSHOT.jar",
          "url": "embedded-mas-0.02904-SNAPSHOT.jar",
          "size": 30750,
          "sha512": "4c39b287011338d7d199ca95732bdd820cc5c7efdc273b1510843bd5b9abd8d504967fbbc2ab530f08f12f6407343c61148b5ce1587163421f42cb3c37809ff2",
          "sha256": "68750c30cb7edd4051af560f6cb50baf5c3bc7600f90bc33337f1a4d0f47dc7c",
          "sha1": "682677cce4a05b417534a589c26e12eeda7db138",
          "md5": "51b72c2602d3466f2b8d63df8a654f7f"
        }
      ]
    }
  ]
}
