{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.02713-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02713-SNAPSHOT.jar",
          "url": "embedded-mas-0.02713-SNAPSHOT.jar",
          "size": 30252,
          "sha512": "92e0387b460d3dd175edb3f0dfa02be2b7fcefb831345f152e2a85b14d9ed2ddea3dec2952e5d2310c5e94089bbac4d7486d4959a63813693041c08769c370d4",
          "sha256": "551001f9dd84c44df6a363bf15823c145775436c093fc31572ba2034ecf968d8",
          "sha1": "c5f47115cac73ea86fccef4406d3d4bd33614f48",
          "md5": "c907daff2c269d1c308bb961ff53a0c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02713-SNAPSHOT.jar",
          "url": "embedded-mas-0.02713-SNAPSHOT.jar",
          "size": 30252,
          "sha512": "92e0387b460d3dd175edb3f0dfa02be2b7fcefb831345f152e2a85b14d9ed2ddea3dec2952e5d2310c5e94089bbac4d7486d4959a63813693041c08769c370d4",
          "sha256": "551001f9dd84c44df6a363bf15823c145775436c093fc31572ba2034ecf968d8",
          "sha1": "c5f47115cac73ea86fccef4406d3d4bd33614f48",
          "md5": "c907daff2c269d1c308bb961ff53a0c1"
        }
      ]
    }
  ]
}
