{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03025-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03025-SNAPSHOT.jar",
          "url": "embedded-mas-0.03025-SNAPSHOT.jar",
          "size": 58561,
          "sha512": "c2547819dcc23d7bc75614a1b8ad86b3dc9144eb16da3bffab56b721f6713278be16220e842c495d97abe4eeb232bf7b5d3f0cc9ce3ab31e29817fa9d03a1b7f",
          "sha256": "434b303eed9ab47795ba4ecc9ed35cf8f44852f63a958b26a1bc5cb4a2106dd7",
          "sha1": "2f5fef908f658b758ce1d175c84ebb47bf972efc",
          "md5": "a230accd4502b819b2b5f5b4fa941c66"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03025-SNAPSHOT.jar",
          "url": "embedded-mas-0.03025-SNAPSHOT.jar",
          "size": 58561,
          "sha512": "c2547819dcc23d7bc75614a1b8ad86b3dc9144eb16da3bffab56b721f6713278be16220e842c495d97abe4eeb232bf7b5d3f0cc9ce3ab31e29817fa9d03a1b7f",
          "sha256": "434b303eed9ab47795ba4ecc9ed35cf8f44852f63a958b26a1bc5cb4a2106dd7",
          "sha1": "2f5fef908f658b758ce1d175c84ebb47bf972efc",
          "md5": "a230accd4502b819b2b5f5b4fa941c66"
        }
      ]
    }
  ]
}
