{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.02901-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02901-SNAPSHOT.jar",
          "url": "embedded-mas-0.02901-SNAPSHOT.jar",
          "size": 30796,
          "sha512": "5e123ddad24979925bfe3c2adab52bbb10d5d8f7c61825214feeaf41a6c39cbbe7aeae57d12a07910e0c746940b21b882c0b0a31780e27e21c77dbd331b1391d",
          "sha256": "fee14730a9b64f9ec22e17cba401fe6676c6f231bb4753102c0c116d983c685e",
          "sha1": "8479c31cb7332a491d2818382c519ea2265e97d0",
          "md5": "6491b5fdf91770a45541fc9edb5e80a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02901-SNAPSHOT.jar",
          "url": "embedded-mas-0.02901-SNAPSHOT.jar",
          "size": 30796,
          "sha512": "5e123ddad24979925bfe3c2adab52bbb10d5d8f7c61825214feeaf41a6c39cbbe7aeae57d12a07910e0c746940b21b882c0b0a31780e27e21c77dbd331b1391d",
          "sha256": "fee14730a9b64f9ec22e17cba401fe6676c6f231bb4753102c0c116d983c685e",
          "sha1": "8479c31cb7332a491d2818382c519ea2265e97d0",
          "md5": "6491b5fdf91770a45541fc9edb5e80a9"
        }
      ]
    }
  ]
}
