{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.02901-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02901-SNAPSHOT.jar",
          "url": "embedded-mas-0.02901-SNAPSHOT.jar",
          "size": 30664,
          "sha512": "80d4978dc8eb8e35afb2f5cedef4647dad3d124ca02565ed873b4d9bb9cff6bc31796094fe3d68a43939c41acb9cdd02ac3f5b105262a49f51e819558554fcd2",
          "sha256": "1f6625d26c32d83c54fbac2250045d777efb6f3c6a7308e39782c90e5151fee9",
          "sha1": "448f9c1a13017d8214acf6ae18399c0064794b07",
          "md5": "f18986d018c70b0cb5fad7479f130195"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02901-SNAPSHOT.jar",
          "url": "embedded-mas-0.02901-SNAPSHOT.jar",
          "size": 30664,
          "sha512": "80d4978dc8eb8e35afb2f5cedef4647dad3d124ca02565ed873b4d9bb9cff6bc31796094fe3d68a43939c41acb9cdd02ac3f5b105262a49f51e819558554fcd2",
          "sha256": "1f6625d26c32d83c54fbac2250045d777efb6f3c6a7308e39782c90e5151fee9",
          "sha1": "448f9c1a13017d8214acf6ae18399c0064794b07",
          "md5": "f18986d018c70b0cb5fad7479f130195"
        }
      ]
    }
  ]
}
