{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04608-DEVX",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04608-DEVX.jar",
          "url": "embedded-mas-0.04608-DEVX.jar",
          "size": 69579,
          "sha512": "1e0c302d6999b9f33a47d866d493dc29d65a0685f50e615b75b76f527e8b5aa63c861953447155166a9575226c5f236c492061bfcb3eb3b67330364941aa37a2",
          "sha256": "79e8ccdde50e7ff7c7ea9c4a8f103b3876b073cc2a3d642f33ec0616fb35cd11",
          "sha1": "a2c5e28298ba9df4db45fd0bafffec54f82cf76e",
          "md5": "61d7a893a10e9374abb66ce5d5cfccb5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04608-DEVX.jar",
          "url": "embedded-mas-0.04608-DEVX.jar",
          "size": 69579,
          "sha512": "1e0c302d6999b9f33a47d866d493dc29d65a0685f50e615b75b76f527e8b5aa63c861953447155166a9575226c5f236c492061bfcb3eb3b67330364941aa37a2",
          "sha256": "79e8ccdde50e7ff7c7ea9c4a8f103b3876b073cc2a3d642f33ec0616fb35cd11",
          "sha1": "a2c5e28298ba9df4db45fd0bafffec54f82cf76e",
          "md5": "61d7a893a10e9374abb66ce5d5cfccb5"
        }
      ]
    }
  ]
}
