{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04608-DEVX",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04608-DEVX.jar",
          "url": "embedded-mas-0.04608-DEVX.jar",
          "size": 69524,
          "sha512": "fbbd84c24c3532e55a18592474d52424c28da40a023f63b68b6237f148289661160d81b39853e5d2c3c76a3083c4de5d102320232526bbeeef5648f831195635",
          "sha256": "10b79cb03ffbf59af4ba3446224e5bf636088a481c14435fcf8277d2e8d469c1",
          "sha1": "52a22b12f0b4c1abe740781ffbf3ffbf186aa834",
          "md5": "557834fe5da8d1e3cb8892d7db75dc3b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04608-DEVX.jar",
          "url": "embedded-mas-0.04608-DEVX.jar",
          "size": 69524,
          "sha512": "fbbd84c24c3532e55a18592474d52424c28da40a023f63b68b6237f148289661160d81b39853e5d2c3c76a3083c4de5d102320232526bbeeef5648f831195635",
          "sha256": "10b79cb03ffbf59af4ba3446224e5bf636088a481c14435fcf8277d2e8d469c1",
          "sha1": "52a22b12f0b4c1abe740781ffbf3ffbf186aa834",
          "md5": "557834fe5da8d1e3cb8892d7db75dc3b"
        }
      ]
    }
  ]
}
