{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03006-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03006-SNAPSHOT.jar",
          "url": "embedded-mas-0.03006-SNAPSHOT.jar",
          "size": 52731,
          "sha512": "6a88f8c89a09cca5563aed84701c55b0cbb831928c1abbe7449c0dccc30c162579d883fcd42a44388b8e645cedaea2556b95c29aa8ceacb98957df354933926b",
          "sha256": "ab3406a74387a531730add6a2c61231a5139512f4e6c3ed6297c1d7924bc7a56",
          "sha1": "dcb6723d552f036ef2f769e9faa14c0ed91f0134",
          "md5": "d1eb83ff3668815348e16e8afda287a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03006-SNAPSHOT.jar",
          "url": "embedded-mas-0.03006-SNAPSHOT.jar",
          "size": 52731,
          "sha512": "6a88f8c89a09cca5563aed84701c55b0cbb831928c1abbe7449c0dccc30c162579d883fcd42a44388b8e645cedaea2556b95c29aa8ceacb98957df354933926b",
          "sha256": "ab3406a74387a531730add6a2c61231a5139512f4e6c3ed6297c1d7924bc7a56",
          "sha1": "dcb6723d552f036ef2f769e9faa14c0ed91f0134",
          "md5": "d1eb83ff3668815348e16e8afda287a5"
        }
      ]
    }
  ]
}
