{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271204-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271204-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271204-SNAPSHOT.jar",
          "size": 30252,
          "sha512": "6ebcdf4f13cdf78da715e4e9ad5f59b79299c7c806b9ee753f052d5131c511350145786da8963142c66bf505bccdebb27b9ca89b8d5aa5e764fed6e22501d744",
          "sha256": "98676b1e211be4c0e136e0e96d16591c21e0c6fe05639cc1ddab1ef0fa5d2868",
          "sha1": "d193e1484689527055fc31d2a7d700f4040cc4cf",
          "md5": "09bfbba31d15057a87eb314753b2b8c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271204-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271204-SNAPSHOT.jar",
          "size": 30252,
          "sha512": "6ebcdf4f13cdf78da715e4e9ad5f59b79299c7c806b9ee753f052d5131c511350145786da8963142c66bf505bccdebb27b9ca89b8d5aa5e764fed6e22501d744",
          "sha256": "98676b1e211be4c0e136e0e96d16591c21e0c6fe05639cc1ddab1ef0fa5d2868",
          "sha1": "d193e1484689527055fc31d2a7d700f4040cc4cf",
          "md5": "09bfbba31d15057a87eb314753b2b8c1"
        }
      ]
    }
  ]
}
