{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04643-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04643-DEV.jar",
          "url": "embedded-mas-0.04643-DEV.jar",
          "size": 77328,
          "sha512": "4b7a657a0a56d45070902dd856801d5a3307a1967578abf2efb2210ccc772d9df44966d9d3eba16df52c609daf7323b9dc068128aeffe45d4d7583d4462b3e88",
          "sha256": "562dc377e0786b9a0b70b3c0f8cfe3910e47b9f8d3afb1be1f65d63b219e1b68",
          "sha1": "8029743e8461ab6b8f66982bb0ff007237ed4c53",
          "md5": "c47e9030bead1c69f402838006feec07"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04643-DEV.jar",
          "url": "embedded-mas-0.04643-DEV.jar",
          "size": 77328,
          "sha512": "4b7a657a0a56d45070902dd856801d5a3307a1967578abf2efb2210ccc772d9df44966d9d3eba16df52c609daf7323b9dc068128aeffe45d4d7583d4462b3e88",
          "sha256": "562dc377e0786b9a0b70b3c0f8cfe3910e47b9f8d3afb1be1f65d63b219e1b68",
          "sha1": "8029743e8461ab6b8f66982bb0ff007237ed4c53",
          "md5": "c47e9030bead1c69f402838006feec07"
        }
      ]
    }
  ]
}
