{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04643-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04643-DEV.jar",
          "url": "embedded-mas-0.04643-DEV.jar",
          "size": 78001,
          "sha512": "366a07c27e96dfd5ab21f6212cc06a24ddffcc07a0b808b30f4bb183537ce823cdcf8a0adb6919fc33273f8753eb3fc8cefed12fe54a5f36865440a976ea6eb7",
          "sha256": "68831ced9e2209f1cb74b66f2f22a2a82e9bbfb4b93a30ed8b4099f1afc769a9",
          "sha1": "a810d364ffe5ba4203e21263a0a78fda8ef0ffb8",
          "md5": "88e33e8d3c7ffea8e2b81c8bb7d3f8fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04643-DEV.jar",
          "url": "embedded-mas-0.04643-DEV.jar",
          "size": 78001,
          "sha512": "366a07c27e96dfd5ab21f6212cc06a24ddffcc07a0b808b30f4bb183537ce823cdcf8a0adb6919fc33273f8753eb3fc8cefed12fe54a5f36865440a976ea6eb7",
          "sha256": "68831ced9e2209f1cb74b66f2f22a2a82e9bbfb4b93a30ed8b4099f1afc769a9",
          "sha1": "a810d364ffe5ba4203e21263a0a78fda8ef0ffb8",
          "md5": "88e33e8d3c7ffea8e2b81c8bb7d3f8fd"
        }
      ]
    }
  ]
}
