{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.02807-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02807-SNAPSHOT.jar",
          "url": "embedded-mas-0.02807-SNAPSHOT.jar",
          "size": 31820,
          "sha512": "6e461a0de0ae7d288aae8e45896fcaec1fa4c96078431287d1b7a3ad0e63bb06cb5a21b155289cb55d436a32e08b1cbdd5cac292c164523cb51334a9b43ba5e4",
          "sha256": "9d641be0dfcb88a20eba02ade4933cd1ef815be8ca2b83ed14146c8ac71d2f8b",
          "sha1": "a258d4c855714d2d55d81b5fbde1a08cf42d3d1f",
          "md5": "663dbb56e2d6992595a8d85b148d1c5a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02807-SNAPSHOT.jar",
          "url": "embedded-mas-0.02807-SNAPSHOT.jar",
          "size": 31820,
          "sha512": "6e461a0de0ae7d288aae8e45896fcaec1fa4c96078431287d1b7a3ad0e63bb06cb5a21b155289cb55d436a32e08b1cbdd5cac292c164523cb51334a9b43ba5e4",
          "sha256": "9d641be0dfcb88a20eba02ade4933cd1ef815be8ca2b83ed14146c8ac71d2f8b",
          "sha1": "a258d4c855714d2d55d81b5fbde1a08cf42d3d1f",
          "md5": "663dbb56e2d6992595a8d85b148d1c5a"
        }
      ]
    }
  ]
}
