{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04620-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04620-SNAPSHOT.jar",
          "url": "embedded-mas-0.04620-SNAPSHOT.jar",
          "size": 69114,
          "sha512": "85c1956796b92509f7ef5f9bb32c609991e64764d2f6b7decffb2890a72b0fd4c51f89a40ee45e8ac1ba985525477ec75541b0538029ce3edb3f5e5ec2f78b2a",
          "sha256": "69d669b03a95469870d408b9cbfa6352828ac1eea5708da1479a7eee4241cef4",
          "sha1": "7082e3f9f36e4bf2824da5496175e457e45cda60",
          "md5": "42cca486e46142b254b6a96d53ca9237"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04620-SNAPSHOT.jar",
          "url": "embedded-mas-0.04620-SNAPSHOT.jar",
          "size": 69114,
          "sha512": "85c1956796b92509f7ef5f9bb32c609991e64764d2f6b7decffb2890a72b0fd4c51f89a40ee45e8ac1ba985525477ec75541b0538029ce3edb3f5e5ec2f78b2a",
          "sha256": "69d669b03a95469870d408b9cbfa6352828ac1eea5708da1479a7eee4241cef4",
          "sha1": "7082e3f9f36e4bf2824da5496175e457e45cda60",
          "md5": "42cca486e46142b254b6a96d53ca9237"
        }
      ]
    }
  ]
}
