{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271404-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271404-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271404-SNAPSHOT.jar",
          "size": 30581,
          "sha512": "7b33b6cd97cdd7d5e6d160679c5d46984292f2933ccacc4f5b2dff1e6ab52d91680d3e4e89a0cc214ad7e08121b8f569d1752b0c6ba9bd253ff6fa935ac2fa59",
          "sha256": "331c8ccf840fd862ec55db44e5980f23d3b2b26c92e4afbb913159e26a2b28b1",
          "sha1": "74fa9f1964877ec3cbc53134b2bdc2dd9160b18a",
          "md5": "0434afd9dbee97cab881ad9b202b4d4e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271404-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271404-SNAPSHOT.jar",
          "size": 30581,
          "sha512": "7b33b6cd97cdd7d5e6d160679c5d46984292f2933ccacc4f5b2dff1e6ab52d91680d3e4e89a0cc214ad7e08121b8f569d1752b0c6ba9bd253ff6fa935ac2fa59",
          "sha256": "331c8ccf840fd862ec55db44e5980f23d3b2b26c92e4afbb913159e26a2b28b1",
          "sha1": "74fa9f1964877ec3cbc53134b2bdc2dd9160b18a",
          "md5": "0434afd9dbee97cab881ad9b202b4d4e"
        }
      ]
    }
  ]
}
