{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04656-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04656-DEV.jar",
          "url": "embedded-mas-0.04656-DEV.jar",
          "size": 70552,
          "sha512": "eb14ccfd619cdf4f3a68e2a375ebf33a4ec2de637fcb24006878ea0bdac7a2fb31d90738bb79b296cedd71a441a8fe55498ba398ac93374d4e215f4ec705ce6b",
          "sha256": "b916655dfefc3d414116ae5609d6b0697975b2b77817efb239efd829148e2d4d",
          "sha1": "7d432517599f6e63568b6481e8f6e0fd2bfcb884",
          "md5": "606c747a807d19935d55aac96a1cd97f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04656-DEV.jar",
          "url": "embedded-mas-0.04656-DEV.jar",
          "size": 70552,
          "sha512": "eb14ccfd619cdf4f3a68e2a375ebf33a4ec2de637fcb24006878ea0bdac7a2fb31d90738bb79b296cedd71a441a8fe55498ba398ac93374d4e215f4ec705ce6b",
          "sha256": "b916655dfefc3d414116ae5609d6b0697975b2b77817efb239efd829148e2d4d",
          "sha1": "7d432517599f6e63568b6481e8f6e0fd2bfcb884",
          "md5": "606c747a807d19935d55aac96a1cd97f"
        }
      ]
    }
  ]
}
