{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271501-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271501-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271501-SNAPSHOT.jar",
          "size": 30674,
          "sha512": "3548eb4203f2d3aa12887199be791a952e7eb46a06f3d6a05fce1b31bdd1ff4f9055787be422a15b7463b62a1e82623f8a713aadb3e3ae7e5d68e31f5665ca67",
          "sha256": "1cab3727839d0bc822c6f31fc8582f0462aea56b5b70c05ac474502b53263059",
          "sha1": "1d8b08500c604d817fe499c6e7e2b4ebef2eff4c",
          "md5": "f175b5dc092927a0854b76286c9df7f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271501-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271501-SNAPSHOT.jar",
          "size": 30674,
          "sha512": "3548eb4203f2d3aa12887199be791a952e7eb46a06f3d6a05fce1b31bdd1ff4f9055787be422a15b7463b62a1e82623f8a713aadb3e3ae7e5d68e31f5665ca67",
          "sha256": "1cab3727839d0bc822c6f31fc8582f0462aea56b5b70c05ac474502b53263059",
          "sha1": "1d8b08500c604d817fe499c6e7e2b4ebef2eff4c",
          "md5": "f175b5dc092927a0854b76286c9df7f9"
        }
      ]
    }
  ]
}
