{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.038015-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038015-SNAPSHOT.jar",
          "url": "embedded-mas-0.038015-SNAPSHOT.jar",
          "size": 74507,
          "sha512": "e91b47dffe9719579593a3f79d1c03ece76861024bc4deeb0db748cb2c3dd0a83ba13c424f7584969b8efb04640cef5a53ad411babfd52f66fe538899d663a4e",
          "sha256": "6ac25d4605e62bd58fd4776fffb909401c54651774a3dbd12456da47f5467cd4",
          "sha1": "8ae9f88ace446b1c5bcd413beffc789a042736e6",
          "md5": "c08d8ff6be2aae88f1c13aa2fd02ef63"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038015-SNAPSHOT.jar",
          "url": "embedded-mas-0.038015-SNAPSHOT.jar",
          "size": 74507,
          "sha512": "e91b47dffe9719579593a3f79d1c03ece76861024bc4deeb0db748cb2c3dd0a83ba13c424f7584969b8efb04640cef5a53ad411babfd52f66fe538899d663a4e",
          "sha256": "6ac25d4605e62bd58fd4776fffb909401c54651774a3dbd12456da47f5467cd4",
          "sha1": "8ae9f88ace446b1c5bcd413beffc789a042736e6",
          "md5": "c08d8ff6be2aae88f1c13aa2fd02ef63"
        }
      ]
    }
  ]
}
