{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04601-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04601-SNAPSHOT.jar",
          "url": "embedded-mas-0.04601-SNAPSHOT.jar",
          "size": 73256,
          "sha512": "0c0cb371700c4089218067caec8780785c153a985dc596ce95579d124958dd5ed15eba950a5311ed1a546a07c681590a0187b737929fc02721a558126e63e2a3",
          "sha256": "ea633cfcb9e45b8d0dcdcced40cf90a73d52ab4f0caa6cc4424b9149819eeb1b",
          "sha1": "0beeedac70114f4b39b81908daf083e3dd82061a",
          "md5": "c976b2e90c17e318b2236c9a4101647e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04601-SNAPSHOT.jar",
          "url": "embedded-mas-0.04601-SNAPSHOT.jar",
          "size": 73256,
          "sha512": "0c0cb371700c4089218067caec8780785c153a985dc596ce95579d124958dd5ed15eba950a5311ed1a546a07c681590a0187b737929fc02721a558126e63e2a3",
          "sha256": "ea633cfcb9e45b8d0dcdcced40cf90a73d52ab4f0caa6cc4424b9149819eeb1b",
          "sha1": "0beeedac70114f4b39b81908daf083e3dd82061a",
          "md5": "c976b2e90c17e318b2236c9a4101647e"
        }
      ]
    }
  ]
}
