{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04625-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04625-SNAPSHOT.jar",
          "url": "embedded-mas-0.04625-SNAPSHOT.jar",
          "size": 74054,
          "sha512": "c0e2806fccd01ecfab987ab864b3cb6d91ce3e957169b444e962b7732ab957f3a0a5ccc6d8fc9322fd80e080f6e4015768abc42ca48d3c7431e94b1a231eca21",
          "sha256": "0574b4241db47f5eb87a9ae03e271f4734069dad9a9f27fe99afd15859dba06c",
          "sha1": "91c136608622d36e88f70b1c886b9e67c831415c",
          "md5": "fae928443e300539184178bea862bff9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04625-SNAPSHOT.jar",
          "url": "embedded-mas-0.04625-SNAPSHOT.jar",
          "size": 74054,
          "sha512": "c0e2806fccd01ecfab987ab864b3cb6d91ce3e957169b444e962b7732ab957f3a0a5ccc6d8fc9322fd80e080f6e4015768abc42ca48d3c7431e94b1a231eca21",
          "sha256": "0574b4241db47f5eb87a9ae03e271f4734069dad9a9f27fe99afd15859dba06c",
          "sha1": "91c136608622d36e88f70b1c886b9e67c831415c",
          "md5": "fae928443e300539184178bea862bff9"
        }
      ]
    }
  ]
}
