{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03049-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03049-SNAPSHOT.jar",
          "url": "embedded-mas-0.03049-SNAPSHOT.jar",
          "size": 60464,
          "sha512": "8f77148924d58630ea7ece1eb932da6938119e276b96c1d8ed8b84a85b2bbc8342cafe9cedf6e46f35eed6269876a466d379ad21ce8a329037acb5fba39327b7",
          "sha256": "ae8ee3b26636135f3f35210ece828f71334ecdb4f2e7b959eace357e6f155e21",
          "sha1": "3b95ee65fa10255e3ef0b31db3c7cbdae11a63d9",
          "md5": "517276cbaa1c63fc304790cfc3c1a54a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03049-SNAPSHOT.jar",
          "url": "embedded-mas-0.03049-SNAPSHOT.jar",
          "size": 60464,
          "sha512": "8f77148924d58630ea7ece1eb932da6938119e276b96c1d8ed8b84a85b2bbc8342cafe9cedf6e46f35eed6269876a466d379ad21ce8a329037acb5fba39327b7",
          "sha256": "ae8ee3b26636135f3f35210ece828f71334ecdb4f2e7b959eace357e6f155e21",
          "sha1": "3b95ee65fa10255e3ef0b31db3c7cbdae11a63d9",
          "md5": "517276cbaa1c63fc304790cfc3c1a54a"
        }
      ]
    }
  ]
}
