{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.033-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.033-SNAPSHOT.jar",
          "url": "embedded-mas-0.033-SNAPSHOT.jar",
          "size": 62205,
          "sha512": "59e815a0446ec93f6a35bd5ebfa684833514470a8bb033def81c8c5ed653e7cbb9d335ff29b6ac1b8aa9139594ddcece098dc7ee6ed4b3c4df70864de7d9b91c",
          "sha256": "a9b59a816dafb96ee69d969b6621aac7674a1b1398591656ed6d1b07c95b8feb",
          "sha1": "279f98845291c49d6263be56ced068f580d7469f",
          "md5": "081ec80d2d42a58d5de7a5c727305ab3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.033-SNAPSHOT.jar",
          "url": "embedded-mas-0.033-SNAPSHOT.jar",
          "size": 62205,
          "sha512": "59e815a0446ec93f6a35bd5ebfa684833514470a8bb033def81c8c5ed653e7cbb9d335ff29b6ac1b8aa9139594ddcece098dc7ee6ed4b3c4df70864de7d9b91c",
          "sha256": "a9b59a816dafb96ee69d969b6621aac7674a1b1398591656ed6d1b07c95b8feb",
          "sha1": "279f98845291c49d6263be56ced068f580d7469f",
          "md5": "081ec80d2d42a58d5de7a5c727305ab3"
        }
      ]
    }
  ]
}
