{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04670-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04670-DEV.jar",
          "url": "embedded-mas-0.04670-DEV.jar",
          "size": 70843,
          "sha512": "60b4f98ebb9245dc97bcf6289622385b20c671a6b81d750b83e995af81d0c612a714ac43d9180150d6b9a455043dbef795720c217440c1c8fc3962ee94b3a8b2",
          "sha256": "e32dcc0188e0076e88920c36cf0674ae83eba9748d16f1f9b80933ccfe0ece0f",
          "sha1": "17f550b67df6e7e4d733bdc182965e414dfdb4da",
          "md5": "fcfee93de17eed44d7fedad1b55aabe8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04670-DEV.jar",
          "url": "embedded-mas-0.04670-DEV.jar",
          "size": 70843,
          "sha512": "60b4f98ebb9245dc97bcf6289622385b20c671a6b81d750b83e995af81d0c612a714ac43d9180150d6b9a455043dbef795720c217440c1c8fc3962ee94b3a8b2",
          "sha256": "e32dcc0188e0076e88920c36cf0674ae83eba9748d16f1f9b80933ccfe0ece0f",
          "sha1": "17f550b67df6e7e4d733bdc182965e414dfdb4da",
          "md5": "fcfee93de17eed44d7fedad1b55aabe8"
        }
      ]
    }
  ]
}
