{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03056-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03056-SNAPSHOT.jar",
          "url": "embedded-mas-0.03056-SNAPSHOT.jar",
          "size": 60687,
          "sha512": "3b4539b03df7e6a0a6666d8149a27f3ac8d174ded82ed479fcef4702c8cb37046a2cf2927b681df9263963da77911e1c7f1846e8963f778633dcc716b0efd215",
          "sha256": "f42c7451fc0390df9dc6adb1187b31838ec64285b9159242a8266a315018beed",
          "sha1": "d713b639d6fb633a8bfdd10a66123767b94d6f52",
          "md5": "5d4643f87cb307783314c4b9f060bdd7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03056-SNAPSHOT.jar",
          "url": "embedded-mas-0.03056-SNAPSHOT.jar",
          "size": 60687,
          "sha512": "3b4539b03df7e6a0a6666d8149a27f3ac8d174ded82ed479fcef4702c8cb37046a2cf2927b681df9263963da77911e1c7f1846e8963f778633dcc716b0efd215",
          "sha256": "f42c7451fc0390df9dc6adb1187b31838ec64285b9159242a8266a315018beed",
          "sha1": "d713b639d6fb633a8bfdd10a66123767b94d6f52",
          "md5": "5d4643f87cb307783314c4b9f060bdd7"
        }
      ]
    }
  ]
}
