{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.02808-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02808-SNAPSHOT.jar",
          "url": "embedded-mas-0.02808-SNAPSHOT.jar",
          "size": 30551,
          "sha512": "59360519351e19b61130c869f5788ea78fddf933ae4816cd2d476dc90e4becfcb12294e11be71b9376e5018e9952bf8e6b0086414e4c49c2129de043250cd4f0",
          "sha256": "022241b27f4e540bbdcd3634c8399a3cdcf7816d6a3521d53968708c1167525e",
          "sha1": "945274e5385a375c58f1381b641070dfc2ab2b6b",
          "md5": "a26e35cc9c9734ac98eff5344bf088c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02808-SNAPSHOT.jar",
          "url": "embedded-mas-0.02808-SNAPSHOT.jar",
          "size": 30551,
          "sha512": "59360519351e19b61130c869f5788ea78fddf933ae4816cd2d476dc90e4becfcb12294e11be71b9376e5018e9952bf8e6b0086414e4c49c2129de043250cd4f0",
          "sha256": "022241b27f4e540bbdcd3634c8399a3cdcf7816d6a3521d53968708c1167525e",
          "sha1": "945274e5385a375c58f1381b641070dfc2ab2b6b",
          "md5": "a26e35cc9c9734ac98eff5344bf088c8"
        }
      ]
    }
  ]
}
