{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.02902-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02902-SNAPSHOT.jar",
          "url": "embedded-mas-0.02902-SNAPSHOT.jar",
          "size": 30014,
          "sha512": "a0d66736fdcf2e527cf36e3020f56e8140498ea5f8766a8bc5cb50d777b8825f0f70f80d549626000ef8117267ff4264f2cf3c3c8e871639198cc7a76c9e01e5",
          "sha256": "4e35e2517279ba3db9f63a833007a637e2bae6f29649964af549dcf1c0da16b4",
          "sha1": "d333a6133e53b2aa61991567a8ff4ca7c77d3ba2",
          "md5": "8762e28b5bbb063ea55e64779333e916"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02902-SNAPSHOT.jar",
          "url": "embedded-mas-0.02902-SNAPSHOT.jar",
          "size": 30014,
          "sha512": "a0d66736fdcf2e527cf36e3020f56e8140498ea5f8766a8bc5cb50d777b8825f0f70f80d549626000ef8117267ff4264f2cf3c3c8e871639198cc7a76c9e01e5",
          "sha256": "4e35e2517279ba3db9f63a833007a637e2bae6f29649964af549dcf1c0da16b4",
          "sha1": "d333a6133e53b2aa61991567a8ff4ca7c77d3ba2",
          "md5": "8762e28b5bbb063ea55e64779333e916"
        }
      ]
    }
  ]
}
