{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.02902-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02902-SNAPSHOT.jar",
          "url": "embedded-mas-0.02902-SNAPSHOT.jar",
          "size": 30687,
          "sha512": "ddcce69291af95b0defe3142aad6bcfe664e70144550f17af928b3a3652a23f06a9def2d9dfa583b8dadecf326795a68bf628d257e88d64db4beaf49ffeeeb0e",
          "sha256": "1c0a7324244db03b53716957d61c570404f34d63719ffebdda2b4c8438ea88b1",
          "sha1": "773ca0c8fe8cd78440f2187902dbd90afcd3f3a2",
          "md5": "a7a36ed0ba1755ebec0e74217c827172"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02902-SNAPSHOT.jar",
          "url": "embedded-mas-0.02902-SNAPSHOT.jar",
          "size": 30687,
          "sha512": "ddcce69291af95b0defe3142aad6bcfe664e70144550f17af928b3a3652a23f06a9def2d9dfa583b8dadecf326795a68bf628d257e88d64db4beaf49ffeeeb0e",
          "sha256": "1c0a7324244db03b53716957d61c570404f34d63719ffebdda2b4c8438ea88b1",
          "sha1": "773ca0c8fe8cd78440f2187902dbd90afcd3f3a2",
          "md5": "a7a36ed0ba1755ebec0e74217c827172"
        }
      ]
    }
  ]
}
