{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04654-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04654-DEV.jar",
          "url": "embedded-mas-0.04654-DEV.jar",
          "size": 70466,
          "sha512": "4df677bf1aad534e8369d304c39b866b09f2e42ce69ae6429161414c12af0bd0792f2243504481072414005e4e418600902f6b4d7991b0ab80887d87f4f6774a",
          "sha256": "b0da6484db7bfa8b3a9e6580b15cfd223b33af12c2e23b3ad6d913d7bba5d1d7",
          "sha1": "b24a637c5316a5506ce1d44b2a3d2576c82a4ac6",
          "md5": "d96aa5be1aafbf51fd9e17d49a173862"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04654-DEV.jar",
          "url": "embedded-mas-0.04654-DEV.jar",
          "size": 70466,
          "sha512": "4df677bf1aad534e8369d304c39b866b09f2e42ce69ae6429161414c12af0bd0792f2243504481072414005e4e418600902f6b4d7991b0ab80887d87f4f6774a",
          "sha256": "b0da6484db7bfa8b3a9e6580b15cfd223b33af12c2e23b3ad6d913d7bba5d1d7",
          "sha1": "b24a637c5316a5506ce1d44b2a3d2576c82a4ac6",
          "md5": "d96aa5be1aafbf51fd9e17d49a173862"
        }
      ]
    }
  ]
}
