{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04654-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04654-DEV.jar",
          "url": "embedded-mas-0.04654-DEV.jar",
          "size": 70554,
          "sha512": "4e225be0ec72a097a0a150846a10c583ce5ac93d99af8bc48fda630bd723c56be458a6ff082299ef2c03a4af5ae1ab65ebabbca623f3025e118e5e3d10cb09c4",
          "sha256": "3b275fb12260b6bf04b130ef7590238996f77ef3af379d26af95edae7c7e3721",
          "sha1": "09c64b0e84963253aa21bb0a9d8de1f74923ee72",
          "md5": "7df9dd1eec88b04a7bf9340365af324c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04654-DEV.jar",
          "url": "embedded-mas-0.04654-DEV.jar",
          "size": 70554,
          "sha512": "4e225be0ec72a097a0a150846a10c583ce5ac93d99af8bc48fda630bd723c56be458a6ff082299ef2c03a4af5ae1ab65ebabbca623f3025e118e5e3d10cb09c4",
          "sha256": "3b275fb12260b6bf04b130ef7590238996f77ef3af379d26af95edae7c7e3721",
          "sha1": "09c64b0e84963253aa21bb0a9d8de1f74923ee72",
          "md5": "7df9dd1eec88b04a7bf9340365af324c"
        }
      ]
    }
  ]
}
