{
  "formatVersion": "1.1",
  "component": {
    "group": "javard",
    "module": "javard",
    "version": "0.027-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "javard-0.031-6-SNAPSHOT.jar",
          "url": "javard-0.031-6-SNAPSHOT.jar",
          "size": 4690,
          "sha512": "4f91be42465c7d526f23a0391328c4fbc0306fb30551579eba6dafa1403db342dc6a23cffef52dbb121cbca9b6d39eba83ba5e3c31d975c6e8bf8f0cfddb2fea",
          "sha256": "24a7f43c8727faa8e9329374677fd936a788ae54615d2335b4b768ecc1ae8208",
          "sha1": "aa2d694a8ae3ee5cc0a18fc1a3ac7015f931b1ae",
          "md5": "2e21fb3d2393a7429395bc5ff88cc502"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "javard-0.031-6-SNAPSHOT.jar",
          "url": "javard-0.031-6-SNAPSHOT.jar",
          "size": 4690,
          "sha512": "4f91be42465c7d526f23a0391328c4fbc0306fb30551579eba6dafa1403db342dc6a23cffef52dbb121cbca9b6d39eba83ba5e3c31d975c6e8bf8f0cfddb2fea",
          "sha256": "24a7f43c8727faa8e9329374677fd936a788ae54615d2335b4b768ecc1ae8208",
          "sha1": "aa2d694a8ae3ee5cc0a18fc1a3ac7015f931b1ae",
          "md5": "2e21fb3d2393a7429395bc5ff88cc502"
        }
      ]
    }
  ]
}
