{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.02710-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02710-SNAPSHOT.jar",
          "url": "embedded-mas-0.02710-SNAPSHOT.jar",
          "size": 30090,
          "sha512": "a48a4e658d2ae85048ad902656b2f662c81ce58f55b6629e2dd6525b42ee035a4861d6f7529b9e41761d78038505096b00bfc0623b67800edf55a514d8c89bfa",
          "sha256": "8bcdb1adb89796a6be0f6db29677f2f09e8750e42ade0a57690a23b7458c63eb",
          "sha1": "f7017ac50e2c3ddbabd962e827747f37abd0d8dc",
          "md5": "7e6171aaaa71922b0691a91fb0cb7477"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02710-SNAPSHOT.jar",
          "url": "embedded-mas-0.02710-SNAPSHOT.jar",
          "size": 30090,
          "sha512": "a48a4e658d2ae85048ad902656b2f662c81ce58f55b6629e2dd6525b42ee035a4861d6f7529b9e41761d78038505096b00bfc0623b67800edf55a514d8c89bfa",
          "sha256": "8bcdb1adb89796a6be0f6db29677f2f09e8750e42ade0a57690a23b7458c63eb",
          "sha1": "f7017ac50e2c3ddbabd962e827747f37abd0d8dc",
          "md5": "7e6171aaaa71922b0691a91fb0cb7477"
        }
      ]
    }
  ]
}
