{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04606-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04606-SNAPSHOT.jar",
          "url": "embedded-mas-0.04606-SNAPSHOT.jar",
          "size": 68827,
          "sha512": "2dcbf29b1319daf7ea34844fb423329e2ec31e3ed960823c0778ce630a7e85e6d7e91297dd9f004596c2f58c5f28436462c2144ac04ca2bb59bc7c843a66c974",
          "sha256": "098cb165ec468bf7b0e615f49e4f1ab90723ba9df81c01c30c614af1e8f75e08",
          "sha1": "16a98ecd2e6411c46c511ecf527e1be2c0be26c6",
          "md5": "0a37e0942dcb0317a4a73664e55f0e65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04606-SNAPSHOT.jar",
          "url": "embedded-mas-0.04606-SNAPSHOT.jar",
          "size": 68827,
          "sha512": "2dcbf29b1319daf7ea34844fb423329e2ec31e3ed960823c0778ce630a7e85e6d7e91297dd9f004596c2f58c5f28436462c2144ac04ca2bb59bc7c843a66c974",
          "sha256": "098cb165ec468bf7b0e615f49e4f1ab90723ba9df81c01c30c614af1e8f75e08",
          "sha1": "16a98ecd2e6411c46c511ecf527e1be2c0be26c6",
          "md5": "0a37e0942dcb0317a4a73664e55f0e65"
        }
      ]
    }
  ]
}
