{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03801-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03801-SNAPSHOT.jar",
          "url": "embedded-mas-0.03801-SNAPSHOT.jar",
          "size": 71064,
          "sha512": "e11c12d1d1433a70186524f1b99d78e8174047be26e3c2c4af95bb9d46d73fdbdd8ffc350e980f0a3a966bab43f9cecfb3b02ca4c6809fe84c075eeabc305413",
          "sha256": "d4bc2b0e6e2a8a4f83a185ccca42dcb8f2bfd85e0fa05fd7a1150e97ad21b51d",
          "sha1": "7d92ce882dc0a06e411494fe71d520ec0fa1043f",
          "md5": "aa374dbe6dea3879bef42b7527237942"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03801-SNAPSHOT.jar",
          "url": "embedded-mas-0.03801-SNAPSHOT.jar",
          "size": 71064,
          "sha512": "e11c12d1d1433a70186524f1b99d78e8174047be26e3c2c4af95bb9d46d73fdbdd8ffc350e980f0a3a966bab43f9cecfb3b02ca4c6809fe84c075eeabc305413",
          "sha256": "d4bc2b0e6e2a8a4f83a185ccca42dcb8f2bfd85e0fa05fd7a1150e97ad21b51d",
          "sha1": "7d92ce882dc0a06e411494fe71d520ec0fa1043f",
          "md5": "aa374dbe6dea3879bef42b7527237942"
        }
      ]
    }
  ]
}
