{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0270701-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0270701-SNAPSHOT.jar",
          "url": "embedded-mas-0.0270701-SNAPSHOT.jar",
          "size": 30004,
          "sha512": "8691e44e3d88763f9f6a48b6f05126d6450080cca3d3b91f7461cc8d6f921546db58313db27de12273b1d1bac473af3b7fea90e0bb5f590d992c55e9b58bbe29",
          "sha256": "94f754bd1fd2ba05b90d8fc1b45af55dd7b23956d0d47494dd7d171e740be6c6",
          "sha1": "2dcfa6b45effb23ae33bc7cde67846bf7f15c399",
          "md5": "cb04686e98519072094329d59799971b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0270701-SNAPSHOT.jar",
          "url": "embedded-mas-0.0270701-SNAPSHOT.jar",
          "size": 30004,
          "sha512": "8691e44e3d88763f9f6a48b6f05126d6450080cca3d3b91f7461cc8d6f921546db58313db27de12273b1d1bac473af3b7fea90e0bb5f590d992c55e9b58bbe29",
          "sha256": "94f754bd1fd2ba05b90d8fc1b45af55dd7b23956d0d47494dd7d171e740be6c6",
          "sha1": "2dcfa6b45effb23ae33bc7cde67846bf7f15c399",
          "md5": "cb04686e98519072094329d59799971b"
        }
      ]
    }
  ]
}
