{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04303-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04303-SNAPSHOT.jar",
          "url": "embedded-mas-0.04303-SNAPSHOT.jar",
          "size": 74321,
          "sha512": "88b038b306ef796ef3c43e2f15e2163efe0ab52ecbe07f497b988f70308b6382ee451f9d91be7d9cefdb842bdbeb032779e623316b8d72b7caa3d7856c6c49a2",
          "sha256": "b0e143578a8af0f338055f827618020ec657370d7ef0deaba4330488fb9c65a4",
          "sha1": "71ed433eec097b44020a5a2fdaf0d59259d387c3",
          "md5": "b900ef7c69d5987951edaa9043314ff8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04303-SNAPSHOT.jar",
          "url": "embedded-mas-0.04303-SNAPSHOT.jar",
          "size": 74321,
          "sha512": "88b038b306ef796ef3c43e2f15e2163efe0ab52ecbe07f497b988f70308b6382ee451f9d91be7d9cefdb842bdbeb032779e623316b8d72b7caa3d7856c6c49a2",
          "sha256": "b0e143578a8af0f338055f827618020ec657370d7ef0deaba4330488fb9c65a4",
          "sha1": "71ed433eec097b44020a5a2fdaf0d59259d387c3",
          "md5": "b900ef7c69d5987951edaa9043314ff8"
        }
      ]
    }
  ]
}
