{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04672-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04672-DEV.jar",
          "url": "embedded-mas-0.04672-DEV.jar",
          "size": 70867,
          "sha512": "ca25a0f5851b4939837eda1140c479a41fb23bce7d572ffcf49a228f8a1a7b22407bfc364879b94b3e116a8118ae85848b7c8b868808af3fd19ae4e1643bcfff",
          "sha256": "17e0cb4487483fd5bbf2e95182c0742bdd9dfd2b2142bd1daa966b3270444fc1",
          "sha1": "3bcb12701345f19ae0a6c564f711797530b71b59",
          "md5": "a7319ded3f6f44bbb76f25caa7fdca1a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04672-DEV.jar",
          "url": "embedded-mas-0.04672-DEV.jar",
          "size": 70867,
          "sha512": "ca25a0f5851b4939837eda1140c479a41fb23bce7d572ffcf49a228f8a1a7b22407bfc364879b94b3e116a8118ae85848b7c8b868808af3fd19ae4e1643bcfff",
          "sha256": "17e0cb4487483fd5bbf2e95182c0742bdd9dfd2b2142bd1daa966b3270444fc1",
          "sha1": "3bcb12701345f19ae0a6c564f711797530b71b59",
          "md5": "a7319ded3f6f44bbb76f25caa7fdca1a"
        }
      ]
    }
  ]
}
