{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03024-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03024-SNAPSHOT.jar",
          "url": "embedded-mas-0.03024-SNAPSHOT.jar",
          "size": 58505,
          "sha512": "032942a652e611415e3089ab20c6767b5208aac803676378f7219eea9e9da4e646e2b18be6cc6e6e8fe005002d652e09f82600b6b7d1bbc5cb5a8a812dd4b1a3",
          "sha256": "de28a4860bf8fd73ace17bbb9356fb32ccc78bda88104eb26cc3028f40c33902",
          "sha1": "74c86c2f172bce8528e4038208a667fbccbcbd0e",
          "md5": "aee1ca6cfbb2e362ae80d141e08c6573"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03024-SNAPSHOT.jar",
          "url": "embedded-mas-0.03024-SNAPSHOT.jar",
          "size": 58505,
          "sha512": "032942a652e611415e3089ab20c6767b5208aac803676378f7219eea9e9da4e646e2b18be6cc6e6e8fe005002d652e09f82600b6b7d1bbc5cb5a8a812dd4b1a3",
          "sha256": "de28a4860bf8fd73ace17bbb9356fb32ccc78bda88104eb26cc3028f40c33902",
          "sha1": "74c86c2f172bce8528e4038208a667fbccbcbd0e",
          "md5": "aee1ca6cfbb2e362ae80d141e08c6573"
        }
      ]
    }
  ]
}
