{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03026-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03026-SNAPSHOT.jar",
          "url": "embedded-mas-0.03026-SNAPSHOT.jar",
          "size": 58713,
          "sha512": "2d4f1cb85ae56a1bd37403d426435d4859c2d3a4204961ba976d737790200e5cb5c354767b412354aafe97dff75c1d58bd717cc278a7813e80a2ce386b9897c7",
          "sha256": "8f39f99d29231dd6acf594622a51962d5d1feeb8ce46c26bc639139954b29cd6",
          "sha1": "7d1d591ac29e5d240be1b7995bac1a3f7655b44c",
          "md5": "1fd2a99939dee6be66b4fe7f93de58b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03026-SNAPSHOT.jar",
          "url": "embedded-mas-0.03026-SNAPSHOT.jar",
          "size": 58713,
          "sha512": "2d4f1cb85ae56a1bd37403d426435d4859c2d3a4204961ba976d737790200e5cb5c354767b412354aafe97dff75c1d58bd717cc278a7813e80a2ce386b9897c7",
          "sha256": "8f39f99d29231dd6acf594622a51962d5d1feeb8ce46c26bc639139954b29cd6",
          "sha1": "7d1d591ac29e5d240be1b7995bac1a3f7655b44c",
          "md5": "1fd2a99939dee6be66b4fe7f93de58b5"
        }
      ]
    }
  ]
}
