{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.038-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038-SNAPSHOT.jar",
          "url": "embedded-mas-0.038-SNAPSHOT.jar",
          "size": 68500,
          "sha512": "56259ed399f24d6eb7ef2cb66d053b9c3a414547f0359d815fb3340174c324f6c8d9b1cbe592ccf02cbf08078eefff9523f7054e7d2324d402a36626294673cf",
          "sha256": "f4ac756d1a277e702dc21c410d8fb98b60877e757725b2bf7c158cb30979ef6d",
          "sha1": "665c530b3e24e40b15365658298ee79b43f773ca",
          "md5": "24dbd8b197e411c6b71dd185c258b71e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038-SNAPSHOT.jar",
          "url": "embedded-mas-0.038-SNAPSHOT.jar",
          "size": 68500,
          "sha512": "56259ed399f24d6eb7ef2cb66d053b9c3a414547f0359d815fb3340174c324f6c8d9b1cbe592ccf02cbf08078eefff9523f7054e7d2324d402a36626294673cf",
          "sha256": "f4ac756d1a277e702dc21c410d8fb98b60877e757725b2bf7c158cb30979ef6d",
          "sha1": "665c530b3e24e40b15365658298ee79b43f773ca",
          "md5": "24dbd8b197e411c6b71dd185c258b71e"
        }
      ]
    }
  ]
}
