{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04202-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04202-SNAPSHOT.jar",
          "url": "embedded-mas-0.04202-SNAPSHOT.jar",
          "size": 72596,
          "sha512": "0eab03f1e9c4824b5c0bfed3502478f57678f77f2b7c67c5e4d760857696bb2521dd02f11acdb0a9a276817b555871baccdc1249e05b5f6fa6acb830899214d7",
          "sha256": "2bec4cd5ada9ff7c601ee4b86668f0e1c81bd8ec1a6357e11846c5430482c256",
          "sha1": "6de723b7943f5e088f3b77031c547b85eac85e33",
          "md5": "e80b1d7062f21f3792ea56b075873495"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04202-SNAPSHOT.jar",
          "url": "embedded-mas-0.04202-SNAPSHOT.jar",
          "size": 72596,
          "sha512": "0eab03f1e9c4824b5c0bfed3502478f57678f77f2b7c67c5e4d760857696bb2521dd02f11acdb0a9a276817b555871baccdc1249e05b5f6fa6acb830899214d7",
          "sha256": "2bec4cd5ada9ff7c601ee4b86668f0e1c81bd8ec1a6357e11846c5430482c256",
          "sha1": "6de723b7943f5e088f3b77031c547b85eac85e33",
          "md5": "e80b1d7062f21f3792ea56b075873495"
        }
      ]
    }
  ]
}
