{
  "formatVersion": "1.1",
  "component": {
    "group": "javard",
    "module": "javard",
    "version": "0.034-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "javard-0.034-SNAPSHOT.jar",
          "url": "javard-0.034-SNAPSHOT.jar",
          "size": 4690,
          "sha512": "beac063027e4ad80a0bf2645932f07940ee9a86c149080062e968c2b05f0c7ddb80fde78f059e672d81341453ee95ecf132ccad39f94a30c98931cc69835699f",
          "sha256": "89c394822a093cf61fabb382ce7a7ad3fd90b4826956a1e518d251fdbb475078",
          "sha1": "cb56910f8c904c1709f5dad631dca501a74a9b9e",
          "md5": "8614304ca69992bf787e14388b94c0d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "javard-0.034-SNAPSHOT.jar",
          "url": "javard-0.034-SNAPSHOT.jar",
          "size": 4690,
          "sha512": "beac063027e4ad80a0bf2645932f07940ee9a86c149080062e968c2b05f0c7ddb80fde78f059e672d81341453ee95ecf132ccad39f94a30c98931cc69835699f",
          "sha256": "89c394822a093cf61fabb382ce7a7ad3fd90b4826956a1e518d251fdbb475078",
          "sha1": "cb56910f8c904c1709f5dad631dca501a74a9b9e",
          "md5": "8614304ca69992bf787e14388b94c0d1"
        }
      ]
    }
  ]
}
