{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271537-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271537-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271537-SNAPSHOT.jar",
          "size": 31072,
          "sha512": "49b7d5e5d580af8f2fb53ac8f9beacbe3b49bda90102c22560e90afdd04e39510b7a7de161d06c053f91a840e31292d18cce1fc98f72363b90dd1bd70c17be63",
          "sha256": "19e251872507c09c2ac515c786a5707ae583222af0b629c67de049e451ed071f",
          "sha1": "90729609f7565f70c3ae759bfbee8c014d6e3560",
          "md5": "784035f29627d9eaae5c170984bd0433"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271537-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271537-SNAPSHOT.jar",
          "size": 31072,
          "sha512": "49b7d5e5d580af8f2fb53ac8f9beacbe3b49bda90102c22560e90afdd04e39510b7a7de161d06c053f91a840e31292d18cce1fc98f72363b90dd1bd70c17be63",
          "sha256": "19e251872507c09c2ac515c786a5707ae583222af0b629c67de049e451ed071f",
          "sha1": "90729609f7565f70c3ae759bfbee8c014d6e3560",
          "md5": "784035f29627d9eaae5c170984bd0433"
        }
      ]
    }
  ]
}
