{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271519-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271519-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271519-SNAPSHOT.jar",
          "size": 30914,
          "sha512": "4a169ecd9a612113f84cf4952fc4f175c24b71fa3225f4f3635c69d0d5631d1f32c49682a81b5d7bc90830d1ff5c9079a1d96e76f6ca31b63fb841911638c490",
          "sha256": "4e2331d10bb39dad69ec90e5126fd8c7b29095bee00d9e230ea3325ea43d75fb",
          "sha1": "bfc5bb21761e9891c9638e322f5fd5d69aae99b0",
          "md5": "03320f5cd89fac92d506d968b381c514"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271519-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271519-SNAPSHOT.jar",
          "size": 30914,
          "sha512": "4a169ecd9a612113f84cf4952fc4f175c24b71fa3225f4f3635c69d0d5631d1f32c49682a81b5d7bc90830d1ff5c9079a1d96e76f6ca31b63fb841911638c490",
          "sha256": "4e2331d10bb39dad69ec90e5126fd8c7b29095bee00d9e230ea3325ea43d75fb",
          "sha1": "bfc5bb21761e9891c9638e322f5fd5d69aae99b0",
          "md5": "03320f5cd89fac92d506d968b381c514"
        }
      ]
    }
  ]
}
