{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04674-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04674-DEV.jar",
          "url": "embedded-mas-0.04674-DEV.jar",
          "size": 70781,
          "sha512": "67affaafc28d2d1a54b3f1de8e68bfa8887672fdce4d51b173f5708edca92046c215e5fb77e3661f567c65db3868244160c49dfeaeaf5c88196b73bd735c2c43",
          "sha256": "95ed87ba16e91a9673bd8b59c643e3691cf6b23d7bf9f7a2b9bfa6fb546ce904",
          "sha1": "5408003e5bcf625f26399d2d0b44204f1992f45a",
          "md5": "54093e0f6cdf642fe2c77bd383b1ed44"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04674-DEV.jar",
          "url": "embedded-mas-0.04674-DEV.jar",
          "size": 70781,
          "sha512": "67affaafc28d2d1a54b3f1de8e68bfa8887672fdce4d51b173f5708edca92046c215e5fb77e3661f567c65db3868244160c49dfeaeaf5c88196b73bd735c2c43",
          "sha256": "95ed87ba16e91a9673bd8b59c643e3691cf6b23d7bf9f7a2b9bfa6fb546ce904",
          "sha1": "5408003e5bcf625f26399d2d0b44204f1992f45a",
          "md5": "54093e0f6cdf642fe2c77bd383b1ed44"
        }
      ]
    }
  ]
}
