{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03802-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03802-SNAPSHOT.jar",
          "url": "embedded-mas-0.03802-SNAPSHOT.jar",
          "size": 71102,
          "sha512": "fcf0337d10657cdd40dec04b9c76710ba937ee0fab93b7fe78feb8e72c85d591eeb70167518f9cfb7de9adc7352ac6443a8d7dd86977ebfc03977896ba214b33",
          "sha256": "a45542c8f6787ab771af02b45d7af9b896ab09375e114153420467859c1e72b6",
          "sha1": "f194083612d2d2b9421876beb6aa394fb613b2e5",
          "md5": "a724349750ddaa16a9e5e765556b5b91"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03802-SNAPSHOT.jar",
          "url": "embedded-mas-0.03802-SNAPSHOT.jar",
          "size": 71102,
          "sha512": "fcf0337d10657cdd40dec04b9c76710ba937ee0fab93b7fe78feb8e72c85d591eeb70167518f9cfb7de9adc7352ac6443a8d7dd86977ebfc03977896ba214b33",
          "sha256": "a45542c8f6787ab771af02b45d7af9b896ab09375e114153420467859c1e72b6",
          "sha1": "f194083612d2d2b9421876beb6aa394fb613b2e5",
          "md5": "a724349750ddaa16a9e5e765556b5b91"
        }
      ]
    }
  ]
}
