{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04623-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04623-SNAPSHOT.jar",
          "url": "embedded-mas-0.04623-SNAPSHOT.jar",
          "size": 68828,
          "sha512": "6daf14ce43b481d1c1ca68e5f3f5538ec3c4b86810a70bf671f14f93276e3d7ad251996c1a405b48fb2b8d78306dd6bc81ddc345819a323f19254d9cd41abea4",
          "sha256": "43860f58b2fd5315eae1ae8bba8d73ea4d19a826f0d9aae14f73cc202a76083a",
          "sha1": "a4901408183dbc956b2524ac0f8a6177c5069dd4",
          "md5": "7276354aef2c6557970f5441fb97e898"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04623-SNAPSHOT.jar",
          "url": "embedded-mas-0.04623-SNAPSHOT.jar",
          "size": 68828,
          "sha512": "6daf14ce43b481d1c1ca68e5f3f5538ec3c4b86810a70bf671f14f93276e3d7ad251996c1a405b48fb2b8d78306dd6bc81ddc345819a323f19254d9cd41abea4",
          "sha256": "43860f58b2fd5315eae1ae8bba8d73ea4d19a826f0d9aae14f73cc202a76083a",
          "sha1": "a4901408183dbc956b2524ac0f8a6177c5069dd4",
          "md5": "7276354aef2c6557970f5441fb97e898"
        }
      ]
    }
  ]
}
