{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03201-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03201-SNAPSHOT.jar",
          "url": "embedded-mas-0.03201-SNAPSHOT.jar",
          "size": 62031,
          "sha512": "0b9fd809028febf48e27ee0ca92dd077b56752baa18e269089429e05316d412e32b244fece0ec678c22e7bde22e50dc99ca22af2c469259e4594739d765f3c25",
          "sha256": "385a08f9251a30b020f5c6d16465b091c160b619da974c337de6ceb8e72e2285",
          "sha1": "8ed27b87c180d94f1f8e0df4bec6eb9f9f9ef334",
          "md5": "88c82bce6a0021ac3659fd85270ecd8e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03201-SNAPSHOT.jar",
          "url": "embedded-mas-0.03201-SNAPSHOT.jar",
          "size": 62031,
          "sha512": "0b9fd809028febf48e27ee0ca92dd077b56752baa18e269089429e05316d412e32b244fece0ec678c22e7bde22e50dc99ca22af2c469259e4594739d765f3c25",
          "sha256": "385a08f9251a30b020f5c6d16465b091c160b619da974c337de6ceb8e72e2285",
          "sha1": "8ed27b87c180d94f1f8e0df4bec6eb9f9f9ef334",
          "md5": "88c82bce6a0021ac3659fd85270ecd8e"
        }
      ]
    }
  ]
}
