{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04622-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04622-SNAPSHOT.jar",
          "url": "embedded-mas-0.04622-SNAPSHOT.jar",
          "size": 69025,
          "sha512": "f71b9657d580f2fe1b9777585fe87f4805b28fa249b875a257fb7fad801d9a0306c8cd299dbd406079abfd34ccde045a01e96f1a3fe7d9cdc74cb79a758e18f0",
          "sha256": "ab1aa2e79cbe7abf83a0a0cf3b4b1e4567c2a77eaf2fe323208f396d0c601f5e",
          "sha1": "1884a945bdd015991dd4b215ead18bbfe2eb4714",
          "md5": "d0976aa7926b24714689630da829708d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04622-SNAPSHOT.jar",
          "url": "embedded-mas-0.04622-SNAPSHOT.jar",
          "size": 69025,
          "sha512": "f71b9657d580f2fe1b9777585fe87f4805b28fa249b875a257fb7fad801d9a0306c8cd299dbd406079abfd34ccde045a01e96f1a3fe7d9cdc74cb79a758e18f0",
          "sha256": "ab1aa2e79cbe7abf83a0a0cf3b4b1e4567c2a77eaf2fe323208f396d0c601f5e",
          "sha1": "1884a945bdd015991dd4b215ead18bbfe2eb4714",
          "md5": "d0976aa7926b24714689630da829708d"
        }
      ]
    }
  ]
}
