{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.02802-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02802-SNAPSHOT.jar",
          "url": "embedded-mas-0.02802-SNAPSHOT.jar",
          "size": 30688,
          "sha512": "086ca516c0406a68dcf8038a01b73f72c71d28647fc78dcc1e90652970d1af4d122de76012ac7fa7afaa4189f87ede9248b46d37e841363322815becafcf7318",
          "sha256": "197ad4df47784e43a53d39bc5247dd3e71a3d57a2cb2f2f92668d3229d636fe9",
          "sha1": "c6d372c45c132c9be8e75cfa19c37ce04997f600",
          "md5": "a33b030930f67a53e4e3215c2c28cd33"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02802-SNAPSHOT.jar",
          "url": "embedded-mas-0.02802-SNAPSHOT.jar",
          "size": 30688,
          "sha512": "086ca516c0406a68dcf8038a01b73f72c71d28647fc78dcc1e90652970d1af4d122de76012ac7fa7afaa4189f87ede9248b46d37e841363322815becafcf7318",
          "sha256": "197ad4df47784e43a53d39bc5247dd3e71a3d57a2cb2f2f92668d3229d636fe9",
          "sha1": "c6d372c45c132c9be8e75cfa19c37ce04997f600",
          "md5": "a33b030930f67a53e4e3215c2c28cd33"
        }
      ]
    }
  ]
}
