{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03008-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03008-SNAPSHOT.jar",
          "url": "embedded-mas-0.03008-SNAPSHOT.jar",
          "size": 53535,
          "sha512": "c946f68c4353ace889ea85809e554258b3ad500281437a85f69a29bcf23d00c0c536464c80b400bae013a14f36b3ee4a40d0459a37e8bac23cda8a103d6c99f5",
          "sha256": "ef449ca8041ef58b7793569b5ce99bceeca75fcf1acb981ca1d48df082878af2",
          "sha1": "16eefab01a3e0007f4bcf7de2569b559787c9cff",
          "md5": "2a5bbd3b581e3c8e6db43b17860968df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03008-SNAPSHOT.jar",
          "url": "embedded-mas-0.03008-SNAPSHOT.jar",
          "size": 53535,
          "sha512": "c946f68c4353ace889ea85809e554258b3ad500281437a85f69a29bcf23d00c0c536464c80b400bae013a14f36b3ee4a40d0459a37e8bac23cda8a103d6c99f5",
          "sha256": "ef449ca8041ef58b7793569b5ce99bceeca75fcf1acb981ca1d48df082878af2",
          "sha1": "16eefab01a3e0007f4bcf7de2569b559787c9cff",
          "md5": "2a5bbd3b581e3c8e6db43b17860968df"
        }
      ]
    }
  ]
}
