{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04613-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04613-SNAPSHOT.jar",
          "url": "embedded-mas-0.04613-SNAPSHOT.jar",
          "size": 69195,
          "sha512": "ef0ec4ef2f73ea649927096232a5f5bfb5c3c2065aaa12781f04794205d62afcaae31c7e72ff22373aa2edb7c72c6c7eacd0954bed6ca94caae47e4e0d8c2d25",
          "sha256": "6e5df60044c64e31c0b67f4ebdc3154df33d42ac70fd77bf342dff6bebd4b227",
          "sha1": "8a37293c5e8fb89f904836717675519ec50c0839",
          "md5": "2a6399dc0118d872862119022cef9d3b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04613-SNAPSHOT.jar",
          "url": "embedded-mas-0.04613-SNAPSHOT.jar",
          "size": 69195,
          "sha512": "ef0ec4ef2f73ea649927096232a5f5bfb5c3c2065aaa12781f04794205d62afcaae31c7e72ff22373aa2edb7c72c6c7eacd0954bed6ca94caae47e4e0d8c2d25",
          "sha256": "6e5df60044c64e31c0b67f4ebdc3154df33d42ac70fd77bf342dff6bebd4b227",
          "sha1": "8a37293c5e8fb89f904836717675519ec50c0839",
          "md5": "2a6399dc0118d872862119022cef9d3b"
        }
      ]
    }
  ]
}
