{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-unspecified.jar",
          "url": "embedded-mas-unspecified.jar",
          "size": 74321,
          "sha512": "9a0c9f3d9cfd383a91bdcc1b05f61e0b6e1b6a97ff877cfb1dfe1eeea654c712beb59040d3b5b8570a21702dbd11cd3c11ece4c6d7eb11b0c68695ce4b700714",
          "sha256": "773063362f90f0278a22691029a547658e4b1c067918d65051a2ff71f7159f29",
          "sha1": "4328f1e3a32fd9486987aa6c3735558aca1439ce",
          "md5": "7be7962db7ebdafb14a12141b443e39d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-unspecified.jar",
          "url": "embedded-mas-unspecified.jar",
          "size": 74321,
          "sha512": "9a0c9f3d9cfd383a91bdcc1b05f61e0b6e1b6a97ff877cfb1dfe1eeea654c712beb59040d3b5b8570a21702dbd11cd3c11ece4c6d7eb11b0c68695ce4b700714",
          "sha256": "773063362f90f0278a22691029a547658e4b1c067918d65051a2ff71f7159f29",
          "sha1": "4328f1e3a32fd9486987aa6c3735558aca1439ce",
          "md5": "7be7962db7ebdafb14a12141b443e39d"
        }
      ]
    }
  ]
}
