{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.038002-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038002-SNAPSHOT.jar",
          "url": "embedded-mas-0.038002-SNAPSHOT.jar",
          "size": 67995,
          "sha512": "469e2cbe676a2004dda4bcbcc4f6d9a9b5bc1254300e17735861090b80e0dfc1504b76f6f7e9d205dbd0b65cc7ec267509a70750822cfdd2bad6c6e4eacd9dbd",
          "sha256": "3297cb2b752ac78cc1c142ce4b273a28f28cf4797838ca50f37efcedfce21844",
          "sha1": "2ac42dfbe5487ead9a6790f279afd213e2da2f78",
          "md5": "dde951b2846bbc1322b64eb17d790f91"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038002-SNAPSHOT.jar",
          "url": "embedded-mas-0.038002-SNAPSHOT.jar",
          "size": 67995,
          "sha512": "469e2cbe676a2004dda4bcbcc4f6d9a9b5bc1254300e17735861090b80e0dfc1504b76f6f7e9d205dbd0b65cc7ec267509a70750822cfdd2bad6c6e4eacd9dbd",
          "sha256": "3297cb2b752ac78cc1c142ce4b273a28f28cf4797838ca50f37efcedfce21844",
          "sha1": "2ac42dfbe5487ead9a6790f279afd213e2da2f78",
          "md5": "dde951b2846bbc1322b64eb17d790f91"
        }
      ]
    }
  ]
}
