{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271506-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271506-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271506-SNAPSHOT.jar",
          "size": 30464,
          "sha512": "f8fc198b5606df3e0ce014ef6ebc5a7a647455ed56a28fbc10f087a2259cee36eb666d69b891b0e66c4b2b6fcad9d7298921fa99c7b7a7b75479ad21da476d00",
          "sha256": "4e8732a34350c3f348cea958d239e9798310c2d9e449d2a8ae715c694df82648",
          "sha1": "8eb3f7b76f8bbd97a28460da4ef6098e9c12b5fa",
          "md5": "8054914504a1da7c9f07760d6616073c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271506-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271506-SNAPSHOT.jar",
          "size": 30464,
          "sha512": "f8fc198b5606df3e0ce014ef6ebc5a7a647455ed56a28fbc10f087a2259cee36eb666d69b891b0e66c4b2b6fcad9d7298921fa99c7b7a7b75479ad21da476d00",
          "sha256": "4e8732a34350c3f348cea958d239e9798310c2d9e449d2a8ae715c694df82648",
          "sha1": "8eb3f7b76f8bbd97a28460da4ef6098e9c12b5fa",
          "md5": "8054914504a1da7c9f07760d6616073c"
        }
      ]
    }
  ]
}
