{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.039-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.039-SNAPSHOT.jar",
          "url": "embedded-mas-0.039-SNAPSHOT.jar",
          "size": 71102,
          "sha512": "2b89e1c774347326ee91c71d94cf7906683fb6072a1b96914283e2c03a1554f2f5a1fb732137d4a11ae9c52d250a428a62383934660bded375c08105bf071b64",
          "sha256": "33eea1074272bbb6a1a90c39ca898460144d2d8c29b6801794ce231f1a4e13bf",
          "sha1": "8285b45c710f4641779e5d3206437ba6963f9bc0",
          "md5": "c7152687752827415e3af9de28d7b5f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.039-SNAPSHOT.jar",
          "url": "embedded-mas-0.039-SNAPSHOT.jar",
          "size": 71102,
          "sha512": "2b89e1c774347326ee91c71d94cf7906683fb6072a1b96914283e2c03a1554f2f5a1fb732137d4a11ae9c52d250a428a62383934660bded375c08105bf071b64",
          "sha256": "33eea1074272bbb6a1a90c39ca898460144d2d8c29b6801794ce231f1a4e13bf",
          "sha1": "8285b45c710f4641779e5d3206437ba6963f9bc0",
          "md5": "c7152687752827415e3af9de28d7b5f9"
        }
      ]
    }
  ]
}
