{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03018-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03018-SNAPSHOT.jar",
          "url": "embedded-mas-0.03018-SNAPSHOT.jar",
          "size": 54633,
          "sha512": "c37c48deffab0f2b143c0bb71da4fd44306707354b144bbc5cbd0f4f202c3c47c149f95342e29d7488ec11d98037c9822d87a81fb322ec6ccbfdf7aee3ad79bc",
          "sha256": "766690c86466054a59f7996d0df6d03ac37975dd57f538dda601b338476dab2b",
          "sha1": "863c8a0128d65f2609740f6b53e2aeddd1767b2e",
          "md5": "c0c49f0651bcf87969448e55c8abaf17"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03018-SNAPSHOT.jar",
          "url": "embedded-mas-0.03018-SNAPSHOT.jar",
          "size": 54633,
          "sha512": "c37c48deffab0f2b143c0bb71da4fd44306707354b144bbc5cbd0f4f202c3c47c149f95342e29d7488ec11d98037c9822d87a81fb322ec6ccbfdf7aee3ad79bc",
          "sha256": "766690c86466054a59f7996d0df6d03ac37975dd57f538dda601b338476dab2b",
          "sha1": "863c8a0128d65f2609740f6b53e2aeddd1767b2e",
          "md5": "c0c49f0651bcf87969448e55c8abaf17"
        }
      ]
    }
  ]
}
