{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03031-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03031-SNAPSHOT.jar",
          "url": "embedded-mas-0.03031-SNAPSHOT.jar",
          "size": 60035,
          "sha512": "2267bfb269e858e285718dfcb13271935a2d3a612f36c3a34498b3d72a7c6c1abe64edc96dcf496b46834191beaad3df519a6e51f59d2495ecbb220894420d7e",
          "sha256": "423b505a096ac80d6a9a80496ff72b00b14d89cfd7da9335f5174530e2cddc4a",
          "sha1": "ee0f19e5947bafc5c918a5c17d4c1ec76c22022e",
          "md5": "c982871040725463ad6f12925b7cbbc6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03031-SNAPSHOT.jar",
          "url": "embedded-mas-0.03031-SNAPSHOT.jar",
          "size": 60035,
          "sha512": "2267bfb269e858e285718dfcb13271935a2d3a612f36c3a34498b3d72a7c6c1abe64edc96dcf496b46834191beaad3df519a6e51f59d2495ecbb220894420d7e",
          "sha256": "423b505a096ac80d6a9a80496ff72b00b14d89cfd7da9335f5174530e2cddc4a",
          "sha1": "ee0f19e5947bafc5c918a5c17d4c1ec76c22022e",
          "md5": "c982871040725463ad6f12925b7cbbc6"
        }
      ]
    }
  ]
}
