{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03107-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03107-SNAPSHOT.jar",
          "url": "embedded-mas-0.03107-SNAPSHOT.jar",
          "size": 63573,
          "sha512": "f13158636935982b1339d1114b88faae402d5e224855d23427e39f392b421d9f5dce2abfdcd0c2121afbd6c917eb2d86bf108b361cb62a613d1498ae5f35b55b",
          "sha256": "dd50f4d09c1ebfad485f18d349c968bc5e195bd6dc3e9ce343a7ca6709efc559",
          "sha1": "56b24faf2fe1fd996031c5f05e0a97a7f3589e59",
          "md5": "55d725e73f3c9564198625a7e638bafc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03107-SNAPSHOT.jar",
          "url": "embedded-mas-0.03107-SNAPSHOT.jar",
          "size": 63573,
          "sha512": "f13158636935982b1339d1114b88faae402d5e224855d23427e39f392b421d9f5dce2abfdcd0c2121afbd6c917eb2d86bf108b361cb62a613d1498ae5f35b55b",
          "sha256": "dd50f4d09c1ebfad485f18d349c968bc5e195bd6dc3e9ce343a7ca6709efc559",
          "sha1": "56b24faf2fe1fd996031c5f05e0a97a7f3589e59",
          "md5": "55d725e73f3c9564198625a7e638bafc"
        }
      ]
    }
  ]
}
