{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271526-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271526-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271526-SNAPSHOT.jar",
          "size": 30906,
          "sha512": "b137175f6f13be9ae6b4f13e3cf8dc7fc64a05e7f7be597cacb725750922397fc4369989f1c2347cbe9411b8457c9c89714b3d9b97efed851b05b0385345596e",
          "sha256": "0e47743c059f29a1070e27ab639a4e3ac999e83a58b770e9aa7c305a775ebd4f",
          "sha1": "94d05b24af3de60248d39dbb7afe6037eaf71703",
          "md5": "16a055e5eb8db94621d799af9e020206"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271526-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271526-SNAPSHOT.jar",
          "size": 30906,
          "sha512": "b137175f6f13be9ae6b4f13e3cf8dc7fc64a05e7f7be597cacb725750922397fc4369989f1c2347cbe9411b8457c9c89714b3d9b97efed851b05b0385345596e",
          "sha256": "0e47743c059f29a1070e27ab639a4e3ac999e83a58b770e9aa7c305a775ebd4f",
          "sha1": "94d05b24af3de60248d39dbb7afe6037eaf71703",
          "md5": "16a055e5eb8db94621d799af9e020206"
        }
      ]
    }
  ]
}
