{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04603-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04603-SNAPSHOT.jar",
          "url": "embedded-mas-0.04603-SNAPSHOT.jar",
          "size": 72945,
          "sha512": "07dbae78a2dfb0d3e3816b4d9b3c8ef66156fa0417e8dfe2379097e4b8eba33c452a387ecb651cc5cc7c7f31105dcef1fb58fae9ac44f41eafdb757126c6572e",
          "sha256": "34c32f2de612f51ba28fdea2b5922f8ac288b2e1263ec04bdef399cb2342498b",
          "sha1": "dcbbc1ae168aaaa5bcb0fce23d0fce538ad418a0",
          "md5": "5e574c3751beb9aa203913b06c61d9b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04603-SNAPSHOT.jar",
          "url": "embedded-mas-0.04603-SNAPSHOT.jar",
          "size": 72945,
          "sha512": "07dbae78a2dfb0d3e3816b4d9b3c8ef66156fa0417e8dfe2379097e4b8eba33c452a387ecb651cc5cc7c7f31105dcef1fb58fae9ac44f41eafdb757126c6572e",
          "sha256": "34c32f2de612f51ba28fdea2b5922f8ac288b2e1263ec04bdef399cb2342498b",
          "sha1": "dcbbc1ae168aaaa5bcb0fce23d0fce538ad418a0",
          "md5": "5e574c3751beb9aa203913b06c61d9b9"
        }
      ]
    }
  ]
}
