{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03033-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03033-SNAPSHOT.jar",
          "url": "embedded-mas-0.03033-SNAPSHOT.jar",
          "size": 61294,
          "sha512": "d03e25d9fd6f30d7684b3dc1bc825ae039a068501f6ebb1906aad73575bb629dc64dc68baec04f9de41f9281c53473b436467795c06f199c229ff1640e5b24ff",
          "sha256": "5ea70fd6f5d40cd23f5ae2521e3e7b8758bf485d92b647cc00cffbe6500bc8b4",
          "sha1": "0fb96ca40b2051dbb0bb27e66b5014741e34a359",
          "md5": "180415b2f5f99da312ed97c54281d26e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03033-SNAPSHOT.jar",
          "url": "embedded-mas-0.03033-SNAPSHOT.jar",
          "size": 61294,
          "sha512": "d03e25d9fd6f30d7684b3dc1bc825ae039a068501f6ebb1906aad73575bb629dc64dc68baec04f9de41f9281c53473b436467795c06f199c229ff1640e5b24ff",
          "sha256": "5ea70fd6f5d40cd23f5ae2521e3e7b8758bf485d92b647cc00cffbe6500bc8b4",
          "sha1": "0fb96ca40b2051dbb0bb27e66b5014741e34a359",
          "md5": "180415b2f5f99da312ed97c54281d26e"
        }
      ]
    }
  ]
}
