{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04612-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04612-SNAPSHOT.jar",
          "url": "embedded-mas-0.04612-SNAPSHOT.jar",
          "size": 69089,
          "sha512": "ef7ba69b444738d0f121139391706d854a31b1063d0a4f375a5e62a736ed07367148ba50267e475e7215796c1c159537d60e27bed7799f8fadf558d13016d220",
          "sha256": "29e1f097a46b653912fba1bab1b45f20bf509c04ee01b9c1ee40ad2ecda768c4",
          "sha1": "4471d75370e98d4f0f8aae4503bbe863e546a7f6",
          "md5": "c5cc15c0d35223f0b9d0a99eb1f119c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04612-SNAPSHOT.jar",
          "url": "embedded-mas-0.04612-SNAPSHOT.jar",
          "size": 69089,
          "sha512": "ef7ba69b444738d0f121139391706d854a31b1063d0a4f375a5e62a736ed07367148ba50267e475e7215796c1c159537d60e27bed7799f8fadf558d13016d220",
          "sha256": "29e1f097a46b653912fba1bab1b45f20bf509c04ee01b9c1ee40ad2ecda768c4",
          "sha1": "4471d75370e98d4f0f8aae4503bbe863e546a7f6",
          "md5": "c5cc15c0d35223f0b9d0a99eb1f119c1"
        }
      ]
    }
  ]
}
