{
  "formatVersion": "1.1",
  "component": {
    "group": "javard",
    "module": "javard",
    "version": "0.027-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "javard-0.031-7-SNAPSHOT.jar",
          "url": "javard-0.031-7-SNAPSHOT.jar",
          "size": 4690,
          "sha512": "5d3d0cd88263f1355b6a156bf087026f4d65a6daf2879a96b538bab56fcc8ab37522b60f403af45478baf432802873370191ee1cd3f9c7ea0f469c7c334a7361",
          "sha256": "1e27090d6e8f2806e1e28eccf0413a8b03f95e1b693780ce9b27068f21439a63",
          "sha1": "933b31bf6c9d706c80da4daf1e894447995668f0",
          "md5": "9440d0ba7d505eee67f4aa0f0be09852"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "javard-0.031-7-SNAPSHOT.jar",
          "url": "javard-0.031-7-SNAPSHOT.jar",
          "size": 4690,
          "sha512": "5d3d0cd88263f1355b6a156bf087026f4d65a6daf2879a96b538bab56fcc8ab37522b60f403af45478baf432802873370191ee1cd3f9c7ea0f469c7c334a7361",
          "sha256": "1e27090d6e8f2806e1e28eccf0413a8b03f95e1b693780ce9b27068f21439a63",
          "sha1": "933b31bf6c9d706c80da4daf1e894447995668f0",
          "md5": "9440d0ba7d505eee67f4aa0f0be09852"
        }
      ]
    }
  ]
}
