{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04607-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04607-SNAPSHOT.jar",
          "url": "embedded-mas-0.04607-SNAPSHOT.jar",
          "size": 69023,
          "sha512": "4390bedeeb3c1f484ecf8ac0bf6a89086107c4f887ade68e3d83714f59730a70ce4b4315fe0f4a63bb287834e613a8977dde9a4f2f7b1d4b6da6f589fe543b2c",
          "sha256": "57132095c0b718e11b5e0f4c61b880f9caa25976e078bdfd26c00eee4a40e8d4",
          "sha1": "ed77b98853ac5cd2376a60a09f93ac5524613771",
          "md5": "fa068831d079168b6b6733f3a14eccf0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04607-SNAPSHOT.jar",
          "url": "embedded-mas-0.04607-SNAPSHOT.jar",
          "size": 69023,
          "sha512": "4390bedeeb3c1f484ecf8ac0bf6a89086107c4f887ade68e3d83714f59730a70ce4b4315fe0f4a63bb287834e613a8977dde9a4f2f7b1d4b6da6f589fe543b2c",
          "sha256": "57132095c0b718e11b5e0f4c61b880f9caa25976e078bdfd26c00eee4a40e8d4",
          "sha1": "ed77b98853ac5cd2376a60a09f93ac5524613771",
          "md5": "fa068831d079168b6b6733f3a14eccf0"
        }
      ]
    }
  ]
}
