{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271401-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271401-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271401-SNAPSHOT.jar",
          "size": 30297,
          "sha512": "8eb22959bf485f3702612b50a992b40ee6e15480c8415be7398a4e1641870ce920ce9041a641befd18f15d14e6d3aa3b1436d719f1d2888ec2495e1d1eff322d",
          "sha256": "e8cdcec92107f89c64068db8492e06b77174e5efeb91520394b25a7890bf15e9",
          "sha1": "6f8919cbcdd2510105bc12d3c9e6ff91b41eaaaa",
          "md5": "c5cf17a6f29d0c50857315fa0c49fae1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271401-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271401-SNAPSHOT.jar",
          "size": 30297,
          "sha512": "8eb22959bf485f3702612b50a992b40ee6e15480c8415be7398a4e1641870ce920ce9041a641befd18f15d14e6d3aa3b1436d719f1d2888ec2495e1d1eff322d",
          "sha256": "e8cdcec92107f89c64068db8492e06b77174e5efeb91520394b25a7890bf15e9",
          "sha1": "6f8919cbcdd2510105bc12d3c9e6ff91b41eaaaa",
          "md5": "c5cf17a6f29d0c50857315fa0c49fae1"
        }
      ]
    }
  ]
}
