{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.032-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.032-SNAPSHOT.jar",
          "url": "embedded-mas-0.032-SNAPSHOT.jar",
          "size": 62449,
          "sha512": "3100b70f9e2af2a409c3b0897e3aa5c7d287e73b26abbab0591227b16b45dfcf843d3066222fa7b2a5faf2d77534e30d921e745c76641e0f8283a31e7930b0ba",
          "sha256": "11450bcbb799619d57bcdd3008c07319eec23497577ec1f3f39582da4987aa9a",
          "sha1": "f37a8ea31dea0a0de59035bc1f71d0fdf2fb1c1c",
          "md5": "c39635161a779fde8f849bfd0ba7ecc3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.032-SNAPSHOT.jar",
          "url": "embedded-mas-0.032-SNAPSHOT.jar",
          "size": 62449,
          "sha512": "3100b70f9e2af2a409c3b0897e3aa5c7d287e73b26abbab0591227b16b45dfcf843d3066222fa7b2a5faf2d77534e30d921e745c76641e0f8283a31e7930b0ba",
          "sha256": "11450bcbb799619d57bcdd3008c07319eec23497577ec1f3f39582da4987aa9a",
          "sha1": "f37a8ea31dea0a0de59035bc1f71d0fdf2fb1c1c",
          "md5": "c39635161a779fde8f849bfd0ba7ecc3"
        }
      ]
    }
  ]
}
