{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03019-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03019-SNAPSHOT.jar",
          "url": "embedded-mas-0.03019-SNAPSHOT.jar",
          "size": 54647,
          "sha512": "3a24e17295930464650b374ba0e2f53b5871fa49594e86f9e05df599235dec1033b8866fc0caedc049e144bb54fbf1217a6888a1a2072d5a8e3a53910f8857f4",
          "sha256": "70344b711d383a40594e345c2aaa00ad0bee7a0e94dcaca6f7e1f519d92cf7f5",
          "sha1": "e746287b256bff2168416f7c4a77ed331fa1a154",
          "md5": "fb8ee366192b2ac67ee2d4428ca41a9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03019-SNAPSHOT.jar",
          "url": "embedded-mas-0.03019-SNAPSHOT.jar",
          "size": 54647,
          "sha512": "3a24e17295930464650b374ba0e2f53b5871fa49594e86f9e05df599235dec1033b8866fc0caedc049e144bb54fbf1217a6888a1a2072d5a8e3a53910f8857f4",
          "sha256": "70344b711d383a40594e345c2aaa00ad0bee7a0e94dcaca6f7e1f519d92cf7f5",
          "sha1": "e746287b256bff2168416f7c4a77ed331fa1a154",
          "md5": "fb8ee366192b2ac67ee2d4428ca41a9c"
        }
      ]
    }
  ]
}
