{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.038003-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038003-SNAPSHOT.jar",
          "url": "embedded-mas-0.038003-SNAPSHOT.jar",
          "size": 74442,
          "sha512": "65de546b4827e1c7f83dda14c94e8db42c68819aec450fb4528870d8f09ffcc81c2285a48e726d166c7b2756786aa10e0a9e1855e9c1747fa20c71b192166a72",
          "sha256": "e0841b1c38e032203a0fee6933514a98180ec4358ba19b072c1448b3f48f492e",
          "sha1": "f6e1e468768c7b01547fa8ea3cdecdd2e82e641b",
          "md5": "160600e011516f98caaba4358a457bb9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038003-SNAPSHOT.jar",
          "url": "embedded-mas-0.038003-SNAPSHOT.jar",
          "size": 74442,
          "sha512": "65de546b4827e1c7f83dda14c94e8db42c68819aec450fb4528870d8f09ffcc81c2285a48e726d166c7b2756786aa10e0a9e1855e9c1747fa20c71b192166a72",
          "sha256": "e0841b1c38e032203a0fee6933514a98180ec4358ba19b072c1448b3f48f492e",
          "sha1": "f6e1e468768c7b01547fa8ea3cdecdd2e82e641b",
          "md5": "160600e011516f98caaba4358a457bb9"
        }
      ]
    }
  ]
}
