{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04609-DEVX",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04609-DEVX.jar",
          "url": "embedded-mas-0.04609-DEVX.jar",
          "size": 69579,
          "sha512": "d6023a87816d32b5f19c3f570f0fc0c0a604e9835e2dc2e49879592e2dc426cd749c0e812a9887fc5d37b7b19885909457ed05fcc414e6e8c292ed2d7a2fc03f",
          "sha256": "6fa2f8f7837632512396e7c0ef734ca4eac722563a4b28aadf5cd17583ada228",
          "sha1": "dd1ca1bc8d52310255ecd6db1fd41001239928c4",
          "md5": "6f092719022a052fac6e20328b6ee817"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04609-DEVX.jar",
          "url": "embedded-mas-0.04609-DEVX.jar",
          "size": 69579,
          "sha512": "d6023a87816d32b5f19c3f570f0fc0c0a604e9835e2dc2e49879592e2dc426cd749c0e812a9887fc5d37b7b19885909457ed05fcc414e6e8c292ed2d7a2fc03f",
          "sha256": "6fa2f8f7837632512396e7c0ef734ca4eac722563a4b28aadf5cd17583ada228",
          "sha1": "dd1ca1bc8d52310255ecd6db1fd41001239928c4",
          "md5": "6f092719022a052fac6e20328b6ee817"
        }
      ]
    }
  ]
}
