{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03301-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03301-SNAPSHOT.jar",
          "url": "embedded-mas-0.03301-SNAPSHOT.jar",
          "size": 62040,
          "sha512": "08f55016052a92c74906f3f947426db66a297d9ca1187c98c6845c01736aea228cec0e71f9011dda7c1e8b1aca556939d3f5031ed1bd4406d9eca44b502b038d",
          "sha256": "3d69601187725f5c0a30ffecda39e7a3a720e9a4591e75ea70d5b1defe63c72e",
          "sha1": "2f27c176cbf4f3f94a48473a8361a33c3825b2c4",
          "md5": "adf85f7b3a9364829b205f06286831f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03301-SNAPSHOT.jar",
          "url": "embedded-mas-0.03301-SNAPSHOT.jar",
          "size": 62040,
          "sha512": "08f55016052a92c74906f3f947426db66a297d9ca1187c98c6845c01736aea228cec0e71f9011dda7c1e8b1aca556939d3f5031ed1bd4406d9eca44b502b038d",
          "sha256": "3d69601187725f5c0a30ffecda39e7a3a720e9a4591e75ea70d5b1defe63c72e",
          "sha1": "2f27c176cbf4f3f94a48473a8361a33c3825b2c4",
          "md5": "adf85f7b3a9364829b205f06286831f1"
        }
      ]
    }
  ]
}
