{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03010-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03010-SNAPSHOT.jar",
          "url": "embedded-mas-0.03010-SNAPSHOT.jar",
          "size": 53596,
          "sha512": "9e2a0321af715b2414eef58e9031cb2de229dcf9ab5a662282e00817489f5ce1f59873f1766e57bce14e1e710d6b4b13eafb4cb170f7e7e43796ae0d5e77bdfb",
          "sha256": "31c57b7449cb977de44deb2b7a5100a167922f1861132e6d6a82b3afc9581685",
          "sha1": "ba6e0a7ac3eadd5f2b61a1dee896af9c4022a209",
          "md5": "e8af33cfbd57cc32ab3b308b3994e706"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03010-SNAPSHOT.jar",
          "url": "embedded-mas-0.03010-SNAPSHOT.jar",
          "size": 53596,
          "sha512": "9e2a0321af715b2414eef58e9031cb2de229dcf9ab5a662282e00817489f5ce1f59873f1766e57bce14e1e710d6b4b13eafb4cb170f7e7e43796ae0d5e77bdfb",
          "sha256": "31c57b7449cb977de44deb2b7a5100a167922f1861132e6d6a82b3afc9581685",
          "sha1": "ba6e0a7ac3eadd5f2b61a1dee896af9c4022a209",
          "md5": "e8af33cfbd57cc32ab3b308b3994e706"
        }
      ]
    }
  ]
}
