{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03020-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03020-SNAPSHOT.jar",
          "url": "embedded-mas-0.03020-SNAPSHOT.jar",
          "size": 54662,
          "sha512": "1cb0904e75c6a9ab4e4d623b01f4b9e88e6e390fb2c75822e4c1ba7b23816c77a3545949890ce0de674a0b1620ec374dadc4c77f4d1d822533c20ee076fc4fc6",
          "sha256": "22328539d0a0c6e8c3880f625639e8052a3f051f0c0cfbd9c094cd52cf547f06",
          "sha1": "12c700ce8746f80d2fe6095e3d2cfc6340a0758a",
          "md5": "3d127a41aa1473944e4c1e5d4a64fd73"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03020-SNAPSHOT.jar",
          "url": "embedded-mas-0.03020-SNAPSHOT.jar",
          "size": 54662,
          "sha512": "1cb0904e75c6a9ab4e4d623b01f4b9e88e6e390fb2c75822e4c1ba7b23816c77a3545949890ce0de674a0b1620ec374dadc4c77f4d1d822533c20ee076fc4fc6",
          "sha256": "22328539d0a0c6e8c3880f625639e8052a3f051f0c0cfbd9c094cd52cf547f06",
          "sha1": "12c700ce8746f80d2fe6095e3d2cfc6340a0758a",
          "md5": "3d127a41aa1473944e4c1e5d4a64fd73"
        }
      ]
    }
  ]
}
