{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271520-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271520-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271520-SNAPSHOT.jar",
          "size": 30966,
          "sha512": "eabea83485a1bea53acfa96321ef400e9b4aa2ca3cabda87a0ef1458cf508664d6d2bf5ee3dde737eb677615e2745b34906a011e3146858abaedb4509c1c0ff5",
          "sha256": "8eeef97177099bd52ceff594ccbe198b751af830c5a6ef497516af4dcaac94cb",
          "sha1": "3ca325296f398c8eccb73c91503f3869db9069aa",
          "md5": "af6c8fe1291e221c7797f65abf79702f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271520-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271520-SNAPSHOT.jar",
          "size": 30966,
          "sha512": "eabea83485a1bea53acfa96321ef400e9b4aa2ca3cabda87a0ef1458cf508664d6d2bf5ee3dde737eb677615e2745b34906a011e3146858abaedb4509c1c0ff5",
          "sha256": "8eeef97177099bd52ceff594ccbe198b751af830c5a6ef497516af4dcaac94cb",
          "sha1": "3ca325296f398c8eccb73c91503f3869db9069aa",
          "md5": "af6c8fe1291e221c7797f65abf79702f"
        }
      ]
    }
  ]
}
