{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04302-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04302-SNAPSHOT.jar",
          "url": "embedded-mas-0.04302-SNAPSHOT.jar",
          "size": 74322,
          "sha512": "4ff307399d228eccf5db55515c9bf8da09a1872249accc0991dd981002ce6baf95a0c7a40852b760fbd5672668b2d28f0ec675f0f85700271f6b6992d578085b",
          "sha256": "31a090e01a7aa39ce8398b1aec8d96c79855933cec4f79eabe21e8680ba85ff0",
          "sha1": "1708ecc712fb437a8ffbd57a0bc68a0d8d2efbb3",
          "md5": "b1596f6ef793e94d7a4ac2daf157aba2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04302-SNAPSHOT.jar",
          "url": "embedded-mas-0.04302-SNAPSHOT.jar",
          "size": 74322,
          "sha512": "4ff307399d228eccf5db55515c9bf8da09a1872249accc0991dd981002ce6baf95a0c7a40852b760fbd5672668b2d28f0ec675f0f85700271f6b6992d578085b",
          "sha256": "31a090e01a7aa39ce8398b1aec8d96c79855933cec4f79eabe21e8680ba85ff0",
          "sha1": "1708ecc712fb437a8ffbd57a0bc68a0d8d2efbb3",
          "md5": "b1596f6ef793e94d7a4ac2daf157aba2"
        }
      ]
    }
  ]
}
