{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.063k-TEMP",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.063k-TEMP.jar",
          "url": "embedded-mas-0.063k-TEMP.jar",
          "size": 102345,
          "sha512": "d3cca745f28e0658e67e9fdd769c96cd35f5e31e3a4df96f54f594c7501dd57a200efab4e299a7f46a61d8a9cc34e1923b51ba992b871d25c88cd43160de91ea",
          "sha256": "c9d5664a015916a6c9eee6fa1d314ac1e742260ed40e422df5284c837cebb766",
          "sha1": "7a348214b5ea63b3c57dc6381ebd358ca9ed5c05",
          "md5": "1d4618dea6b1301adb845f2ef45ada21"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.30"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.063k-TEMP.jar",
          "url": "embedded-mas-0.063k-TEMP.jar",
          "size": 102345,
          "sha512": "d3cca745f28e0658e67e9fdd769c96cd35f5e31e3a4df96f54f594c7501dd57a200efab4e299a7f46a61d8a9cc34e1923b51ba992b871d25c88cd43160de91ea",
          "sha256": "c9d5664a015916a6c9eee6fa1d314ac1e742260ed40e422df5284c837cebb766",
          "sha1": "7a348214b5ea63b3c57dc6381ebd358ca9ed5c05",
          "md5": "1d4618dea6b1301adb845f2ef45ada21"
        }
      ]
    }
  ]
}
