{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03903-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03903-SNAPSHOT.jar",
          "url": "embedded-mas-0.03903-SNAPSHOT.jar",
          "size": 71214,
          "sha512": "ed05f764bf3e3a5225541d8eb6b20254cc9380354fbbb6e06d49cf77856c39a18389f08c11a8b2266c82f2d257bd73aafb6cd49b8c8abc3495132e97f87db1d8",
          "sha256": "9379a3b0480f24b05b5e1b92aa145d31a2ab6c23e4add1698e230fcd02269c4d",
          "sha1": "edd4319874adc8d93d3235f20317af49aa5d3085",
          "md5": "8e3daf280a9489012f87127982ef38b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03903-SNAPSHOT.jar",
          "url": "embedded-mas-0.03903-SNAPSHOT.jar",
          "size": 71214,
          "sha512": "ed05f764bf3e3a5225541d8eb6b20254cc9380354fbbb6e06d49cf77856c39a18389f08c11a8b2266c82f2d257bd73aafb6cd49b8c8abc3495132e97f87db1d8",
          "sha256": "9379a3b0480f24b05b5e1b92aa145d31a2ab6c23e4add1698e230fcd02269c4d",
          "sha1": "edd4319874adc8d93d3235f20317af49aa5d3085",
          "md5": "8e3daf280a9489012f87127982ef38b6"
        }
      ]
    }
  ]
}
