{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03605-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03605-SNAPSHOT.jar",
          "url": "embedded-mas-0.03605-SNAPSHOT.jar",
          "size": 64170,
          "sha512": "3eae1bd19c89ed3bd251ae3e96b5d7ff50d8b0d4beb8623d4b86c4b4daa7d6b563520b202c25a3db23da13156ac3cf3ed81d678b753cee006b003cb04b690e7e",
          "sha256": "424ddce2b242a9624bf29f5c94889074f1ced13009b6d0120e0266bd1823797f",
          "sha1": "2c14f1ca39e08c6f08e5c1853f80cd810c620695",
          "md5": "392355c727e9c84509d833cc6f8f04d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03605-SNAPSHOT.jar",
          "url": "embedded-mas-0.03605-SNAPSHOT.jar",
          "size": 64170,
          "sha512": "3eae1bd19c89ed3bd251ae3e96b5d7ff50d8b0d4beb8623d4b86c4b4daa7d6b563520b202c25a3db23da13156ac3cf3ed81d678b753cee006b003cb04b690e7e",
          "sha256": "424ddce2b242a9624bf29f5c94889074f1ced13009b6d0120e0266bd1823797f",
          "sha1": "2c14f1ca39e08c6f08e5c1853f80cd810c620695",
          "md5": "392355c727e9c84509d833cc6f8f04d6"
        }
      ]
    }
  ]
}
