{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.038005-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038005-SNAPSHOT.jar",
          "url": "embedded-mas-0.038005-SNAPSHOT.jar",
          "size": 74512,
          "sha512": "3c29dd2546fd14f2d1bbf6a8a7d98861474d699ef447eba6a1488a7f24a907ef9d95d85d25ba3667e4c5f5c160c56d1c3ddafba6547862a89bc37340926e73c8",
          "sha256": "3a654ee1eb7b6b15783f5d09e8a4a74768f3592822a358314daf784dfc6adf0a",
          "sha1": "d5f4319b5a2c35121263d329e4213ef8b6025379",
          "md5": "cc5e0ccee97f491724daac828deb3055"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038005-SNAPSHOT.jar",
          "url": "embedded-mas-0.038005-SNAPSHOT.jar",
          "size": 74512,
          "sha512": "3c29dd2546fd14f2d1bbf6a8a7d98861474d699ef447eba6a1488a7f24a907ef9d95d85d25ba3667e4c5f5c160c56d1c3ddafba6547862a89bc37340926e73c8",
          "sha256": "3a654ee1eb7b6b15783f5d09e8a4a74768f3592822a358314daf784dfc6adf0a",
          "sha1": "d5f4319b5a2c35121263d329e4213ef8b6025379",
          "md5": "cc5e0ccee97f491724daac828deb3055"
        }
      ]
    }
  ]
}
