{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271533-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271533-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271533-SNAPSHOT.jar",
          "size": 31209,
          "sha512": "15d3311129fa0d72ec585ffad66b3507ccd569f622c01c22500a1ca80e188b81b4c8e1365b8ae8c67156ee0f487c09baae2d2ad6c5436e1c2c6bd31a7de484da",
          "sha256": "146f79663329ab9c19f72c072da36968410e9a32989430492605e45f5e43f2b2",
          "sha1": "1740e26bad0af0f2d34dd0dbe71072fc92cccb21",
          "md5": "e6079880c7cce4f5360d00568c6fd3fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271533-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271533-SNAPSHOT.jar",
          "size": 31209,
          "sha512": "15d3311129fa0d72ec585ffad66b3507ccd569f622c01c22500a1ca80e188b81b4c8e1365b8ae8c67156ee0f487c09baae2d2ad6c5436e1c2c6bd31a7de484da",
          "sha256": "146f79663329ab9c19f72c072da36968410e9a32989430492605e45f5e43f2b2",
          "sha1": "1740e26bad0af0f2d34dd0dbe71072fc92cccb21",
          "md5": "e6079880c7cce4f5360d00568c6fd3fb"
        }
      ]
    }
  ]
}
