{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271405-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271405-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271405-SNAPSHOT.jar",
          "size": 30582,
          "sha512": "5f4694de28009ef7c63eba2b21be45c110ed78a2c0cac8681b643f5549350c0f8e422298748004eebf9bbc585dd6fb52eb355c4236aae67bfa7d64a289ede852",
          "sha256": "c342c4b3b5febfd26f77fed616ce13eaed413837d8083c986a4ca2eb9dae20a7",
          "sha1": "8e4bb17a8466c53edebc4a6e60a17b68876046c5",
          "md5": "76cd4eb9769512a211bbbf62a45514ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271405-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271405-SNAPSHOT.jar",
          "size": 30582,
          "sha512": "5f4694de28009ef7c63eba2b21be45c110ed78a2c0cac8681b643f5549350c0f8e422298748004eebf9bbc585dd6fb52eb355c4236aae67bfa7d64a289ede852",
          "sha256": "c342c4b3b5febfd26f77fed616ce13eaed413837d8083c986a4ca2eb9dae20a7",
          "sha1": "8e4bb17a8466c53edebc4a6e60a17b68876046c5",
          "md5": "76cd4eb9769512a211bbbf62a45514ec"
        }
      ]
    }
  ]
}
