{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04610-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04610-SNAPSHOT.jar",
          "url": "embedded-mas-0.04610-SNAPSHOT.jar",
          "size": 69066,
          "sha512": "03aefea911c49c820ab5f5ece1a6654ded1842d2a5144eb98e6e17eca482fade22fbbd5721287531d76492d02a3890e938f72a99cfe1a292a6d8b1ba645b5ac5",
          "sha256": "1332702a62b4e35275768da644d0d3b518d846d4ddb31800ec096d49440a39f5",
          "sha1": "cd7c132618af14950e41d587bf3fc7c8aa8e8c29",
          "md5": "c1f9040e54a31050401e265e4f74219b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04610-SNAPSHOT.jar",
          "url": "embedded-mas-0.04610-SNAPSHOT.jar",
          "size": 69066,
          "sha512": "03aefea911c49c820ab5f5ece1a6654ded1842d2a5144eb98e6e17eca482fade22fbbd5721287531d76492d02a3890e938f72a99cfe1a292a6d8b1ba645b5ac5",
          "sha256": "1332702a62b4e35275768da644d0d3b518d846d4ddb31800ec096d49440a39f5",
          "sha1": "cd7c132618af14950e41d587bf3fc7c8aa8e8c29",
          "md5": "c1f9040e54a31050401e265e4f74219b"
        }
      ]
    }
  ]
}
