{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271514-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271514-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271514-SNAPSHOT.jar",
          "size": 30725,
          "sha512": "f5556af0e619fed9655afae62cf4319d18262bc36f011e4ac16dda60895f21229ef5a39abb823a1d060b5be3898dc29d1d566473cde51ca77b41121913a703dc",
          "sha256": "336e62b0c6001270baaf84a432241055c50e9bd23c1b43dc371eafca643d9608",
          "sha1": "651052a556ee3c569169103c3f6f0a6fff3ffa5c",
          "md5": "e005734aada47472c0da00ad8c91bcd6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271514-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271514-SNAPSHOT.jar",
          "size": 30725,
          "sha512": "f5556af0e619fed9655afae62cf4319d18262bc36f011e4ac16dda60895f21229ef5a39abb823a1d060b5be3898dc29d1d566473cde51ca77b41121913a703dc",
          "sha256": "336e62b0c6001270baaf84a432241055c50e9bd23c1b43dc371eafca643d9608",
          "sha1": "651052a556ee3c569169103c3f6f0a6fff3ffa5c",
          "md5": "e005734aada47472c0da00ad8c91bcd6"
        }
      ]
    }
  ]
}
