{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04678-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04678-DEV.jar",
          "url": "embedded-mas-0.04678-DEV.jar",
          "size": 70770,
          "sha512": "946e8892112bdab35766c96e985acc35555a041bd7362c2aa67dc94d6b0d0731da6ec2cc5d3e063b5c17ba475a872eab10b4572e24de8d3f058f9c871ce6acfd",
          "sha256": "6e01a40229c77bc2726c96719f684950ee02d87cd1f27c6537daf5a63d860f24",
          "sha1": "99f14aa0bd92aac4450dc8cc3cece1f15840cdb5",
          "md5": "cc0dbec1c8cf70cdf7d2ec56923fd3b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04678-DEV.jar",
          "url": "embedded-mas-0.04678-DEV.jar",
          "size": 70770,
          "sha512": "946e8892112bdab35766c96e985acc35555a041bd7362c2aa67dc94d6b0d0731da6ec2cc5d3e063b5c17ba475a872eab10b4572e24de8d3f058f9c871ce6acfd",
          "sha256": "6e01a40229c77bc2726c96719f684950ee02d87cd1f27c6537daf5a63d860f24",
          "sha1": "99f14aa0bd92aac4450dc8cc3cece1f15840cdb5",
          "md5": "cc0dbec1c8cf70cdf7d2ec56923fd3b5"
        }
      ]
    }
  ]
}
