{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03104-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03104-SNAPSHOT.jar",
          "url": "embedded-mas-0.03104-SNAPSHOT.jar",
          "size": 63512,
          "sha512": "cd018d559e60b29d357c3588584295a321f84b435903c686fe1cfde27d59776237cd2e465a4aeaac64a47ea5a9eb83bd209d64966ca5b06363772864e96e5ac7",
          "sha256": "15667d2f5d85fe8d5cd21095fe6d63cb29271dabc985bd195954fe5d73176e16",
          "sha1": "ec11f4d44d96d7b3355e5be52e31901494ab5915",
          "md5": "1194411e2c4212f8bf61d8242f84af98"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03104-SNAPSHOT.jar",
          "url": "embedded-mas-0.03104-SNAPSHOT.jar",
          "size": 63512,
          "sha512": "cd018d559e60b29d357c3588584295a321f84b435903c686fe1cfde27d59776237cd2e465a4aeaac64a47ea5a9eb83bd209d64966ca5b06363772864e96e5ac7",
          "sha256": "15667d2f5d85fe8d5cd21095fe6d63cb29271dabc985bd195954fe5d73176e16",
          "sha1": "ec11f4d44d96d7b3355e5be52e31901494ab5915",
          "md5": "1194411e2c4212f8bf61d8242f84af98"
        }
      ]
    }
  ]
}
