{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271510-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271510-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271510-SNAPSHOT.jar",
          "size": 30578,
          "sha512": "5691acc0d7c7147e2e9d5716bd864adbc869706a18dc9fd5545f690a62a6c03ba898c61c0db80dc2eabcd40ba53fee18a636f8f12cd07edccb5bca4207743588",
          "sha256": "d7403522267617efc6995f335a4756618cdaf14008db768da4ed74b8cc083629",
          "sha1": "b1c7764a30f61371d361c1bfef6109e54f393b33",
          "md5": "31315bdca0ca6e3a22f18f7a6f12b7f3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271510-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271510-SNAPSHOT.jar",
          "size": 30578,
          "sha512": "5691acc0d7c7147e2e9d5716bd864adbc869706a18dc9fd5545f690a62a6c03ba898c61c0db80dc2eabcd40ba53fee18a636f8f12cd07edccb5bca4207743588",
          "sha256": "d7403522267617efc6995f335a4756618cdaf14008db768da4ed74b8cc083629",
          "sha1": "b1c7764a30f61371d361c1bfef6109e54f393b33",
          "md5": "31315bdca0ca6e3a22f18f7a6f12b7f3"
        }
      ]
    }
  ]
}
