{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04617-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04617-SNAPSHOT.jar",
          "url": "embedded-mas-0.04617-SNAPSHOT.jar",
          "size": 69413,
          "sha512": "518af1480898a70037b4139e3feb624c5c6ef71e0381f622f0ccd324c8b591b2b5532e967168c100c464e683467f17de59d8dba7007a767b3c2fc18109e562a6",
          "sha256": "2982fca6a62c10a1ccaca98c11aa8c9e2da917c73fc8f3061ad8c01719dd7c12",
          "sha1": "ee0748b833671e3b5c83e20993e61adc374883b1",
          "md5": "4245c0fbdb39a14d6be472a4daae4308"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04617-SNAPSHOT.jar",
          "url": "embedded-mas-0.04617-SNAPSHOT.jar",
          "size": 69413,
          "sha512": "518af1480898a70037b4139e3feb624c5c6ef71e0381f622f0ccd324c8b591b2b5532e967168c100c464e683467f17de59d8dba7007a767b3c2fc18109e562a6",
          "sha256": "2982fca6a62c10a1ccaca98c11aa8c9e2da917c73fc8f3061ad8c01719dd7c12",
          "sha1": "ee0748b833671e3b5c83e20993e61adc374883b1",
          "md5": "4245c0fbdb39a14d6be472a4daae4308"
        }
      ]
    }
  ]
}
