{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271515-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271515-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271515-SNAPSHOT.jar",
          "size": 30914,
          "sha512": "fad869c1d75bee3ff9e1f93d80dbbd50519f5e14389cab69ffd8ab34c8056ce384c1ce669099fcdfc661df332e47b8cb4e87ce297a16e783ed113deb27f1b3e1",
          "sha256": "dc085ae483dd2a82e9909c481f7af368a4c3060f616d9c473c29cfaf8552e8ba",
          "sha1": "d843f7334a7f5d1c9e35e0a91f2daf10b44785c3",
          "md5": "3937bbe067fe9ee384a03180e968adab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271515-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271515-SNAPSHOT.jar",
          "size": 30914,
          "sha512": "fad869c1d75bee3ff9e1f93d80dbbd50519f5e14389cab69ffd8ab34c8056ce384c1ce669099fcdfc661df332e47b8cb4e87ce297a16e783ed113deb27f1b3e1",
          "sha256": "dc085ae483dd2a82e9909c481f7af368a4c3060f616d9c473c29cfaf8552e8ba",
          "sha1": "d843f7334a7f5d1c9e35e0a91f2daf10b44785c3",
          "md5": "3937bbe067fe9ee384a03180e968adab"
        }
      ]
    }
  ]
}
