{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03034-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03034-SNAPSHOT.jar",
          "url": "embedded-mas-0.03034-SNAPSHOT.jar",
          "size": 61623,
          "sha512": "6038a5d5838a79360c5e16a9a44c5d962161db5123c7e46f40d8f4f8cffd9bb960853c1e2ab6640ea13fcac26c7a3f12b0be44c9dab276070e0acd5046886a2d",
          "sha256": "47f9369b3fc3097d59c30b242017b7eda8658dfc3575fd20a5e58dc8e1d92d11",
          "sha1": "08367ff4120708dc27676ede084657e6d7d2416f",
          "md5": "b60c6e3312cf59d6bb7cbbc9432f976f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03034-SNAPSHOT.jar",
          "url": "embedded-mas-0.03034-SNAPSHOT.jar",
          "size": 61623,
          "sha512": "6038a5d5838a79360c5e16a9a44c5d962161db5123c7e46f40d8f4f8cffd9bb960853c1e2ab6640ea13fcac26c7a3f12b0be44c9dab276070e0acd5046886a2d",
          "sha256": "47f9369b3fc3097d59c30b242017b7eda8658dfc3575fd20a5e58dc8e1d92d11",
          "sha1": "08367ff4120708dc27676ede084657e6d7d2416f",
          "md5": "b60c6e3312cf59d6bb7cbbc9432f976f"
        }
      ]
    }
  ]
}
