{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.02801-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02801-SNAPSHOT.jar",
          "url": "embedded-mas-0.02801-SNAPSHOT.jar",
          "size": 30551,
          "sha512": "f66b98f06f90ab4a7f94e4fb5f5958bcbbdbaecfe1fd31fa53242525ea510b0c391d51d5744dec8a6d7b03f799758e4f7afc4e495698806ca4b2701128fe6255",
          "sha256": "5b9ef40a6dba8c7caa5d3499aaf4c816bd623c15fb738973cc6d428046b29f3c",
          "sha1": "2a5402129a8f345c4223986398ef94f2e785575f",
          "md5": "ba37a8ea2846c9e5171b5d5b0795d828"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02801-SNAPSHOT.jar",
          "url": "embedded-mas-0.02801-SNAPSHOT.jar",
          "size": 30551,
          "sha512": "f66b98f06f90ab4a7f94e4fb5f5958bcbbdbaecfe1fd31fa53242525ea510b0c391d51d5744dec8a6d7b03f799758e4f7afc4e495698806ca4b2701128fe6255",
          "sha256": "5b9ef40a6dba8c7caa5d3499aaf4c816bd623c15fb738973cc6d428046b29f3c",
          "sha1": "2a5402129a8f345c4223986398ef94f2e785575f",
          "md5": "ba37a8ea2846c9e5171b5d5b0795d828"
        }
      ]
    }
  ]
}
