{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03039-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03039-SNAPSHOT.jar",
          "url": "embedded-mas-0.03039-SNAPSHOT.jar",
          "size": 61955,
          "sha512": "5d95203a7f3197679f69c82fcc219689b341c372a4c5d63bcb40ec52fa72ecff3a58b932786badaeab3461ebf2bd379e2c3a043460e118814e0c102cfc322f1f",
          "sha256": "676156c1e41190216b39312566d04beed57d18a1f0fe27ca8db0e44e905b1171",
          "sha1": "3414f45431bdeef1d0cb83f1ba2b04824c26d714",
          "md5": "84cb8664af0273cc179cb40c11d0c625"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03039-SNAPSHOT.jar",
          "url": "embedded-mas-0.03039-SNAPSHOT.jar",
          "size": 61955,
          "sha512": "5d95203a7f3197679f69c82fcc219689b341c372a4c5d63bcb40ec52fa72ecff3a58b932786badaeab3461ebf2bd379e2c3a043460e118814e0c102cfc322f1f",
          "sha256": "676156c1e41190216b39312566d04beed57d18a1f0fe27ca8db0e44e905b1171",
          "sha1": "3414f45431bdeef1d0cb83f1ba2b04824c26d714",
          "md5": "84cb8664af0273cc179cb40c11d0c625"
        }
      ]
    }
  ]
}
