{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.029-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.029-SNAPSHOT.jar",
          "url": "embedded-mas-0.029-SNAPSHOT.jar",
          "size": 30551,
          "sha512": "07dbe6c5e9046c1f1d98ab005fe1d5ca99c5973dcb7f381112c9fb5de42931d727c600fcd1abcf2bc7ae1e1b04466e762e21c8e45f51af94dbd9ce6cce10d422",
          "sha256": "1995cfa2043dbafee376557b7a8e7360c9db8f3250ed24b44e387ed0e4382715",
          "sha1": "36289718e2f4136fd27f619a06b4fc14c667c766",
          "md5": "ba3c2d1cb30bd244c05ede533893a925"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.029-SNAPSHOT.jar",
          "url": "embedded-mas-0.029-SNAPSHOT.jar",
          "size": 30551,
          "sha512": "07dbe6c5e9046c1f1d98ab005fe1d5ca99c5973dcb7f381112c9fb5de42931d727c600fcd1abcf2bc7ae1e1b04466e762e21c8e45f51af94dbd9ce6cce10d422",
          "sha256": "1995cfa2043dbafee376557b7a8e7360c9db8f3250ed24b44e387ed0e4382715",
          "sha1": "36289718e2f4136fd27f619a06b4fc14c667c766",
          "md5": "ba3c2d1cb30bd244c05ede533893a925"
        }
      ]
    }
  ]
}
