{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04675-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04675-DEV.jar",
          "url": "embedded-mas-0.04675-DEV.jar",
          "size": 70800,
          "sha512": "00dafea9afe302b08674d12a619b447b8fae0621d4812ae39f884ac6ab6b02ff322aa04bae997d7ea20cdb25312cf0987ed0153b25dc004fafbb5aebd4f51a11",
          "sha256": "9d1b62bcd86141a2d66a5cd9fa33615781cc135ab624496270e09043bb68bfac",
          "sha1": "5392c405556e9afee81bea1314e91ca92c215fec",
          "md5": "1947c738ba86628375bd8d998213e13e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04675-DEV.jar",
          "url": "embedded-mas-0.04675-DEV.jar",
          "size": 70800,
          "sha512": "00dafea9afe302b08674d12a619b447b8fae0621d4812ae39f884ac6ab6b02ff322aa04bae997d7ea20cdb25312cf0987ed0153b25dc004fafbb5aebd4f51a11",
          "sha256": "9d1b62bcd86141a2d66a5cd9fa33615781cc135ab624496270e09043bb68bfac",
          "sha1": "5392c405556e9afee81bea1314e91ca92c215fec",
          "md5": "1947c738ba86628375bd8d998213e13e"
        }
      ]
    }
  ]
}
