{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0471-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0471-SNAPSHOT.jar",
          "url": "embedded-mas-0.0471-SNAPSHOT.jar",
          "size": 73638,
          "sha512": "242e21eadf1e4cb48739f3265518e05fe439050569477841bd69cf2ddd147d8dfc51fff224fe0b6a2c0ce3209dcd4978e7356221476c0665a6e1796699bbd37d",
          "sha256": "e7d84583620f75a3f44ab3e2f1c0a0de3524bbca19163983bb07a06f5461afbf",
          "sha1": "1f1d7fc184b97f1e9e546adbc5024c5decd126de",
          "md5": "09602f96876753a8b3c729c97dab13de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0471-SNAPSHOT.jar",
          "url": "embedded-mas-0.0471-SNAPSHOT.jar",
          "size": 73638,
          "sha512": "242e21eadf1e4cb48739f3265518e05fe439050569477841bd69cf2ddd147d8dfc51fff224fe0b6a2c0ce3209dcd4978e7356221476c0665a6e1796699bbd37d",
          "sha256": "e7d84583620f75a3f44ab3e2f1c0a0de3524bbca19163983bb07a06f5461afbf",
          "sha1": "1f1d7fc184b97f1e9e546adbc5024c5decd126de",
          "md5": "09602f96876753a8b3c729c97dab13de"
        }
      ]
    }
  ]
}
