{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03036-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03036-SNAPSHOT.jar",
          "url": "embedded-mas-0.03036-SNAPSHOT.jar",
          "size": 61626,
          "sha512": "9bba7e0a9bab4eefc18993f459b3201b75e862695eacad54fa8816a155ff57117094a31637e53ca2678d02edd2ce7a2a27e7dc1729d793e54cde12087de04731",
          "sha256": "b3e282a9c130e8fd54be54040901b39e08850a1b2bd50cbfd8134bfc3c6932a0",
          "sha1": "0a1583701dbfb20fcc3d75f3954b692c6e0bf89d",
          "md5": "d12b40a17de71825d27194a04f2a4566"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03036-SNAPSHOT.jar",
          "url": "embedded-mas-0.03036-SNAPSHOT.jar",
          "size": 61626,
          "sha512": "9bba7e0a9bab4eefc18993f459b3201b75e862695eacad54fa8816a155ff57117094a31637e53ca2678d02edd2ce7a2a27e7dc1729d793e54cde12087de04731",
          "sha256": "b3e282a9c130e8fd54be54040901b39e08850a1b2bd50cbfd8134bfc3c6932a0",
          "sha1": "0a1583701dbfb20fcc3d75f3954b692c6e0bf89d",
          "md5": "d12b40a17de71825d27194a04f2a4566"
        }
      ]
    }
  ]
}
