{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03035-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03035-SNAPSHOT.jar",
          "url": "embedded-mas-0.03035-SNAPSHOT.jar",
          "size": 61623,
          "sha512": "5e8109122c3762d43360652d80aa87d3b838e34ef768c88b26e5cc28b9c3cbfaf901f7bd5707779f4316192652459d8cdca23d4546be4a03b355ff40ff1ddb91",
          "sha256": "ddd8e8aff2d270731ab82377ecd7d109146eb10574c817d3ac2243349fda97f9",
          "sha1": "764839af55e5e1b8144b92d5218fa58217e6db4d",
          "md5": "0640410cf40dd5ddf4254f01889a2801"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03035-SNAPSHOT.jar",
          "url": "embedded-mas-0.03035-SNAPSHOT.jar",
          "size": 61623,
          "sha512": "5e8109122c3762d43360652d80aa87d3b838e34ef768c88b26e5cc28b9c3cbfaf901f7bd5707779f4316192652459d8cdca23d4546be4a03b355ff40ff1ddb91",
          "sha256": "ddd8e8aff2d270731ab82377ecd7d109146eb10574c817d3ac2243349fda97f9",
          "sha1": "764839af55e5e1b8144b92d5218fa58217e6db4d",
          "md5": "0640410cf40dd5ddf4254f01889a2801"
        }
      ]
    }
  ]
}
