{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03058-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03058-SNAPSHOT.jar",
          "url": "embedded-mas-0.03058-SNAPSHOT.jar",
          "size": 60380,
          "sha512": "d53d2e21d5440d4e743be6b24240b986060b9139aef097dddbed2e0df521c64e9636f3d33373a16a4eb87ca580e4878ebc1df210f557b214571cd43fa7b6fe5f",
          "sha256": "7165619a606e9bf70c8de385df54f3d6a433cc0110ebda2b8d3c50821f31ed3f",
          "sha1": "860739664b56f4ccdbd3ae3397459cc3dcea6c6d",
          "md5": "2b52386e930476e4bdb4e8f8eac04a2e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03058-SNAPSHOT.jar",
          "url": "embedded-mas-0.03058-SNAPSHOT.jar",
          "size": 60380,
          "sha512": "d53d2e21d5440d4e743be6b24240b986060b9139aef097dddbed2e0df521c64e9636f3d33373a16a4eb87ca580e4878ebc1df210f557b214571cd43fa7b6fe5f",
          "sha256": "7165619a606e9bf70c8de385df54f3d6a433cc0110ebda2b8d3c50821f31ed3f",
          "sha1": "860739664b56f4ccdbd3ae3397459cc3dcea6c6d",
          "md5": "2b52386e930476e4bdb4e8f8eac04a2e"
        }
      ]
    }
  ]
}
