{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271522-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271522-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271522-SNAPSHOT.jar",
          "size": 30959,
          "sha512": "3b7162f21d4cdce766c979689e9767f40db8db8ed5db71c328d59bf4658a103e0acdf757f612e1c1eaf7c5b2f0acc5b7690b3449f7c323ac1e186b3ffa4b11f4",
          "sha256": "594cad13af334d8ff2c530b2b98f308ffae1bdb85d16dcd69c770559c48e760e",
          "sha1": "fec479eb37a68fcce7eb731d08521a4cb754b96a",
          "md5": "832527fd8acc26ebfa1b1acf938810fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271522-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271522-SNAPSHOT.jar",
          "size": 30959,
          "sha512": "3b7162f21d4cdce766c979689e9767f40db8db8ed5db71c328d59bf4658a103e0acdf757f612e1c1eaf7c5b2f0acc5b7690b3449f7c323ac1e186b3ffa4b11f4",
          "sha256": "594cad13af334d8ff2c530b2b98f308ffae1bdb85d16dcd69c770559c48e760e",
          "sha1": "fec479eb37a68fcce7eb731d08521a4cb754b96a",
          "md5": "832527fd8acc26ebfa1b1acf938810fa"
        }
      ]
    }
  ]
}
