{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.038004-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038004-SNAPSHOT.jar",
          "url": "embedded-mas-0.038004-SNAPSHOT.jar",
          "size": 74512,
          "sha512": "b6673fc8e81faf0eb6ddc759155131f93f21b64559eb26cb01814bef15a4866c405fc6e496fba51abd9f50dd3b51fa1f8a97d82bf981cc700aefb5ae3393c6e4",
          "sha256": "1e311f0f10915151212e7a04acc36f08719b512f7ab1856c7f5778552f66c414",
          "sha1": "51eeecd0ec591506759a8b86447743f177bd2a87",
          "md5": "458674ccf775ca01658a6a9fbb5603f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038004-SNAPSHOT.jar",
          "url": "embedded-mas-0.038004-SNAPSHOT.jar",
          "size": 74512,
          "sha512": "b6673fc8e81faf0eb6ddc759155131f93f21b64559eb26cb01814bef15a4866c405fc6e496fba51abd9f50dd3b51fa1f8a97d82bf981cc700aefb5ae3393c6e4",
          "sha256": "1e311f0f10915151212e7a04acc36f08719b512f7ab1856c7f5778552f66c414",
          "sha1": "51eeecd0ec591506759a8b86447743f177bd2a87",
          "md5": "458674ccf775ca01658a6a9fbb5603f4"
        }
      ]
    }
  ]
}
