{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03607-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03607-SNAPSHOT.jar",
          "url": "embedded-mas-0.03607-SNAPSHOT.jar",
          "size": 65354,
          "sha512": "5d5fdec8625d282faa934cfb85998a63eb9b8e38f484645be35c1523b5f1966232eeedd1a97f9d9ccc410c08bbfc70cdf154bab3c68f6cc25ca9d3d12ca38a10",
          "sha256": "bc9e28c6b5ef5004deb5208312fd10c3da49cf9121310b9df807c76d115227ff",
          "sha1": "f91d1062c9bfd61bba6bbcb3a6715552ae3cf260",
          "md5": "66e7d19edebf7d2000796ccaed0efa84"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03607-SNAPSHOT.jar",
          "url": "embedded-mas-0.03607-SNAPSHOT.jar",
          "size": 65354,
          "sha512": "5d5fdec8625d282faa934cfb85998a63eb9b8e38f484645be35c1523b5f1966232eeedd1a97f9d9ccc410c08bbfc70cdf154bab3c68f6cc25ca9d3d12ca38a10",
          "sha256": "bc9e28c6b5ef5004deb5208312fd10c3da49cf9121310b9df807c76d115227ff",
          "sha1": "f91d1062c9bfd61bba6bbcb3a6715552ae3cf260",
          "md5": "66e7d19edebf7d2000796ccaed0efa84"
        }
      ]
    }
  ]
}
