{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.037-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.037-SNAPSHOT.jar",
          "url": "embedded-mas-0.037-SNAPSHOT.jar",
          "size": 65816,
          "sha512": "2167dc8fa95ac59a84a095eb75ad3089898d2ea231f7e1f3e633f9cffc9834ac71d0e92f5fe1368d9a0c7f05a87e8eb8950861fd03b35f6069ac1ac6d4326347",
          "sha256": "d1e99a2f7cc27c54fa4476d4b2fcfe2801585d2fe2ab9cbb21ab71a0dd855620",
          "sha1": "19e3310e5633cfc86581037159f485b55423e445",
          "md5": "ece5e4d23dac1cdca9e799ea1471d298"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.037-SNAPSHOT.jar",
          "url": "embedded-mas-0.037-SNAPSHOT.jar",
          "size": 65816,
          "sha512": "2167dc8fa95ac59a84a095eb75ad3089898d2ea231f7e1f3e633f9cffc9834ac71d0e92f5fe1368d9a0c7f05a87e8eb8950861fd03b35f6069ac1ac6d4326347",
          "sha256": "d1e99a2f7cc27c54fa4476d4b2fcfe2801585d2fe2ab9cbb21ab71a0dd855620",
          "sha1": "19e3310e5633cfc86581037159f485b55423e445",
          "md5": "ece5e4d23dac1cdca9e799ea1471d298"
        }
      ]
    }
  ]
}
