{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04301-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04301-SNAPSHOT.jar",
          "url": "embedded-mas-0.04301-SNAPSHOT.jar",
          "size": 72579,
          "sha512": "1e833b6142f80cad190c71e44a74815aeaa179acf0a7fdb4f47b3954f3bc8ba6fb87fca0ea52acc31bfa9bcfdf95869cb418b6bae66e6bf4d49483fffc6b6083",
          "sha256": "205df5fca1cf690b6eb0d08b32fc83f6a26ca3902f263f2b78ada829819317a2",
          "sha1": "2256b20df07ef3a97591f95d9b586fca7eb2670e",
          "md5": "c6cb0e2f7394afc78eb58226a7180e9d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04301-SNAPSHOT.jar",
          "url": "embedded-mas-0.04301-SNAPSHOT.jar",
          "size": 72579,
          "sha512": "1e833b6142f80cad190c71e44a74815aeaa179acf0a7fdb4f47b3954f3bc8ba6fb87fca0ea52acc31bfa9bcfdf95869cb418b6bae66e6bf4d49483fffc6b6083",
          "sha256": "205df5fca1cf690b6eb0d08b32fc83f6a26ca3902f263f2b78ada829819317a2",
          "sha1": "2256b20df07ef3a97591f95d9b586fca7eb2670e",
          "md5": "c6cb0e2f7394afc78eb58226a7180e9d"
        }
      ]
    }
  ]
}
