{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03501-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03501-SNAPSHOT.jar",
          "url": "embedded-mas-0.03501-SNAPSHOT.jar",
          "size": 64181,
          "sha512": "c6bacacb5297b119d56c8fded408362e1666e8fe32bfaadaa9e55de70d9a8240bcbad197d9f9f395a601b84d05354867f2172dd95de71606b522d6a207ff2d5d",
          "sha256": "b5ef8f644fb131ccf500a8e08370f01bc2960a1c3daaffa673141ed286f6f019",
          "sha1": "2e481627c700174d97575699255762a8a749eba4",
          "md5": "e9e64618bd88657848aea88f6143a392"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03501-SNAPSHOT.jar",
          "url": "embedded-mas-0.03501-SNAPSHOT.jar",
          "size": 64181,
          "sha512": "c6bacacb5297b119d56c8fded408362e1666e8fe32bfaadaa9e55de70d9a8240bcbad197d9f9f395a601b84d05354867f2172dd95de71606b522d6a207ff2d5d",
          "sha256": "b5ef8f644fb131ccf500a8e08370f01bc2960a1c3daaffa673141ed286f6f019",
          "sha1": "2e481627c700174d97575699255762a8a749eba4",
          "md5": "e9e64618bd88657848aea88f6143a392"
        }
      ]
    }
  ]
}
