{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271517-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271517-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271517-SNAPSHOT.jar",
          "size": 30491,
          "sha512": "338548f7408068cb50fb954bf502742fe95e292c8ca7e0ddd61068caf7d4a9054cc162cf6c14da90e6b8552d15f8030f7bd8d960e16f9f72ad340364a8d05728",
          "sha256": "f58e75368024f36ce292ae8cd38a0f3ce831a8cd044ec0c67759366a0b43169a",
          "sha1": "9ea2d8447329f0928456f0896656f4ab4bfec073",
          "md5": "baff7e521dd1682127d8ece6306ebe01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271517-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271517-SNAPSHOT.jar",
          "size": 30491,
          "sha512": "338548f7408068cb50fb954bf502742fe95e292c8ca7e0ddd61068caf7d4a9054cc162cf6c14da90e6b8552d15f8030f7bd8d960e16f9f72ad340364a8d05728",
          "sha256": "f58e75368024f36ce292ae8cd38a0f3ce831a8cd044ec0c67759366a0b43169a",
          "sha1": "9ea2d8447329f0928456f0896656f4ab4bfec073",
          "md5": "baff7e521dd1682127d8ece6306ebe01"
        }
      ]
    }
  ]
}
