{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04652-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04652-DEV.jar",
          "url": "embedded-mas-0.04652-DEV.jar",
          "size": 69982,
          "sha512": "c6d075644436c454bd0fcad9e6e1fbe8e9d1d3b70963caf7e59cd48e96d64f36f5ccec38ab81a9623ed777e25d391ba26d22d5d4b8d0fdc25bc10b67d8de4381",
          "sha256": "95e981426836894907fddea170aa28677035a54087049c71aae253e84a8059a8",
          "sha1": "e61a7d09f23f77ac45895a0e90b083bcc605e2c3",
          "md5": "c2662f8fc8ef769c3422fc1d9bebe995"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04652-DEV.jar",
          "url": "embedded-mas-0.04652-DEV.jar",
          "size": 69982,
          "sha512": "c6d075644436c454bd0fcad9e6e1fbe8e9d1d3b70963caf7e59cd48e96d64f36f5ccec38ab81a9623ed777e25d391ba26d22d5d4b8d0fdc25bc10b67d8de4381",
          "sha256": "95e981426836894907fddea170aa28677035a54087049c71aae253e84a8059a8",
          "sha1": "e61a7d09f23f77ac45895a0e90b083bcc605e2c3",
          "md5": "c2662f8fc8ef769c3422fc1d9bebe995"
        }
      ]
    }
  ]
}
