{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04637-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04637-DEV.jar",
          "url": "embedded-mas-0.04637-DEV.jar",
          "size": 77416,
          "sha512": "8e7cf4110f706356a1c02ad3cc0a21a20d9dec472d9da09917252e7ea843a87971ed80d0b9b9dd6fd64cb89bb6b9d274ae194434edc1e45f36eade26a2464669",
          "sha256": "4c891b2eb3ec860be310d3e8e0931e5cc2a6af7f9f9c4a11cce186295a627bb2",
          "sha1": "30676714bc3b54b0e24491d2c4147416809f2cdb",
          "md5": "4c75a636ceba06e43fd969b3a9f81fed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04637-DEV.jar",
          "url": "embedded-mas-0.04637-DEV.jar",
          "size": 77416,
          "sha512": "8e7cf4110f706356a1c02ad3cc0a21a20d9dec472d9da09917252e7ea843a87971ed80d0b9b9dd6fd64cb89bb6b9d274ae194434edc1e45f36eade26a2464669",
          "sha256": "4c891b2eb3ec860be310d3e8e0931e5cc2a6af7f9f9c4a11cce186295a627bb2",
          "sha1": "30676714bc3b54b0e24491d2c4147416809f2cdb",
          "md5": "4c75a636ceba06e43fd969b3a9f81fed"
        }
      ]
    }
  ]
}
