{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271509-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271509-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271509-SNAPSHOT.jar",
          "size": 30452,
          "sha512": "68ac9c162f16828783ff6262db2b6a30a47e8bf34e1eb1c094225726cc6b5eac2d3724b8a0144218f98f77af9fde2bd55e752202f76b141e47d01c22bf03610d",
          "sha256": "a3fae56d71a3ddf26c42f6738fca04e3d1aa3912da3084a5da63199b26e3850e",
          "sha1": "bf2f4f404fd79aa1906b0fa0e58fcf137084d48f",
          "md5": "5b1996ab063ccd77d1836412095e1274"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271509-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271509-SNAPSHOT.jar",
          "size": 30452,
          "sha512": "68ac9c162f16828783ff6262db2b6a30a47e8bf34e1eb1c094225726cc6b5eac2d3724b8a0144218f98f77af9fde2bd55e752202f76b141e47d01c22bf03610d",
          "sha256": "a3fae56d71a3ddf26c42f6738fca04e3d1aa3912da3084a5da63199b26e3850e",
          "sha1": "bf2f4f404fd79aa1906b0fa0e58fcf137084d48f",
          "md5": "5b1996ab063ccd77d1836412095e1274"
        }
      ]
    }
  ]
}
