{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.034-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.034-SNAPSHOT.jar",
          "url": "embedded-mas-0.034-SNAPSHOT.jar",
          "size": 61739,
          "sha512": "7821f900bdbc52be887a0c020992dba38b26ee55d3311b14c735f264d881094c1a6ac0dba4a36cfa76132ad00334f6db1582824621919766ddda79babbce1a3a",
          "sha256": "d08764c0b14072cfb0163689471bf11094056719e74beb133da08079071662bc",
          "sha1": "d2fe8a433c4cd2d4d6a9465294a87b488fd7cbc3",
          "md5": "936e6781854abde04b825bd5ab3eb955"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.034-SNAPSHOT.jar",
          "url": "embedded-mas-0.034-SNAPSHOT.jar",
          "size": 61739,
          "sha512": "7821f900bdbc52be887a0c020992dba38b26ee55d3311b14c735f264d881094c1a6ac0dba4a36cfa76132ad00334f6db1582824621919766ddda79babbce1a3a",
          "sha256": "d08764c0b14072cfb0163689471bf11094056719e74beb133da08079071662bc",
          "sha1": "d2fe8a433c4cd2d4d6a9465294a87b488fd7cbc3",
          "md5": "936e6781854abde04b825bd5ab3eb955"
        }
      ]
    }
  ]
}
