{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04604-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04604-SNAPSHOT.jar",
          "url": "embedded-mas-0.04604-SNAPSHOT.jar",
          "size": 68827,
          "sha512": "493a862a365991ad6bce34e83a2c5bb07925820851fa6fbb9e3010c14dd04e4e5b0ac9d9f39fe8466603f6c2c413c498120c59a25548b7c82cf3c581c2b4940e",
          "sha256": "57f4567f0948cfe18f70d19d07db94cc9e1f38ba7676a9e06b5500a094f24e76",
          "sha1": "c56c0b45499aad091e5f9790bcee6aab1ae4a470",
          "md5": "840ea12ec0756806298f01f9a9faf70d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04604-SNAPSHOT.jar",
          "url": "embedded-mas-0.04604-SNAPSHOT.jar",
          "size": 68827,
          "sha512": "493a862a365991ad6bce34e83a2c5bb07925820851fa6fbb9e3010c14dd04e4e5b0ac9d9f39fe8466603f6c2c413c498120c59a25548b7c82cf3c581c2b4940e",
          "sha256": "57f4567f0948cfe18f70d19d07db94cc9e1f38ba7676a9e06b5500a094f24e76",
          "sha1": "c56c0b45499aad091e5f9790bcee6aab1ae4a470",
          "md5": "840ea12ec0756806298f01f9a9faf70d"
        }
      ]
    }
  ]
}
