{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.042-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.042-SNAPSHOT.jar",
          "url": "embedded-mas-0.042-SNAPSHOT.jar",
          "size": 72481,
          "sha512": "d0c71c4a6d2589f46e890253549a8e96e55803e467c97a43cb758d9ecb6992da8f4f555095282a7a23d6355802f09eca5af03a0117cb7e931dfd18d4cbdb7b34",
          "sha256": "d7e1bc03c624c8cd1adcab291668120a35823155c8620d1d9db8e718f19daef4",
          "sha1": "8f3a5f81a0a35027297448c281b32e20bd72ebbe",
          "md5": "cd44b16bd92771438b08c84b9d114f01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.042-SNAPSHOT.jar",
          "url": "embedded-mas-0.042-SNAPSHOT.jar",
          "size": 72481,
          "sha512": "d0c71c4a6d2589f46e890253549a8e96e55803e467c97a43cb758d9ecb6992da8f4f555095282a7a23d6355802f09eca5af03a0117cb7e931dfd18d4cbdb7b34",
          "sha256": "d7e1bc03c624c8cd1adcab291668120a35823155c8620d1d9db8e718f19daef4",
          "sha1": "8f3a5f81a0a35027297448c281b32e20bd72ebbe",
          "md5": "cd44b16bd92771438b08c84b9d114f01"
        }
      ]
    }
  ]
}
