{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03108-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03108-SNAPSHOT.jar",
          "url": "embedded-mas-0.03108-SNAPSHOT.jar",
          "size": 63573,
          "sha512": "aa189d16f10d7f6c6697f6534b85001669d627b0039eb31902926afe3c19948a241c0ea56f067e31112464b0c144694fd39da851af4731063269b192517555bd",
          "sha256": "6ff48b638f3538074a656a7671a117aeb0d33261f376c7d127fcd266c486958e",
          "sha1": "41ba5d3a236a470fd45dbd9b7384f07d341e7dda",
          "md5": "ae77f28def599cee888458b50bfcff64"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03108-SNAPSHOT.jar",
          "url": "embedded-mas-0.03108-SNAPSHOT.jar",
          "size": 63573,
          "sha512": "aa189d16f10d7f6c6697f6534b85001669d627b0039eb31902926afe3c19948a241c0ea56f067e31112464b0c144694fd39da851af4731063269b192517555bd",
          "sha256": "6ff48b638f3538074a656a7671a117aeb0d33261f376c7d127fcd266c486958e",
          "sha1": "41ba5d3a236a470fd45dbd9b7384f07d341e7dda",
          "md5": "ae77f28def599cee888458b50bfcff64"
        }
      ]
    }
  ]
}
