{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271525-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271525-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271525-SNAPSHOT.jar",
          "size": 30697,
          "sha512": "56dd21557fff0c593bb40a2a0f8240072757895f1dc2dc0140cc1fbbd9da712d0480d7d8df8e4293c4259f9a17078005acb81ab640bccb2f6fdf3da96cb47f68",
          "sha256": "eebad77f0eb23b22d59b3993ddb96023287618c506186dd0b829c418e0fb41a8",
          "sha1": "af18cd2eb696f366c4cba945e00db2bbd15b4312",
          "md5": "89a077df06b9ef035cc2e67a5d80306d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271525-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271525-SNAPSHOT.jar",
          "size": 30697,
          "sha512": "56dd21557fff0c593bb40a2a0f8240072757895f1dc2dc0140cc1fbbd9da712d0480d7d8df8e4293c4259f9a17078005acb81ab640bccb2f6fdf3da96cb47f68",
          "sha256": "eebad77f0eb23b22d59b3993ddb96023287618c506186dd0b829c418e0fb41a8",
          "sha1": "af18cd2eb696f366c4cba945e00db2bbd15b4312",
          "md5": "89a077df06b9ef035cc2e67a5d80306d"
        }
      ]
    }
  ]
}
