{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271538-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271538-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271538-SNAPSHOT.jar",
          "size": 30791,
          "sha512": "e65befd926f42a56f5b2c58deeb62faf80231e76af9cd34454508ae06331769c199dfe802717a50f08442aa306ce77d7d00169008727a1d039b5f7441188068c",
          "sha256": "ad244d3a33ab0bc2d9e7383ae68e34e35e7bee5ab875ffc339dab25c1c45b2a0",
          "sha1": "fb9aed191aa52afd076448a321447808231285ab",
          "md5": "0c2717d9fdb931d6f2e268c5f81d97cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271538-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271538-SNAPSHOT.jar",
          "size": 30791,
          "sha512": "e65befd926f42a56f5b2c58deeb62faf80231e76af9cd34454508ae06331769c199dfe802717a50f08442aa306ce77d7d00169008727a1d039b5f7441188068c",
          "sha256": "ad244d3a33ab0bc2d9e7383ae68e34e35e7bee5ab875ffc339dab25c1c45b2a0",
          "sha1": "fb9aed191aa52afd076448a321447808231285ab",
          "md5": "0c2717d9fdb931d6f2e268c5f81d97cf"
        }
      ]
    }
  ]
}
