{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03205-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03205-SNAPSHOT.jar",
          "url": "embedded-mas-0.03205-SNAPSHOT.jar",
          "size": 62290,
          "sha512": "d71fb2e84135ad7d974c7b99c5dfed10711d9a211ff28c6ac4f451086a367e647fed289cad7b03aac38fad6a8a7adda044d685cd5544b51069d8a914e4b74b7f",
          "sha256": "f11b32b8b8eef2aa08aa74619e7aebf5c8ad251d08923e9c61d619edc562714b",
          "sha1": "2a9aac5f8ba272917bf19254602b8f66ba4b2aaf",
          "md5": "08f2e5186e2c3f9e0d7a175934e3c24f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03205-SNAPSHOT.jar",
          "url": "embedded-mas-0.03205-SNAPSHOT.jar",
          "size": 62290,
          "sha512": "d71fb2e84135ad7d974c7b99c5dfed10711d9a211ff28c6ac4f451086a367e647fed289cad7b03aac38fad6a8a7adda044d685cd5544b51069d8a914e4b74b7f",
          "sha256": "f11b32b8b8eef2aa08aa74619e7aebf5c8ad251d08923e9c61d619edc562714b",
          "sha1": "2a9aac5f8ba272917bf19254602b8f66ba4b2aaf",
          "md5": "08f2e5186e2c3f9e0d7a175934e3c24f"
        }
      ]
    }
  ]
}
