{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04611-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04611-SNAPSHOT.jar",
          "url": "embedded-mas-0.04611-SNAPSHOT.jar",
          "size": 69067,
          "sha512": "f946fcd5bc433ad106dcf3f655708ad847e0bef6ce80bfffb2db512f68b38e5aa9c317c31d4d6b489be373b5ef1eb31fd5a6cdb0a477de1a65a45d98ccd7efcb",
          "sha256": "dfb33f869b0b376b02866da8323a965d8cd8ba3ff63ff04b54f81015f6c5e71d",
          "sha1": "ab96817ec8d0ed7e97091e32c647d1b435f2d212",
          "md5": "0cd5db7d0d42a14a3f0a57a7090f522b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04611-SNAPSHOT.jar",
          "url": "embedded-mas-0.04611-SNAPSHOT.jar",
          "size": 69067,
          "sha512": "f946fcd5bc433ad106dcf3f655708ad847e0bef6ce80bfffb2db512f68b38e5aa9c317c31d4d6b489be373b5ef1eb31fd5a6cdb0a477de1a65a45d98ccd7efcb",
          "sha256": "dfb33f869b0b376b02866da8323a965d8cd8ba3ff63ff04b54f81015f6c5e71d",
          "sha1": "ab96817ec8d0ed7e97091e32c647d1b435f2d212",
          "md5": "0cd5db7d0d42a14a3f0a57a7090f522b"
        }
      ]
    }
  ]
}
