{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.038006-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038006-SNAPSHOT.jar",
          "url": "embedded-mas-0.038006-SNAPSHOT.jar",
          "size": 74443,
          "sha512": "72fe85ecaddb69fb129c53a91c9cce254844118c17997141772329705afb46bf24bdd0f2f60a3bfca83baf70a5c18e1793580765fdd94dd844f19a25a361ee63",
          "sha256": "06f172f863c777b5cf52aff783383de506f7ff74acaaa0e726991a130e6131b5",
          "sha1": "79733540aeb09617fa96b7c55f99f2355265e71f",
          "md5": "466db07c78b0b06b841e3a632dfba87d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038006-SNAPSHOT.jar",
          "url": "embedded-mas-0.038006-SNAPSHOT.jar",
          "size": 74443,
          "sha512": "72fe85ecaddb69fb129c53a91c9cce254844118c17997141772329705afb46bf24bdd0f2f60a3bfca83baf70a5c18e1793580765fdd94dd844f19a25a361ee63",
          "sha256": "06f172f863c777b5cf52aff783383de506f7ff74acaaa0e726991a130e6131b5",
          "sha1": "79733540aeb09617fa96b7c55f99f2355265e71f",
          "md5": "466db07c78b0b06b841e3a632dfba87d"
        }
      ]
    }
  ]
}
