{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271512-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271512-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271512-SNAPSHOT.jar",
          "size": 30591,
          "sha512": "55bb1a460513b83fc0c00632a038e1a20792cec8d9a462739abdd5be96a5df58df2a6eeddf4b1a4605d978682a151b1d99fe436f2a5f3c3ea678ef493778b790",
          "sha256": "ddfef7a030d0efb251eee3c9fd91d8a7d0aa70c3709d0b1b0e161c174ef1c163",
          "sha1": "cfb112e7a935fe866dfc81cbf35e59a251253e67",
          "md5": "aac5fb552b840621a77a7484f2b33156"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271512-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271512-SNAPSHOT.jar",
          "size": 30591,
          "sha512": "55bb1a460513b83fc0c00632a038e1a20792cec8d9a462739abdd5be96a5df58df2a6eeddf4b1a4605d978682a151b1d99fe436f2a5f3c3ea678ef493778b790",
          "sha256": "ddfef7a030d0efb251eee3c9fd91d8a7d0aa70c3709d0b1b0e161c174ef1c163",
          "sha1": "cfb112e7a935fe866dfc81cbf35e59a251253e67",
          "md5": "aac5fb552b840621a77a7484f2b33156"
        }
      ]
    }
  ]
}
