{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03038-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03038-SNAPSHOT.jar",
          "url": "embedded-mas-0.03038-SNAPSHOT.jar",
          "size": 61930,
          "sha512": "efb19210a11324c08564874eb33a3b8317be5651e64267a47cb3e50a6737eb07db822210a5af6b7ea053a6fe366201133b956f0cadf372d01d60c4025e371653",
          "sha256": "e9630565f1dde11ada4f4e33f424027ec0b432693feaa0c104022430ccf40817",
          "sha1": "010a4ffb7f384e45ac3f4954e2016462393c2dbd",
          "md5": "a656af61ccaf5d6aaabca18a02c97fd5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03038-SNAPSHOT.jar",
          "url": "embedded-mas-0.03038-SNAPSHOT.jar",
          "size": 61930,
          "sha512": "efb19210a11324c08564874eb33a3b8317be5651e64267a47cb3e50a6737eb07db822210a5af6b7ea053a6fe366201133b956f0cadf372d01d60c4025e371653",
          "sha256": "e9630565f1dde11ada4f4e33f424027ec0b432693feaa0c104022430ccf40817",
          "sha1": "010a4ffb7f384e45ac3f4954e2016462393c2dbd",
          "md5": "a656af61ccaf5d6aaabca18a02c97fd5"
        }
      ]
    }
  ]
}
