{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.038009-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038009-SNAPSHOT.jar",
          "url": "embedded-mas-0.038009-SNAPSHOT.jar",
          "size": 74528,
          "sha512": "79a4fd3f34573f010161b8ecbced3a82fdbebbbd3706931d08f6a0ac5e801f84e610281a8e9fbd973ef50408bb7d2985666968956e333944222c5a46b74e5f3c",
          "sha256": "6b498abe02d63257704c41ccabf57faa0f3267c875e007f42b9cdb1ff2a0fcc2",
          "sha1": "9fbe4da868cfdbf9e587c3fb446d75cf0807dc56",
          "md5": "d63afa1d3ec027603260f564f4a90167"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038009-SNAPSHOT.jar",
          "url": "embedded-mas-0.038009-SNAPSHOT.jar",
          "size": 74528,
          "sha512": "79a4fd3f34573f010161b8ecbced3a82fdbebbbd3706931d08f6a0ac5e801f84e610281a8e9fbd973ef50408bb7d2985666968956e333944222c5a46b74e5f3c",
          "sha256": "6b498abe02d63257704c41ccabf57faa0f3267c875e007f42b9cdb1ff2a0fcc2",
          "sha1": "9fbe4da868cfdbf9e587c3fb446d75cf0807dc56",
          "md5": "d63afa1d3ec027603260f564f4a90167"
        }
      ]
    }
  ]
}
