{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03604-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03604-SNAPSHOT.jar",
          "url": "embedded-mas-0.03604-SNAPSHOT.jar",
          "size": 64134,
          "sha512": "24405afa4c8014b6d5fb480df472bc8d51e0208f393abd1935ac2f2921d5e023034740619ea260bbe36ff441976a148852a2a35d4e1d2f44299223dee04249f7",
          "sha256": "1dcc2bef6628a8d908207f51560c3b4ef9982a79ac67c38053306dd975e3094a",
          "sha1": "7f5b6fde5353fcdc44cb5bf798b814337c6d58c7",
          "md5": "5e8f6eb97389d4fbcb90fda9d4efc063"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03604-SNAPSHOT.jar",
          "url": "embedded-mas-0.03604-SNAPSHOT.jar",
          "size": 64134,
          "sha512": "24405afa4c8014b6d5fb480df472bc8d51e0208f393abd1935ac2f2921d5e023034740619ea260bbe36ff441976a148852a2a35d4e1d2f44299223dee04249f7",
          "sha256": "1dcc2bef6628a8d908207f51560c3b4ef9982a79ac67c38053306dd975e3094a",
          "sha1": "7f5b6fde5353fcdc44cb5bf798b814337c6d58c7",
          "md5": "5e8f6eb97389d4fbcb90fda9d4efc063"
        }
      ]
    }
  ]
}
