{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0270607-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0270607-SNAPSHOT.jar",
          "url": "embedded-mas-0.0270607-SNAPSHOT.jar",
          "size": 29966,
          "sha512": "e151184ac2270381e878c523568aef2605d5b3d0483e5a8471c7177f372d5d3dbd4a9d9d28df6fda85582e15186bd3b25d07614a7135d7415b1090f167c65c99",
          "sha256": "b15956c40c9d7e593eb4520dcd80c4d051cb53123acaa979ecf873a132311011",
          "sha1": "d6beee6ccbceec8b454cdbc49ebb5d278e9a1698",
          "md5": "ac7a6ca0df4edc6d467ad8dd49957a74"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0270607-SNAPSHOT.jar",
          "url": "embedded-mas-0.0270607-SNAPSHOT.jar",
          "size": 29966,
          "sha512": "e151184ac2270381e878c523568aef2605d5b3d0483e5a8471c7177f372d5d3dbd4a9d9d28df6fda85582e15186bd3b25d07614a7135d7415b1090f167c65c99",
          "sha256": "b15956c40c9d7e593eb4520dcd80c4d051cb53123acaa979ecf873a132311011",
          "sha1": "d6beee6ccbceec8b454cdbc49ebb5d278e9a1698",
          "md5": "ac7a6ca0df4edc6d467ad8dd49957a74"
        }
      ]
    }
  ]
}
