{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03206-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03206-SNAPSHOT.jar",
          "url": "embedded-mas-0.03206-SNAPSHOT.jar",
          "size": 62298,
          "sha512": "0093835c4808e2321706f53d2c9eb776d954bac1413b7f0fda033b08228c4d224eb84c2bf6feb119ac42b454d40e2177cbd6c37ca20a7dcd07cc37cfc8c8ea62",
          "sha256": "8fcb906d9086eca4f60cd1b6fa042b9c6f3c8284b5482b21ee2564fe220c5fd0",
          "sha1": "668bc4b870e7fc4a12bc2841836782844cd82cfe",
          "md5": "b90f6c5dfcc5440dd74dc939cde449f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03206-SNAPSHOT.jar",
          "url": "embedded-mas-0.03206-SNAPSHOT.jar",
          "size": 62298,
          "sha512": "0093835c4808e2321706f53d2c9eb776d954bac1413b7f0fda033b08228c4d224eb84c2bf6feb119ac42b454d40e2177cbd6c37ca20a7dcd07cc37cfc8c8ea62",
          "sha256": "8fcb906d9086eca4f60cd1b6fa042b9c6f3c8284b5482b21ee2564fe220c5fd0",
          "sha1": "668bc4b870e7fc4a12bc2841836782844cd82cfe",
          "md5": "b90f6c5dfcc5440dd74dc939cde449f6"
        }
      ]
    }
  ]
}
