{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271527-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271527-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271527-SNAPSHOT.jar",
          "size": 30817,
          "sha512": "375314ee57c66cad5cb72ec0b860030d01e8d2bf50b03f503b07a1390affe743c365ff13ce5363e277556e2e6fff8198135c644640501d21cad5957dfd614f29",
          "sha256": "34719bc98c847c6141684590303e4f092f8ac44930574931591d488ea109c8ff",
          "sha1": "eaedd37c233fbc02affdc953d1f255ab0138b37a",
          "md5": "0122ed59ccc6d27703c42ae9f28ba877"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271527-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271527-SNAPSHOT.jar",
          "size": 30817,
          "sha512": "375314ee57c66cad5cb72ec0b860030d01e8d2bf50b03f503b07a1390affe743c365ff13ce5363e277556e2e6fff8198135c644640501d21cad5957dfd614f29",
          "sha256": "34719bc98c847c6141684590303e4f092f8ac44930574931591d488ea109c8ff",
          "sha1": "eaedd37c233fbc02affdc953d1f255ab0138b37a",
          "md5": "0122ed59ccc6d27703c42ae9f28ba877"
        }
      ]
    }
  ]
}
