{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271508-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271508-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271508-SNAPSHOT.jar",
          "size": 30159,
          "sha512": "5ce24e1bbe29d409b2efe93c8935906661ac8bc356fb434b0abd77ef952b3847e2a25580fd6da4203c4c37de6f75923a45c878539506b2d24728596f8b4a5906",
          "sha256": "6abc99ead797d4251c89cf7164e986ece7e0d3be8c5d46b398b6823dfff5e3f3",
          "sha1": "6e4133f1dce7ae6ee5237c8781b6eb55a5890604",
          "md5": "febd1655da0e3b8e4de3720ee538afcd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271508-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271508-SNAPSHOT.jar",
          "size": 30159,
          "sha512": "5ce24e1bbe29d409b2efe93c8935906661ac8bc356fb434b0abd77ef952b3847e2a25580fd6da4203c4c37de6f75923a45c878539506b2d24728596f8b4a5906",
          "sha256": "6abc99ead797d4251c89cf7164e986ece7e0d3be8c5d46b398b6823dfff5e3f3",
          "sha1": "6e4133f1dce7ae6ee5237c8781b6eb55a5890604",
          "md5": "febd1655da0e3b8e4de3720ee538afcd"
        }
      ]
    }
  ]
}
