{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.038013-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038013-SNAPSHOT.jar",
          "url": "embedded-mas-0.038013-SNAPSHOT.jar",
          "size": 74507,
          "sha512": "645f8c49e2280d61b45777a2fb406b509432a73c857ef63bfeb6706a3cb930f35e08c190c24b151acb3f4cdc2ea0c02e0538603bfe056c3bca37ac6b464332e0",
          "sha256": "730bbd8ef313eaeecf29732962f66a89e80f14e36d849e7d2f1999c8885b9a44",
          "sha1": "9ad6a025870279f280b1db91be762fa62e17299a",
          "md5": "288b8d1d417f9a5e6134f00ea927f86d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038013-SNAPSHOT.jar",
          "url": "embedded-mas-0.038013-SNAPSHOT.jar",
          "size": 74507,
          "sha512": "645f8c49e2280d61b45777a2fb406b509432a73c857ef63bfeb6706a3cb930f35e08c190c24b151acb3f4cdc2ea0c02e0538603bfe056c3bca37ac6b464332e0",
          "sha256": "730bbd8ef313eaeecf29732962f66a89e80f14e36d849e7d2f1999c8885b9a44",
          "sha1": "9ad6a025870279f280b1db91be762fa62e17299a",
          "md5": "288b8d1d417f9a5e6134f00ea927f86d"
        }
      ]
    }
  ]
}
