{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03904-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03904-SNAPSHOT.jar",
          "url": "embedded-mas-0.03904-SNAPSHOT.jar",
          "size": 71212,
          "sha512": "264a41aae9214564a60aa395209e24945729769f5f04982014e27df61a268ab107bef2893abd8e8a501fd0412775b2aa344062cc1d1a7884d1513b88c88ffbdc",
          "sha256": "422af53ed3db99cdc3c1c7b0feba13d63245c04e9ea4521803504e9567575550",
          "sha1": "bce8b7f5cf30930f0fa8ba91eccb4c5ae5b3aa41",
          "md5": "5ae6b7c9cee6cf2bcfadbfb1cfb91bdb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03904-SNAPSHOT.jar",
          "url": "embedded-mas-0.03904-SNAPSHOT.jar",
          "size": 71212,
          "sha512": "264a41aae9214564a60aa395209e24945729769f5f04982014e27df61a268ab107bef2893abd8e8a501fd0412775b2aa344062cc1d1a7884d1513b88c88ffbdc",
          "sha256": "422af53ed3db99cdc3c1c7b0feba13d63245c04e9ea4521803504e9567575550",
          "sha1": "bce8b7f5cf30930f0fa8ba91eccb4c5ae5b3aa41",
          "md5": "5ae6b7c9cee6cf2bcfadbfb1cfb91bdb"
        }
      ]
    }
  ]
}
