{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04634-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04634-DEV.jar",
          "url": "embedded-mas-0.04634-DEV.jar",
          "size": 77328,
          "sha512": "419b21b3b653d328c8fb11ede9f5f10ba458dad1848f4232b398916ea2ad1f2190d7d7761308b9480b15e6e12a1f73857ca1e672c1900ba10c66aad79db50af3",
          "sha256": "09e1ba8c74b1e05253fa3fb8c0a2ead049bb0fde9a4576407bf25e507a432a70",
          "sha1": "01cb2b52407e4582f7a1b7a79f3193074ef17339",
          "md5": "93afecd2ac5ae401f80929ae94d705c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04634-DEV.jar",
          "url": "embedded-mas-0.04634-DEV.jar",
          "size": 77328,
          "sha512": "419b21b3b653d328c8fb11ede9f5f10ba458dad1848f4232b398916ea2ad1f2190d7d7761308b9480b15e6e12a1f73857ca1e672c1900ba10c66aad79db50af3",
          "sha256": "09e1ba8c74b1e05253fa3fb8c0a2ead049bb0fde9a4576407bf25e507a432a70",
          "sha1": "01cb2b52407e4582f7a1b7a79f3193074ef17339",
          "md5": "93afecd2ac5ae401f80929ae94d705c3"
        }
      ]
    }
  ]
}
