{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03011-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03011-SNAPSHOT.jar",
          "url": "embedded-mas-0.03011-SNAPSHOT.jar",
          "size": 53622,
          "sha512": "4e0b0728110b2e09d9600855e8762ae54c6bc544ae7cdb260c785842fe123a50078ff696d6ebea20948fc9ae0f4e7069223069db12a24d1ba3a4c7b539ee9207",
          "sha256": "26e2ead3c541b65eb3956dbe9e4cbfdb0ac3a076585962a6533e6fea9f3c2454",
          "sha1": "4aff45c3970627f474fe19c47580f24812f170f3",
          "md5": "b88e0d8dafee6a6e0e0abca03e695c5f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03011-SNAPSHOT.jar",
          "url": "embedded-mas-0.03011-SNAPSHOT.jar",
          "size": 53622,
          "sha512": "4e0b0728110b2e09d9600855e8762ae54c6bc544ae7cdb260c785842fe123a50078ff696d6ebea20948fc9ae0f4e7069223069db12a24d1ba3a4c7b539ee9207",
          "sha256": "26e2ead3c541b65eb3956dbe9e4cbfdb0ac3a076585962a6533e6fea9f3c2454",
          "sha1": "4aff45c3970627f474fe19c47580f24812f170f3",
          "md5": "b88e0d8dafee6a6e0e0abca03e695c5f"
        }
      ]
    }
  ]
}
