{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03052-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03052-SNAPSHOT.jar",
          "url": "embedded-mas-0.03052-SNAPSHOT.jar",
          "size": 60550,
          "sha512": "552c63e45622a0eacf48f4f633f768cf8719432f4b39301b31cab3e4c2f1368719548530d02e2299fcde7d958145032e878e9637a4783b54064a8625e989b658",
          "sha256": "4eccf8b75273651641ab34567a0b47b7dded0409b2156d971bef5c9162c515e0",
          "sha1": "2d37bc271b6757de3836841d606ed2f8e4d2f490",
          "md5": "46129a5e7d8965870354f890d58e4697"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03052-SNAPSHOT.jar",
          "url": "embedded-mas-0.03052-SNAPSHOT.jar",
          "size": 60550,
          "sha512": "552c63e45622a0eacf48f4f633f768cf8719432f4b39301b31cab3e4c2f1368719548530d02e2299fcde7d958145032e878e9637a4783b54064a8625e989b658",
          "sha256": "4eccf8b75273651641ab34567a0b47b7dded0409b2156d971bef5c9162c515e0",
          "sha1": "2d37bc271b6757de3836841d606ed2f8e4d2f490",
          "md5": "46129a5e7d8965870354f890d58e4697"
        }
      ]
    }
  ]
}
