{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.041-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.041-SNAPSHOT.jar",
          "url": "embedded-mas-0.041-SNAPSHOT.jar",
          "size": 72645,
          "sha512": "d1a5952681907fecd2ae3045d62d162200c1dfab3ad5592fe248fcbc69876acfd0cb65cab509b76da14277b4ce30de0c185015cc7a2d656cb415813141c1b8db",
          "sha256": "32e1042f48f78dfd498a0b1f959ad14252d1c1d022428ab5c6a5f3e4b7910cf2",
          "sha1": "c2e4ebdaaa5f88d2a6550bcf972736361f1a299e",
          "md5": "744f63421324d2562b81b93de4b9dca9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.041-SNAPSHOT.jar",
          "url": "embedded-mas-0.041-SNAPSHOT.jar",
          "size": 72645,
          "sha512": "d1a5952681907fecd2ae3045d62d162200c1dfab3ad5592fe248fcbc69876acfd0cb65cab509b76da14277b4ce30de0c185015cc7a2d656cb415813141c1b8db",
          "sha256": "32e1042f48f78dfd498a0b1f959ad14252d1c1d022428ab5c6a5f3e4b7910cf2",
          "sha1": "c2e4ebdaaa5f88d2a6550bcf972736361f1a299e",
          "md5": "744f63421324d2562b81b93de4b9dca9"
        }
      ]
    }
  ]
}
