{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03001-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03001-SNAPSHOT.jar",
          "url": "embedded-mas-0.03001-SNAPSHOT.jar",
          "size": 51674,
          "sha512": "59a5319d97296067b8348ec93c956de40b730f4316f08f4dc66648288940759fb8789845ccf6341bb4b1d337eccf0f4c1e5efdc42c0fa840b193b9e3daa3042d",
          "sha256": "b97baf81991a28e415d68ebd0b57cbbd1d244a0e3e3e9d64450404006f26f6a2",
          "sha1": "5579b8c20563cb2d210d099e155c9dce46c6d96d",
          "md5": "1a217c091a9890e24a869554d7978380"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03001-SNAPSHOT.jar",
          "url": "embedded-mas-0.03001-SNAPSHOT.jar",
          "size": 51674,
          "sha512": "59a5319d97296067b8348ec93c956de40b730f4316f08f4dc66648288940759fb8789845ccf6341bb4b1d337eccf0f4c1e5efdc42c0fa840b193b9e3daa3042d",
          "sha256": "b97baf81991a28e415d68ebd0b57cbbd1d244a0e3e3e9d64450404006f26f6a2",
          "sha1": "5579b8c20563cb2d210d099e155c9dce46c6d96d",
          "md5": "1a217c091a9890e24a869554d7978380"
        }
      ]
    }
  ]
}
