{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04201-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04201-SNAPSHOT.jar",
          "url": "embedded-mas-0.04201-SNAPSHOT.jar",
          "size": 72566,
          "sha512": "a58b6ff8473d7a543fc8f808ed0ffaa13facd852cd902d9c2fb7f2fefa5d842be3ee02abfe7c14e49e4c0d65d13ffd9aee9481fe9c91eed48c2f561ae718ede4",
          "sha256": "fe5a7c8d8877785a36189c979697546db14c9e5b4d7d8f34a04473a0eb3a24cd",
          "sha1": "feaaaec7c3f82170aa1a55315178bd6b56d9eb59",
          "md5": "8a369b5a02a1c43776868cd7e8f5ed88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04201-SNAPSHOT.jar",
          "url": "embedded-mas-0.04201-SNAPSHOT.jar",
          "size": 72566,
          "sha512": "a58b6ff8473d7a543fc8f808ed0ffaa13facd852cd902d9c2fb7f2fefa5d842be3ee02abfe7c14e49e4c0d65d13ffd9aee9481fe9c91eed48c2f561ae718ede4",
          "sha256": "fe5a7c8d8877785a36189c979697546db14c9e5b4d7d8f34a04473a0eb3a24cd",
          "sha1": "feaaaec7c3f82170aa1a55315178bd6b56d9eb59",
          "md5": "8a369b5a02a1c43776868cd7e8f5ed88"
        }
      ]
    }
  ]
}
