{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271540-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271540-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271540-SNAPSHOT.jar",
          "size": 30673,
          "sha512": "dc591df446df8037e1a27421994dec9c87b43ab29032949e2b04f8a08be120500abf79489dec50db5fbf39f3ecc8c73ca75909bedf53ccb8b861bf157d23c4a8",
          "sha256": "77be581ddac00bb0b1451d5e4c61556bf27bfc48c9f1f73ee8af484acedede5c",
          "sha1": "40d05a443ef902d45b7e9027ab957cb5fa1e946a",
          "md5": "c491631f26fd3d7842abbdd9433e4eb2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271540-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271540-SNAPSHOT.jar",
          "size": 30673,
          "sha512": "dc591df446df8037e1a27421994dec9c87b43ab29032949e2b04f8a08be120500abf79489dec50db5fbf39f3ecc8c73ca75909bedf53ccb8b861bf157d23c4a8",
          "sha256": "77be581ddac00bb0b1451d5e4c61556bf27bfc48c9f1f73ee8af484acedede5c",
          "sha1": "40d05a443ef902d45b7e9027ab957cb5fa1e946a",
          "md5": "c491631f26fd3d7842abbdd9433e4eb2"
        }
      ]
    }
  ]
}
