{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271540-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271540-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271540-SNAPSHOT.jar",
          "size": 30590,
          "sha512": "7b50df4144e7ccf8932356f882d60cd0f5c19cd8fd3c45314c7614e1e6d0fa18ce04fea01cd32bf333a2e1410158cd6af7c7d2a14a4d91286a590ea8a23588fc",
          "sha256": "5f30e2343377ebc3ed6df331032968d95bf9b78283594bb9edeb5ab19c95a2a3",
          "sha1": "b5890c3948fd7f559613a51b8c073cbf3863d9ae",
          "md5": "c6319600bc50adb3f2eb3bd94916aa0d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271540-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271540-SNAPSHOT.jar",
          "size": 30590,
          "sha512": "7b50df4144e7ccf8932356f882d60cd0f5c19cd8fd3c45314c7614e1e6d0fa18ce04fea01cd32bf333a2e1410158cd6af7c7d2a14a4d91286a590ea8a23588fc",
          "sha256": "5f30e2343377ebc3ed6df331032968d95bf9b78283594bb9edeb5ab19c95a2a3",
          "sha1": "b5890c3948fd7f559613a51b8c073cbf3863d9ae",
          "md5": "c6319600bc50adb3f2eb3bd94916aa0d"
        }
      ]
    }
  ]
}
