{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271403-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271403-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271403-SNAPSHOT.jar",
          "size": 30583,
          "sha512": "8744fb8dc01f39ed01b3685028be7266b97858c950502f443e6f8a0acded8a5e1bc9fd97b705e930fd05b89af7b42b064a9b17f85eca52cdef942ec4149c9d81",
          "sha256": "9149189ba0d85f7301c199a8f13c9c201053135c268dd3e6f124bf5cf21b960a",
          "sha1": "8764974d5df40f4e8970ac32f43370d7197b7c65",
          "md5": "fc548b823f71ef32de71d6090ea819a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271403-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271403-SNAPSHOT.jar",
          "size": 30583,
          "sha512": "8744fb8dc01f39ed01b3685028be7266b97858c950502f443e6f8a0acded8a5e1bc9fd97b705e930fd05b89af7b42b064a9b17f85eca52cdef942ec4149c9d81",
          "sha256": "9149189ba0d85f7301c199a8f13c9c201053135c268dd3e6f124bf5cf21b960a",
          "sha1": "8764974d5df40f4e8970ac32f43370d7197b7c65",
          "md5": "fc548b823f71ef32de71d6090ea819a0"
        }
      ]
    }
  ]
}
