{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04631-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04631-DEV.jar",
          "url": "embedded-mas-0.04631-DEV.jar",
          "size": 76992,
          "sha512": "7e3d9c1a7553d9d106835ff44ebb8570e5cde07e905ae41624877b68b483b6f73d3315afab0b82204dca8a367629c8710c21b71686d0f4fa0fd8ab99a054c677",
          "sha256": "783af2e399208ab5a26e7d124be18bdf4c80a98329a7f3c93bb68fb9354fb9c8",
          "sha1": "34218ce77302c8800119571bc44babcf23504331",
          "md5": "ee49c20637b6e2eab2a8693fba0c31fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04631-DEV.jar",
          "url": "embedded-mas-0.04631-DEV.jar",
          "size": 76992,
          "sha512": "7e3d9c1a7553d9d106835ff44ebb8570e5cde07e905ae41624877b68b483b6f73d3315afab0b82204dca8a367629c8710c21b71686d0f4fa0fd8ab99a054c677",
          "sha256": "783af2e399208ab5a26e7d124be18bdf4c80a98329a7f3c93bb68fb9354fb9c8",
          "sha1": "34218ce77302c8800119571bc44babcf23504331",
          "md5": "ee49c20637b6e2eab2a8693fba0c31fb"
        }
      ]
    }
  ]
}
