{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04631-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04631-DEV.jar",
          "url": "embedded-mas-0.04631-DEV.jar",
          "size": 77206,
          "sha512": "cbdb088a58be0630e0af69bf21d285f875fae59bce67a49274c8a336541607ef23dd0dc0247923747fba014cc20a975ea915ad4f6ec75f6ad8df63e2b02e02b9",
          "sha256": "bf8502dc7d8b855d9ea51124f2789ff3357d31089adca5b428fe14fe1463df38",
          "sha1": "a0aed09cd4acf60b8efa8c3bf4e596dbcb89e441",
          "md5": "8b10604e310b7e8f5a1226e9b0058bcf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04631-DEV.jar",
          "url": "embedded-mas-0.04631-DEV.jar",
          "size": 77206,
          "sha512": "cbdb088a58be0630e0af69bf21d285f875fae59bce67a49274c8a336541607ef23dd0dc0247923747fba014cc20a975ea915ad4f6ec75f6ad8df63e2b02e02b9",
          "sha256": "bf8502dc7d8b855d9ea51124f2789ff3357d31089adca5b428fe14fe1463df38",
          "sha1": "a0aed09cd4acf60b8efa8c3bf4e596dbcb89e441",
          "md5": "8b10604e310b7e8f5a1226e9b0058bcf"
        }
      ]
    }
  ]
}
