{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03030-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03030-SNAPSHOT.jar",
          "url": "embedded-mas-0.03030-SNAPSHOT.jar",
          "size": 59769,
          "sha512": "8bb06009b4e679255b687d982c84d99a33ebe44968d0eb4b5e562f25b932b941a78c774280cef5fdf0710b978da342400a14e15c43ee128e8c4a43243ea9c05a",
          "sha256": "555476e88cf9026801cc1fb445ad3833e1cfb253daa2178d4ccda5cca4bbaa8f",
          "sha1": "207e50eb43ba4d104ba95b5c5d6a99c7e310a69e",
          "md5": "b2c7d97e8b5776d5a90dbcac165f43c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03030-SNAPSHOT.jar",
          "url": "embedded-mas-0.03030-SNAPSHOT.jar",
          "size": 59769,
          "sha512": "8bb06009b4e679255b687d982c84d99a33ebe44968d0eb4b5e562f25b932b941a78c774280cef5fdf0710b978da342400a14e15c43ee128e8c4a43243ea9c05a",
          "sha256": "555476e88cf9026801cc1fb445ad3833e1cfb253daa2178d4ccda5cca4bbaa8f",
          "sha1": "207e50eb43ba4d104ba95b5c5d6a99c7e310a69e",
          "md5": "b2c7d97e8b5776d5a90dbcac165f43c7"
        }
      ]
    }
  ]
}
