{
  "formatVersion": "1.1",
  "component": {
    "group": "javard",
    "module": "javard",
    "version": "0.035a-NRJ",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "javard-0.035a-NRJ.jar",
          "url": "javard-0.035a-NRJ.jar",
          "size": 7154,
          "sha512": "1c30db6bc64daae7bfbca923df7a3114f76cf00710fdbafe034dabd5c36616719fbebed2532bcc0cc77f068fb4005cb2e247c906f60715ceb76e7a67aba3e622",
          "sha256": "2934fceea4d70b16686204286ced5dcff64f085de23d1056f3ca0e58c9f267bd",
          "sha1": "16aaf8eae33ea50faa69410964916cd474ff7d79",
          "md5": "0d84bb83a8a7d99913e8a073645a0cda"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.neuronrobotics",
          "module": "nrjavaserial",
          "version": {
            "requires": "5.2.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "javard-0.035a-NRJ.jar",
          "url": "javard-0.035a-NRJ.jar",
          "size": 7154,
          "sha512": "1c30db6bc64daae7bfbca923df7a3114f76cf00710fdbafe034dabd5c36616719fbebed2532bcc0cc77f068fb4005cb2e247c906f60715ceb76e7a67aba3e622",
          "sha256": "2934fceea4d70b16686204286ced5dcff64f085de23d1056f3ca0e58c9f267bd",
          "sha1": "16aaf8eae33ea50faa69410964916cd474ff7d79",
          "md5": "0d84bb83a8a7d99913e8a073645a0cda"
        }
      ]
    }
  ]
}
