{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03002-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03002-SNAPSHOT.jar",
          "url": "embedded-mas-0.03002-SNAPSHOT.jar",
          "size": 51797,
          "sha512": "46a5187079f593edde78286bda4a54a81c27e0c8d93d3b7199d1244b7a3948b52e467effd7a165858629cfd708d54b323ed0ba7a6f6048b7d4c9bd8452181234",
          "sha256": "65407a26911b0d478387c0d7b7a31320d420746c0b61b47c91a2ecd22d7e66f7",
          "sha1": "4a2c11d72e318693cf5f9310290cc11a53c60666",
          "md5": "be63c65430806ea7ad5e22eed7e5d45f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03002-SNAPSHOT.jar",
          "url": "embedded-mas-0.03002-SNAPSHOT.jar",
          "size": 51797,
          "sha512": "46a5187079f593edde78286bda4a54a81c27e0c8d93d3b7199d1244b7a3948b52e467effd7a165858629cfd708d54b323ed0ba7a6f6048b7d4c9bd8452181234",
          "sha256": "65407a26911b0d478387c0d7b7a31320d420746c0b61b47c91a2ecd22d7e66f7",
          "sha1": "4a2c11d72e318693cf5f9310290cc11a53c60666",
          "md5": "be63c65430806ea7ad5e22eed7e5d45f"
        }
      ]
    }
  ]
}
