{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271532-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271532-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271532-SNAPSHOT.jar",
          "size": 31185,
          "sha512": "6bc0d88538e9b53397b8f8c3732a6b8e270ffcba0edb1efc01a65339e70e558803ab33cde80aef37a68f69dcbe8563ebdf10d88dbaa4f709990fba259bf051cd",
          "sha256": "ff6f3666ae0a671e8390d58ebc14a066aec3b6e88def6e47e20f661b8e969ded",
          "sha1": "eb5ccabc25e9ad6586fabc21c4e545370951f84e",
          "md5": "4e5429a80510e99d0a0aa9b8301a1a43"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271532-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271532-SNAPSHOT.jar",
          "size": 31185,
          "sha512": "6bc0d88538e9b53397b8f8c3732a6b8e270ffcba0edb1efc01a65339e70e558803ab33cde80aef37a68f69dcbe8563ebdf10d88dbaa4f709990fba259bf051cd",
          "sha256": "ff6f3666ae0a671e8390d58ebc14a066aec3b6e88def6e47e20f661b8e969ded",
          "sha1": "eb5ccabc25e9ad6586fabc21c4e545370951f84e",
          "md5": "4e5429a80510e99d0a0aa9b8301a1a43"
        }
      ]
    }
  ]
}
