{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.038017-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038017-SNAPSHOT.jar",
          "url": "embedded-mas-0.038017-SNAPSHOT.jar",
          "size": 75701,
          "sha512": "904bf25dac4bfaddf86777a6300f7648493f46f13e6ddc7b5b48d3d65a43dfe1a3e42806f3845094fbc11b61ec469a38801c2c40cf6ab669bde5a7b6bcaf353a",
          "sha256": "f56ed72b52098c6521d55766df306251aa2596649ea78abbde049589392c2123",
          "sha1": "cec49dae413c0af71d837aa634202d5e2c299dd8",
          "md5": "8ed6a81d62de1294769d7421952fe514"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038017-SNAPSHOT.jar",
          "url": "embedded-mas-0.038017-SNAPSHOT.jar",
          "size": 75701,
          "sha512": "904bf25dac4bfaddf86777a6300f7648493f46f13e6ddc7b5b48d3d65a43dfe1a3e42806f3845094fbc11b61ec469a38801c2c40cf6ab669bde5a7b6bcaf353a",
          "sha256": "f56ed72b52098c6521d55766df306251aa2596649ea78abbde049589392c2123",
          "sha1": "cec49dae413c0af71d837aa634202d5e2c299dd8",
          "md5": "8ed6a81d62de1294769d7421952fe514"
        }
      ]
    }
  ]
}
