{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03905-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03905-SNAPSHOT.jar",
          "url": "embedded-mas-0.03905-SNAPSHOT.jar",
          "size": 71633,
          "sha512": "acffd6149606e5a8096f96f438656e0b89049d1e8a542147935fdfcad79a32b12200895ce1628da0405d700515a1bed5fd95f441a62f5d0a83149bf44432da2d",
          "sha256": "e0019d619265c62f226dee6d783ae6ed67c2fcb7843c8c9a422c69e13c61732e",
          "sha1": "20c001c8139d952ef917f921ee514f1e1bb85e13",
          "md5": "a87868083bfd0535b98a3f6cf89d0d7f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03905-SNAPSHOT.jar",
          "url": "embedded-mas-0.03905-SNAPSHOT.jar",
          "size": 71633,
          "sha512": "acffd6149606e5a8096f96f438656e0b89049d1e8a542147935fdfcad79a32b12200895ce1628da0405d700515a1bed5fd95f441a62f5d0a83149bf44432da2d",
          "sha256": "e0019d619265c62f226dee6d783ae6ed67c2fcb7843c8c9a422c69e13c61732e",
          "sha1": "20c001c8139d952ef917f921ee514f1e1bb85e13",
          "md5": "a87868083bfd0535b98a3f6cf89d0d7f"
        }
      ]
    }
  ]
}
