{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271524-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271524-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271524-SNAPSHOT.jar",
          "size": 30894,
          "sha512": "e494cbbe54379ee9f7a345c56711a6a4e56a63d38c5b62d647b0daa0e1c9f8192aef62367d1ff0c293cf518857d676fb160603ce37a6a1b447fe44c23b6c9bb6",
          "sha256": "a0c62e46f72890f696d6fc17e90c2e913066f879d79d2ca826597b3202370401",
          "sha1": "0263e8519100b33884f1541fb463dd95e94c1947",
          "md5": "710f2603d9a64ec65c7eea5d7e95c382"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271524-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271524-SNAPSHOT.jar",
          "size": 30894,
          "sha512": "e494cbbe54379ee9f7a345c56711a6a4e56a63d38c5b62d647b0daa0e1c9f8192aef62367d1ff0c293cf518857d676fb160603ce37a6a1b447fe44c23b6c9bb6",
          "sha256": "a0c62e46f72890f696d6fc17e90c2e913066f879d79d2ca826597b3202370401",
          "sha1": "0263e8519100b33884f1541fb463dd95e94c1947",
          "md5": "710f2603d9a64ec65c7eea5d7e95c382"
        }
      ]
    }
  ]
}
