{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03204-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03204-SNAPSHOT.jar",
          "url": "embedded-mas-0.03204-SNAPSHOT.jar",
          "size": 62201,
          "sha512": "8618b2b0a456132ba9c5a73fd9fda6892178d8ccc145ce91f37a1c3a0c98f033d766c822721a992a3d120ab54d7c93e39b8e99b9cc20564587c99249094e8aff",
          "sha256": "6af88f924c4e80d86fead4d418bdfcc73417bdc1f082bc9d2e30493bc46d77f2",
          "sha1": "6f0b999f4afa29ac95b21bf7e54dfa4b7cc381b7",
          "md5": "9b20d7c25afa5139035eee5577f10967"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03204-SNAPSHOT.jar",
          "url": "embedded-mas-0.03204-SNAPSHOT.jar",
          "size": 62201,
          "sha512": "8618b2b0a456132ba9c5a73fd9fda6892178d8ccc145ce91f37a1c3a0c98f033d766c822721a992a3d120ab54d7c93e39b8e99b9cc20564587c99249094e8aff",
          "sha256": "6af88f924c4e80d86fead4d418bdfcc73417bdc1f082bc9d2e30493bc46d77f2",
          "sha1": "6f0b999f4afa29ac95b21bf7e54dfa4b7cc381b7",
          "md5": "9b20d7c25afa5139035eee5577f10967"
        }
      ]
    }
  ]
}
