{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271202-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271202-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271202-SNAPSHOT.jar",
          "size": 30183,
          "sha512": "53fc8b3d55772e0436574e7617edc69c961e7876c88589469b1ab594c9d9bec3521ac7291da1e4205193b778116fbddd05635d495c21c73ecc20f8c7286e9aa5",
          "sha256": "69d8ab6745a67581899e8bc64d51f6760e79677673f6e643a38ce467700adc72",
          "sha1": "58ae55220ccf9296aeb2f721bb061fe61d8d675d",
          "md5": "e3a94c11cfedc68e68ddd99c2683edc1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271202-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271202-SNAPSHOT.jar",
          "size": 30183,
          "sha512": "53fc8b3d55772e0436574e7617edc69c961e7876c88589469b1ab594c9d9bec3521ac7291da1e4205193b778116fbddd05635d495c21c73ecc20f8c7286e9aa5",
          "sha256": "69d8ab6745a67581899e8bc64d51f6760e79677673f6e643a38ce467700adc72",
          "sha1": "58ae55220ccf9296aeb2f721bb061fe61d8d675d",
          "md5": "e3a94c11cfedc68e68ddd99c2683edc1"
        }
      ]
    }
  ]
}
