{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03101-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03101-SNAPSHOT.jar",
          "url": "embedded-mas-0.03101-SNAPSHOT.jar",
          "size": 61213,
          "sha512": "990081527149babb759e0ed8acd075c33bbc4f3d96ccb47e1f7f0a94d74ca60b207643b7d273521378654b14c46a9cc0ee9f26cdf513fe4cd7f7ef8acac5be67",
          "sha256": "804a298ed467c64e03abe54bac22f4c5b66e222b8765773951eadfffb636f99c",
          "sha1": "8093aa2a1c6aea010b3e822152b19df9fda913a1",
          "md5": "5176272760981dc520a42861a00be7e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03101-SNAPSHOT.jar",
          "url": "embedded-mas-0.03101-SNAPSHOT.jar",
          "size": 61213,
          "sha512": "990081527149babb759e0ed8acd075c33bbc4f3d96ccb47e1f7f0a94d74ca60b207643b7d273521378654b14c46a9cc0ee9f26cdf513fe4cd7f7ef8acac5be67",
          "sha256": "804a298ed467c64e03abe54bac22f4c5b66e222b8765773951eadfffb636f99c",
          "sha1": "8093aa2a1c6aea010b3e822152b19df9fda913a1",
          "md5": "5176272760981dc520a42861a00be7e0"
        }
      ]
    }
  ]
}
