{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04679-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04679-DEV.jar",
          "url": "embedded-mas-0.04679-DEV.jar",
          "size": 70770,
          "sha512": "bcd74604a43d84705293ca6b244be6a7cdfaf5ae5ae05fbaee477d140591bf6b958028d840215f4ca8dc7c155f1ec75028fef23778f4deed84559b5c6112bd3a",
          "sha256": "01082cba66482dfb8d3c2561075e0abef29719576f7df17a7ec80ae781f2f159",
          "sha1": "2d97fef38555899ae3208df7edfea5f5268827df",
          "md5": "8fee609c18111e631e2bc24d0d0bc490"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04679-DEV.jar",
          "url": "embedded-mas-0.04679-DEV.jar",
          "size": 70770,
          "sha512": "bcd74604a43d84705293ca6b244be6a7cdfaf5ae5ae05fbaee477d140591bf6b958028d840215f4ca8dc7c155f1ec75028fef23778f4deed84559b5c6112bd3a",
          "sha256": "01082cba66482dfb8d3c2561075e0abef29719576f7df17a7ec80ae781f2f159",
          "sha1": "2d97fef38555899ae3208df7edfea5f5268827df",
          "md5": "8fee609c18111e631e2bc24d0d0bc490"
        }
      ]
    }
  ]
}
