{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04636-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04636-DEV.jar",
          "url": "embedded-mas-0.04636-DEV.jar",
          "size": 77411,
          "sha512": "b1d74c75abc32a325bdcf0e9cda78042da7aa41f0aca15c5d473c1b5c5e0700b7410492175d99279420f92b8e3eabdbae55c9d55afc3f2ff9a14a8a03d618d9a",
          "sha256": "6911a2cf262b74ea038c99b9291462fec27315349b54f6f98786dc894b7e76a2",
          "sha1": "57def1628eab206dfba330efdf2167cd6b3ac3f5",
          "md5": "d239de378a07b948a136874b9e67c0ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04636-DEV.jar",
          "url": "embedded-mas-0.04636-DEV.jar",
          "size": 77411,
          "sha512": "b1d74c75abc32a325bdcf0e9cda78042da7aa41f0aca15c5d473c1b5c5e0700b7410492175d99279420f92b8e3eabdbae55c9d55afc3f2ff9a14a8a03d618d9a",
          "sha256": "6911a2cf262b74ea038c99b9291462fec27315349b54f6f98786dc894b7e76a2",
          "sha1": "57def1628eab206dfba330efdf2167cd6b3ac3f5",
          "md5": "d239de378a07b948a136874b9e67c0ca"
        }
      ]
    }
  ]
}
