{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04618-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04618-SNAPSHOT.jar",
          "url": "embedded-mas-0.04618-SNAPSHOT.jar",
          "size": 69413,
          "sha512": "7df6a36154f163feab7bf57d0930a149eb1369758edd80d2e5571470016e27ed9f9093fe4bdfc476e8e76835434bd7edb017009d0bdfabbf859c2cb96ba2717f",
          "sha256": "fc59f90d86b5e9f486be2b6850459c6ee674143466608b77bfb24e7ed31a2ea1",
          "sha1": "880fcbcf8c4cdb084e9ee0a2b505b62c9547ae55",
          "md5": "06909b7b7a5273f44664b656fea8078d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04618-SNAPSHOT.jar",
          "url": "embedded-mas-0.04618-SNAPSHOT.jar",
          "size": 69413,
          "sha512": "7df6a36154f163feab7bf57d0930a149eb1369758edd80d2e5571470016e27ed9f9093fe4bdfc476e8e76835434bd7edb017009d0bdfabbf859c2cb96ba2717f",
          "sha256": "fc59f90d86b5e9f486be2b6850459c6ee674143466608b77bfb24e7ed31a2ea1",
          "sha1": "880fcbcf8c4cdb084e9ee0a2b505b62c9547ae55",
          "md5": "06909b7b7a5273f44664b656fea8078d"
        }
      ]
    }
  ]
}
