{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03015-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03015-SNAPSHOT.jar",
          "url": "embedded-mas-0.03015-SNAPSHOT.jar",
          "size": 53629,
          "sha512": "5677a08a115335b70d236e346a047b8203ed35a4c2a5f800d1a7a0259585887f8f7393868e6d218e9119a09223575b43b07ebccae899f26a697f162e69e6ad74",
          "sha256": "66e6bd6d8945ce96f266fb627af4ed1c293dc8795416e21b7a677aa151c0d383",
          "sha1": "45b1850be083be027a4b44a2ee31fba37388ff19",
          "md5": "2fb5a2111153405ce93704836b004431"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03015-SNAPSHOT.jar",
          "url": "embedded-mas-0.03015-SNAPSHOT.jar",
          "size": 53629,
          "sha512": "5677a08a115335b70d236e346a047b8203ed35a4c2a5f800d1a7a0259585887f8f7393868e6d218e9119a09223575b43b07ebccae899f26a697f162e69e6ad74",
          "sha256": "66e6bd6d8945ce96f266fb627af4ed1c293dc8795416e21b7a677aa151c0d383",
          "sha1": "45b1850be083be027a4b44a2ee31fba37388ff19",
          "md5": "2fb5a2111153405ce93704836b004431"
        }
      ]
    }
  ]
}
