{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271516-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271516-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271516-SNAPSHOT.jar",
          "size": 30725,
          "sha512": "e7512712757a4918354595ab90763a7a6e88be771afa72d39f50b3e179e7d4cfcab5afcb15c52f0eb3717300404bb30389197d4328d9ab2e47e88f58b7ec1bb6",
          "sha256": "0c2b567ec1812b1b02c8c96966f03e516ba33d645498aa9b4889b9ed4ea703d4",
          "sha1": "507801e037b14b17311c0000bef73919cfe1cbec",
          "md5": "93cc12029db52a600672b2332d9ad0a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271516-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271516-SNAPSHOT.jar",
          "size": 30725,
          "sha512": "e7512712757a4918354595ab90763a7a6e88be771afa72d39f50b3e179e7d4cfcab5afcb15c52f0eb3717300404bb30389197d4328d9ab2e47e88f58b7ec1bb6",
          "sha256": "0c2b567ec1812b1b02c8c96966f03e516ba33d645498aa9b4889b9ed4ea703d4",
          "sha1": "507801e037b14b17311c0000bef73919cfe1cbec",
          "md5": "93cc12029db52a600672b2332d9ad0a5"
        }
      ]
    }
  ]
}
