{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04665-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04665-DEV.jar",
          "url": "embedded-mas-0.04665-DEV.jar",
          "size": 70702,
          "sha512": "b8fb0397cae4099185c23e055d3a7ee0bf589b2a2eb335b5ac85fa35052df3966fb19686d92001b76c611400398499af60b8f7a465c25043ea133b0a4a2d9170",
          "sha256": "ef579911dd3315c4ad4ef8280f2b142e2caa3f2257ed20b548c520f4c3cc3337",
          "sha1": "105a2bfd84c93f3384779ee56ac8e00a8c3e1e49",
          "md5": "4adb995c163b15551ba7fbf88b529a7b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04665-DEV.jar",
          "url": "embedded-mas-0.04665-DEV.jar",
          "size": 70702,
          "sha512": "b8fb0397cae4099185c23e055d3a7ee0bf589b2a2eb335b5ac85fa35052df3966fb19686d92001b76c611400398499af60b8f7a465c25043ea133b0a4a2d9170",
          "sha256": "ef579911dd3315c4ad4ef8280f2b142e2caa3f2257ed20b548c520f4c3cc3337",
          "sha1": "105a2bfd84c93f3384779ee56ac8e00a8c3e1e49",
          "md5": "4adb995c163b15551ba7fbf88b529a7b"
        }
      ]
    }
  ]
}
