{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.05524BENCHMARK-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.05524BENCHMARK-SNAPSHOT.jar",
          "url": "embedded-mas-0.05524BENCHMARK-SNAPSHOT.jar",
          "size": 88064,
          "sha512": "2a04eb02f5c8f2fe3b913fb72e618bff1b503b6579489b676280e4dc1a550c7e35154ab8d00fa65fb932b6c1586d6781e4e40587515ae534ab18e8d0cf4f64c5",
          "sha256": "1a3674cf56e9b95838864e9c82f9e4c6916e39cf3bf83e82ebbadd2561a8bd86",
          "sha1": "50d0cf29bc52f435fa07022fbf3ed3579605199d",
          "md5": "1c2348e5ab47b65d4cdcf7c1777ba063"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.30"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.05524BENCHMARK-SNAPSHOT.jar",
          "url": "embedded-mas-0.05524BENCHMARK-SNAPSHOT.jar",
          "size": 88064,
          "sha512": "2a04eb02f5c8f2fe3b913fb72e618bff1b503b6579489b676280e4dc1a550c7e35154ab8d00fa65fb932b6c1586d6781e4e40587515ae534ab18e8d0cf4f64c5",
          "sha256": "1a3674cf56e9b95838864e9c82f9e4c6916e39cf3bf83e82ebbadd2561a8bd86",
          "sha1": "50d0cf29bc52f435fa07022fbf3ed3579605199d",
          "md5": "1c2348e5ab47b65d4cdcf7c1777ba063"
        }
      ]
    }
  ]
}
