{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04615-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04615-SNAPSHOT.jar",
          "url": "embedded-mas-0.04615-SNAPSHOT.jar",
          "size": 69344,
          "sha512": "84ad564a3627c5fe465404c638b1d3b543accc053aaac54f6fdb302b7dc83eb87fc4fff9a0bbc52aceaa056f333b02f8fd6507924723e28af5f7eb1407d2ab53",
          "sha256": "0185fd387d09570f418f32292e7fe676007615cfbcb183bbc20d9aa094cb26a1",
          "sha1": "ca26aaf19579fcac8d68afa27168e039b5676a13",
          "md5": "6819fe947a554c5a548a4f92e99e7f56"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04615-SNAPSHOT.jar",
          "url": "embedded-mas-0.04615-SNAPSHOT.jar",
          "size": 69344,
          "sha512": "84ad564a3627c5fe465404c638b1d3b543accc053aaac54f6fdb302b7dc83eb87fc4fff9a0bbc52aceaa056f333b02f8fd6507924723e28af5f7eb1407d2ab53",
          "sha256": "0185fd387d09570f418f32292e7fe676007615cfbcb183bbc20d9aa094cb26a1",
          "sha1": "ca26aaf19579fcac8d68afa27168e039b5676a13",
          "md5": "6819fe947a554c5a548a4f92e99e7f56"
        }
      ]
    }
  ]
}
