{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04210-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04210-SNAPSHOT.jar",
          "url": "embedded-mas-0.04210-SNAPSHOT.jar",
          "size": 72373,
          "sha512": "a701274d2c1eba28bf3e29920b7be49972f3d8d15a571275eee4a1c1617709854d4c38c4c7df97f584e11d5d79211afac057e1752ae9fd6be7e540be1399966d",
          "sha256": "9c3339f0f12e510a3cc5ab6e0958f0743749b3982e57f3d907ffe33dc85ed23c",
          "sha1": "a593d83669967f8df37fe4feb44035b709106819",
          "md5": "029e26e073e66b9e8c6a140daed31dd4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04210-SNAPSHOT.jar",
          "url": "embedded-mas-0.04210-SNAPSHOT.jar",
          "size": 72373,
          "sha512": "a701274d2c1eba28bf3e29920b7be49972f3d8d15a571275eee4a1c1617709854d4c38c4c7df97f584e11d5d79211afac057e1752ae9fd6be7e540be1399966d",
          "sha256": "9c3339f0f12e510a3cc5ab6e0958f0743749b3982e57f3d907ffe33dc85ed23c",
          "sha1": "a593d83669967f8df37fe4feb44035b709106819",
          "md5": "029e26e073e66b9e8c6a140daed31dd4"
        }
      ]
    }
  ]
}
