{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03402-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03402-SNAPSHOT.jar",
          "url": "embedded-mas-0.03402-SNAPSHOT.jar",
          "size": 62940,
          "sha512": "94f8bf99b48f743a7ca3702f33f91e558985f168525857e98733d22f6b487b08982de236602181abddf087d8fa56cece71f3a779046f433da5dc4988a5e30766",
          "sha256": "5e3ef2c73e74ef809fdc2a04492f1ab4c699838274743a9e0fd4a4461233d6dc",
          "sha1": "513021618b362573e13ff30ab7dfde96599789e5",
          "md5": "6574d793c4014836d81ce270da3fdf53"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03402-SNAPSHOT.jar",
          "url": "embedded-mas-0.03402-SNAPSHOT.jar",
          "size": 62940,
          "sha512": "94f8bf99b48f743a7ca3702f33f91e558985f168525857e98733d22f6b487b08982de236602181abddf087d8fa56cece71f3a779046f433da5dc4988a5e30766",
          "sha256": "5e3ef2c73e74ef809fdc2a04492f1ab4c699838274743a9e0fd4a4461233d6dc",
          "sha1": "513021618b362573e13ff30ab7dfde96599789e5",
          "md5": "6574d793c4014836d81ce270da3fdf53"
        }
      ]
    }
  ]
}
