{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04651-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04651-DEV.jar",
          "url": "embedded-mas-0.04651-DEV.jar",
          "size": 70463,
          "sha512": "f28d6a591d6c8ca714b19fc0a8c99dac1f848729bc9fb3a294a550150e1075be5c9f7ca19fe3de4cb6d13a462ea84699072151f15cacd2fe790669b3abd98b96",
          "sha256": "ee53b913d24716435e7a74dcc5c63cdcc3ae783a90f530701a04b4b77ba14866",
          "sha1": "7c26c53776a060c5819ab0a3da382d004a7f0534",
          "md5": "e93b3eb2d5111e01e91afb1376107dca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04651-DEV.jar",
          "url": "embedded-mas-0.04651-DEV.jar",
          "size": 70463,
          "sha512": "f28d6a591d6c8ca714b19fc0a8c99dac1f848729bc9fb3a294a550150e1075be5c9f7ca19fe3de4cb6d13a462ea84699072151f15cacd2fe790669b3abd98b96",
          "sha256": "ee53b913d24716435e7a74dcc5c63cdcc3ae783a90f530701a04b4b77ba14866",
          "sha1": "7c26c53776a060c5819ab0a3da382d004a7f0534",
          "md5": "e93b3eb2d5111e01e91afb1376107dca"
        }
      ]
    }
  ]
}
