{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.038010-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038010-SNAPSHOT.jar",
          "url": "embedded-mas-0.038010-SNAPSHOT.jar",
          "size": 74577,
          "sha512": "fff623a75d0116d0bdfd92f6aaf807a223f1373783b692fc04ee5afd7b98c7f38e89f747972f5ff2243258a548a18efeb287d24dbe6e87ec1c348c83addaec2f",
          "sha256": "d9733efd8b623f67e6eb0c9dff285bec4c0ed99a05de439f8c6d7921a4627843",
          "sha1": "6fd2fef70f8520ec4847ab8f1d13e34670913431",
          "md5": "a177c2800df84a41fd5811e88135ed7d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038010-SNAPSHOT.jar",
          "url": "embedded-mas-0.038010-SNAPSHOT.jar",
          "size": 74577,
          "sha512": "fff623a75d0116d0bdfd92f6aaf807a223f1373783b692fc04ee5afd7b98c7f38e89f747972f5ff2243258a548a18efeb287d24dbe6e87ec1c348c83addaec2f",
          "sha256": "d9733efd8b623f67e6eb0c9dff285bec4c0ed99a05de439f8c6d7921a4627843",
          "sha1": "6fd2fef70f8520ec4847ab8f1d13e34670913431",
          "md5": "a177c2800df84a41fd5811e88135ed7d"
        }
      ]
    }
  ]
}
