{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04632-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04632-DEV.jar",
          "url": "embedded-mas-0.04632-DEV.jar",
          "size": 77206,
          "sha512": "f1b4b6785eea5dfb887138934c141b8f78e587f1b4dfd851915a10bc93e55e6e084b4d67df6fb49cb466b286bb97dfb3f899a85eb8f8a64f22d35bc209c04a91",
          "sha256": "1ea55df5e8fe1e97aea6b188e9e9645a906451443348ba077491d15abd398c12",
          "sha1": "5cb79b6df4db0c9403c84adb177cb3ac4f8e2bb5",
          "md5": "a7ff7dbf96b05e560869116d7df3ccf4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04632-DEV.jar",
          "url": "embedded-mas-0.04632-DEV.jar",
          "size": 77206,
          "sha512": "f1b4b6785eea5dfb887138934c141b8f78e587f1b4dfd851915a10bc93e55e6e084b4d67df6fb49cb466b286bb97dfb3f899a85eb8f8a64f22d35bc209c04a91",
          "sha256": "1ea55df5e8fe1e97aea6b188e9e9645a906451443348ba077491d15abd398c12",
          "sha1": "5cb79b6df4db0c9403c84adb177cb3ac4f8e2bb5",
          "md5": "a7ff7dbf96b05e560869116d7df3ccf4"
        }
      ]
    }
  ]
}
