{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.02714-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02714-SNAPSHOT.jar",
          "url": "embedded-mas-0.02714-SNAPSHOT.jar",
          "size": 30261,
          "sha512": "9bfa486cf7681647f9c3af644629f27cc2be866aa88aea6edbaea5ee41f4469e10b8ea45e0c243ef53e12e4f0bd067fee494f94ad878ce222b25f84b3d44a79c",
          "sha256": "690940add914ae85c085b700623ff554b2d2974eed44854d14abb52b7bc03aa3",
          "sha1": "b47859bb3951099e435fd0560e38a616106066a7",
          "md5": "d845db90d58b3ea9eba0200426486b68"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02714-SNAPSHOT.jar",
          "url": "embedded-mas-0.02714-SNAPSHOT.jar",
          "size": 30261,
          "sha512": "9bfa486cf7681647f9c3af644629f27cc2be866aa88aea6edbaea5ee41f4469e10b8ea45e0c243ef53e12e4f0bd067fee494f94ad878ce222b25f84b3d44a79c",
          "sha256": "690940add914ae85c085b700623ff554b2d2974eed44854d14abb52b7bc03aa3",
          "sha1": "b47859bb3951099e435fd0560e38a616106066a7",
          "md5": "d845db90d58b3ea9eba0200426486b68"
        }
      ]
    }
  ]
}
