{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271539-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271539-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271539-SNAPSHOT.jar",
          "size": 30580,
          "sha512": "9df8848fe539f0f190ab739bd501cee1b522358e3a2285f73d0da3d505c940c0fc9e153460ec6b02dc957c9fee0ab274f0a69a05e4863079d3b9d62ab8a2c26d",
          "sha256": "c987470a1b0adc77bb10ff0a69c0cebecfcd94ba29bf3c9ea3cf304dbaf4055e",
          "sha1": "9bf28edc174a8a2905b63d2b78ba0cc6348c3fc7",
          "md5": "11a362405fbc3159426a3d35473e83f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271539-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271539-SNAPSHOT.jar",
          "size": 30580,
          "sha512": "9df8848fe539f0f190ab739bd501cee1b522358e3a2285f73d0da3d505c940c0fc9e153460ec6b02dc957c9fee0ab274f0a69a05e4863079d3b9d62ab8a2c26d",
          "sha256": "c987470a1b0adc77bb10ff0a69c0cebecfcd94ba29bf3c9ea3cf304dbaf4055e",
          "sha1": "9bf28edc174a8a2905b63d2b78ba0cc6348c3fc7",
          "md5": "11a362405fbc3159426a3d35473e83f7"
        }
      ]
    }
  ]
}
