{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03401-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03401-SNAPSHOT.jar",
          "url": "embedded-mas-0.03401-SNAPSHOT.jar",
          "size": 62860,
          "sha512": "bb1eff5c16c609cafcdb82d86b6d24c30eb82fa775e389feaa8562a37000bcffb2bfbfd00f6eb36e01a16e946f3ede56476fd03a3666b04569232f20b733bd01",
          "sha256": "343079b7595a93d3455e9b898b7d8f9bdd7ca7cc6df005c1fccf2a76c8a5808a",
          "sha1": "c480ea2b83a440d761011a0fc847130c636653e7",
          "md5": "1cedf1fd02664aa149c5f48d9a5cf7dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03401-SNAPSHOT.jar",
          "url": "embedded-mas-0.03401-SNAPSHOT.jar",
          "size": 62860,
          "sha512": "bb1eff5c16c609cafcdb82d86b6d24c30eb82fa775e389feaa8562a37000bcffb2bfbfd00f6eb36e01a16e946f3ede56476fd03a3666b04569232f20b733bd01",
          "sha256": "343079b7595a93d3455e9b898b7d8f9bdd7ca7cc6df005c1fccf2a76c8a5808a",
          "sha1": "c480ea2b83a440d761011a0fc847130c636653e7",
          "md5": "1cedf1fd02664aa149c5f48d9a5cf7dd"
        }
      ]
    }
  ]
}
