{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.05316-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.05316-SNAPSHOT.jar",
          "url": "embedded-mas-0.05316-SNAPSHOT.jar",
          "size": 89627,
          "sha512": "375b79f6062b6295280225af5af41abe6886603d5e41da1cbefd9525c68cb6b833b283107a9a6f49c7768eaeeeae9b1d70f748b6d113653e712b254aefdd90e5",
          "sha256": "f7444fd0304ed6864b30c6dd41d30b59034590b026166da289ea31d293ad0dcc",
          "sha1": "dba8cde8747bd2e072355c740d5086b1461be803",
          "md5": "1b2a40bc2018b48c3856e4da6884487c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.30"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.05316-SNAPSHOT.jar",
          "url": "embedded-mas-0.05316-SNAPSHOT.jar",
          "size": 89627,
          "sha512": "375b79f6062b6295280225af5af41abe6886603d5e41da1cbefd9525c68cb6b833b283107a9a6f49c7768eaeeeae9b1d70f748b6d113653e712b254aefdd90e5",
          "sha256": "f7444fd0304ed6864b30c6dd41d30b59034590b026166da289ea31d293ad0dcc",
          "sha1": "dba8cde8747bd2e072355c740d5086b1461be803",
          "md5": "1b2a40bc2018b48c3856e4da6884487c"
        }
      ]
    }
  ]
}
