{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03609-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03609-SNAPSHOT.jar",
          "url": "embedded-mas-0.03609-SNAPSHOT.jar",
          "size": 65816,
          "sha512": "8756699ebbe3c0e35aadd70a18921997af011ca8324aae0849763cef739a299e638181bb4f61f9e225d685755b9da9ef3af1e6c85c6ba549283593a6d9c5177d",
          "sha256": "c154cc4380e3881c6b74c793ac69ba27602b5d158c4691783b0262e5b6f7d9f2",
          "sha1": "5d8cb7845922737c7d37a8dbf864231c8bf4f9de",
          "md5": "bff3dbd2e8556ca679854d4ca7739744"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03609-SNAPSHOT.jar",
          "url": "embedded-mas-0.03609-SNAPSHOT.jar",
          "size": 65816,
          "sha512": "8756699ebbe3c0e35aadd70a18921997af011ca8324aae0849763cef739a299e638181bb4f61f9e225d685755b9da9ef3af1e6c85c6ba549283593a6d9c5177d",
          "sha256": "c154cc4380e3881c6b74c793ac69ba27602b5d158c4691783b0262e5b6f7d9f2",
          "sha1": "5d8cb7845922737c7d37a8dbf864231c8bf4f9de",
          "md5": "bff3dbd2e8556ca679854d4ca7739744"
        }
      ]
    }
  ]
}
