{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271529-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271529-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271529-SNAPSHOT.jar",
          "size": 31015,
          "sha512": "a717ea9588bb5a56658ed43f8cfc57523ad1d3f64e72b6ee9ba5e4e9170d3edc230275a51ef53a95af7d89acbaeff69f426ba9be3aeb9029bf973bf0e65a5d36",
          "sha256": "abb11732a00ee370c3a8dda0ead1024648152e9fb582a2061c106477c48f89a1",
          "sha1": "4003d6875ae197f91bc0240b8dc52f3e9d466a32",
          "md5": "30af62168c75d4d731e36561a75e725a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271529-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271529-SNAPSHOT.jar",
          "size": 31015,
          "sha512": "a717ea9588bb5a56658ed43f8cfc57523ad1d3f64e72b6ee9ba5e4e9170d3edc230275a51ef53a95af7d89acbaeff69f426ba9be3aeb9029bf973bf0e65a5d36",
          "sha256": "abb11732a00ee370c3a8dda0ead1024648152e9fb582a2061c106477c48f89a1",
          "sha1": "4003d6875ae197f91bc0240b8dc52f3e9d466a32",
          "md5": "30af62168c75d4d731e36561a75e725a"
        }
      ]
    }
  ]
}
