{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03902-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03902-SNAPSHOT.jar",
          "url": "embedded-mas-0.03902-SNAPSHOT.jar",
          "size": 71063,
          "sha512": "cd0e810e345e95b84bcb29f8a77b67b6c88896071de4338db3733d01334f4dcdcd91b348b1d8a6627bf2b391c0b3f7cd25d7e41016a1c9a1d9b07feb7e63cfc9",
          "sha256": "1a19806f6153fcb980d6aadcbbe695457ae54943f596871f7d9b76f312f9a1b5",
          "sha1": "7c98523cd9f96945e51f79781a35ffe79017b414",
          "md5": "6219b524bc8d37e599091f6c4db5636b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03902-SNAPSHOT.jar",
          "url": "embedded-mas-0.03902-SNAPSHOT.jar",
          "size": 71063,
          "sha512": "cd0e810e345e95b84bcb29f8a77b67b6c88896071de4338db3733d01334f4dcdcd91b348b1d8a6627bf2b391c0b3f7cd25d7e41016a1c9a1d9b07feb7e63cfc9",
          "sha256": "1a19806f6153fcb980d6aadcbbe695457ae54943f596871f7d9b76f312f9a1b5",
          "sha1": "7c98523cd9f96945e51f79781a35ffe79017b414",
          "md5": "6219b524bc8d37e599091f6c4db5636b"
        }
      ]
    }
  ]
}
