{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04616-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04616-SNAPSHOT.jar",
          "url": "embedded-mas-0.04616-SNAPSHOT.jar",
          "size": 69382,
          "sha512": "5fe43dc3494adf10838e40fcbdf911860f271c8f0002e29f946bd1709b2d4605cb4f072791342cca4e4d284fbc64ec0c7cf61e59b4cfc994562dadb71b4c3476",
          "sha256": "6d93910b23790cede3413b0374fa1d9850c07ad121477aa902545768e4916c1d",
          "sha1": "795a1a4c93fba83f9ef69f516258e183a4d5065a",
          "md5": "1dc7fbad32dddd32d3494a80bdf0201e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04616-SNAPSHOT.jar",
          "url": "embedded-mas-0.04616-SNAPSHOT.jar",
          "size": 69382,
          "sha512": "5fe43dc3494adf10838e40fcbdf911860f271c8f0002e29f946bd1709b2d4605cb4f072791342cca4e4d284fbc64ec0c7cf61e59b4cfc994562dadb71b4c3476",
          "sha256": "6d93910b23790cede3413b0374fa1d9850c07ad121477aa902545768e4916c1d",
          "sha1": "795a1a4c93fba83f9ef69f516258e183a4d5065a",
          "md5": "1dc7fbad32dddd32d3494a80bdf0201e"
        }
      ]
    }
  ]
}
