{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03106-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03106-SNAPSHOT.jar",
          "url": "embedded-mas-0.03106-SNAPSHOT.jar",
          "size": 63553,
          "sha512": "666af611733904efa6ae471ce8952b3803904faac47191eaa6946fe8fe97efedc735eb991aa78689cfb34979a9ceac00d839cf3a4cc497b6ed9c1cc94ae18671",
          "sha256": "7e38af7f7d1536d96a4a7ffdb8d9d7828984c9a75b9606b70ae58e9984ea0361",
          "sha1": "a5e8a61ba17857b6ade59bc97fa454ad1b5c9cae",
          "md5": "d2f1bafb44b00c85cc75ee72d95d0e52"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03106-SNAPSHOT.jar",
          "url": "embedded-mas-0.03106-SNAPSHOT.jar",
          "size": 63553,
          "sha512": "666af611733904efa6ae471ce8952b3803904faac47191eaa6946fe8fe97efedc735eb991aa78689cfb34979a9ceac00d839cf3a4cc497b6ed9c1cc94ae18671",
          "sha256": "7e38af7f7d1536d96a4a7ffdb8d9d7828984c9a75b9606b70ae58e9984ea0361",
          "sha1": "a5e8a61ba17857b6ade59bc97fa454ad1b5c9cae",
          "md5": "d2f1bafb44b00c85cc75ee72d95d0e52"
        }
      ]
    }
  ]
}
