{
  "formatVersion": "1.1",
  "component": {
    "group": "javard",
    "module": "javard",
    "version": "0.035-NRJ",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "javard-0.035-NRJ.jar",
          "url": "javard-0.035-NRJ.jar",
          "size": 7147,
          "sha512": "40ec0597bba0507165fcbd328359269152673cdcd3addf79d1e41b0269ae4cf1a4342b64baa8e536cdaf59adeee288a1e809fbbb60fd6d1941fec9b9418e83b0",
          "sha256": "001f0f2c9091624e469cb19aebc74ce958e8327ad245c2b247fbf70acd0e021d",
          "sha1": "f6a83d13c5ead0a6db7947a97ab55ed6fbdd63fc",
          "md5": "45217634d4d0677996cdec48c6dfd499"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.neuronrobotics",
          "module": "nrjavaserial",
          "version": {
            "requires": "5.2.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "javard-0.035-NRJ.jar",
          "url": "javard-0.035-NRJ.jar",
          "size": 7147,
          "sha512": "40ec0597bba0507165fcbd328359269152673cdcd3addf79d1e41b0269ae4cf1a4342b64baa8e536cdaf59adeee288a1e809fbbb60fd6d1941fec9b9418e83b0",
          "sha256": "001f0f2c9091624e469cb19aebc74ce958e8327ad245c2b247fbf70acd0e021d",
          "sha1": "f6a83d13c5ead0a6db7947a97ab55ed6fbdd63fc",
          "md5": "45217634d4d0677996cdec48c6dfd499"
        }
      ]
    }
  ]
}
