{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.02903-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02903-SNAPSHOT.jar",
          "url": "embedded-mas-0.02903-SNAPSHOT.jar",
          "size": 30796,
          "sha512": "ec592883707f69982ea6d9b98684d0a349b2793244631872519f83ad8e378d9dc98b6619b7f98943b7d07d145823cff231fc3bd7b2d4b8c5dea732f7e17e6db7",
          "sha256": "68ee65e3602a98be50804cbbb9b52b3d06175873db66520e37755432fb127477",
          "sha1": "020a0bfd5e4f5e0fd3c115d047d5636efb4be5e1",
          "md5": "84a775d5b6c8c10c5ab3431565059aba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02903-SNAPSHOT.jar",
          "url": "embedded-mas-0.02903-SNAPSHOT.jar",
          "size": 30796,
          "sha512": "ec592883707f69982ea6d9b98684d0a349b2793244631872519f83ad8e378d9dc98b6619b7f98943b7d07d145823cff231fc3bd7b2d4b8c5dea732f7e17e6db7",
          "sha256": "68ee65e3602a98be50804cbbb9b52b3d06175873db66520e37755432fb127477",
          "sha1": "020a0bfd5e4f5e0fd3c115d047d5636efb4be5e1",
          "md5": "84a775d5b6c8c10c5ab3431565059aba"
        }
      ]
    }
  ]
}
