{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271521-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271521-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271521-SNAPSHOT.jar",
          "size": 30894,
          "sha512": "e3b9f1ca12a1185444842cd8ce6fd2328dcc004aeee56400a4c296b4cd4e0b22cc74ac74bcd9181a7828af7e6923bf08a5891a0d214a08fd7818aaa6185b9f27",
          "sha256": "31ef5fdd14ead666eaf50f3015c089f072311708fad49409c2add3db30b5ddbc",
          "sha1": "afdd1f63de36220141a8e930a10b47160ed99837",
          "md5": "1058288e5829d1d735e5f04c1e8891f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271521-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271521-SNAPSHOT.jar",
          "size": 30894,
          "sha512": "e3b9f1ca12a1185444842cd8ce6fd2328dcc004aeee56400a4c296b4cd4e0b22cc74ac74bcd9181a7828af7e6923bf08a5891a0d214a08fd7818aaa6185b9f27",
          "sha256": "31ef5fdd14ead666eaf50f3015c089f072311708fad49409c2add3db30b5ddbc",
          "sha1": "afdd1f63de36220141a8e930a10b47160ed99837",
          "md5": "1058288e5829d1d735e5f04c1e8891f4"
        }
      ]
    }
  ]
}
