{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03047-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03047-SNAPSHOT.jar",
          "url": "embedded-mas-0.03047-SNAPSHOT.jar",
          "size": 60320,
          "sha512": "42dbfc6a7bacb0a266bc607f0209f64b42a416a384739f7f6e9534002e700cd006dca41b0fb1b157db57c498f56f01d870b713b9dc0c01d4b99f3827cebee108",
          "sha256": "d8cde44b49f5dc831d148fa4bfd9e1c2e3d179e2b0afafd49356ed57f21ff66f",
          "sha1": "4d532b92f8d6ad89d3917d6ab51f32383a645af9",
          "md5": "4476fe296dd6fa3cbe069af638f605fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03047-SNAPSHOT.jar",
          "url": "embedded-mas-0.03047-SNAPSHOT.jar",
          "size": 60320,
          "sha512": "42dbfc6a7bacb0a266bc607f0209f64b42a416a384739f7f6e9534002e700cd006dca41b0fb1b157db57c498f56f01d870b713b9dc0c01d4b99f3827cebee108",
          "sha256": "d8cde44b49f5dc831d148fa4bfd9e1c2e3d179e2b0afafd49356ed57f21ff66f",
          "sha1": "4d532b92f8d6ad89d3917d6ab51f32383a645af9",
          "md5": "4476fe296dd6fa3cbe069af638f605fb"
        }
      ]
    }
  ]
}
