{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.038014-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038014-SNAPSHOT.jar",
          "url": "embedded-mas-0.038014-SNAPSHOT.jar",
          "size": 74507,
          "sha512": "0f4afca8627a7f8728eae37cbd691e9706b3c9fb7015dc2c9f76f3e1dbc300a2a178654d5d030159780b7b90d9b3fd6c828c07baaba339351e4946919290d4df",
          "sha256": "093c55921f2f02563a0d5438e932553fc515bccaea737df203ac65ad263821b9",
          "sha1": "396054a939cb0f00960a6d8f02d1ba51e462e8fd",
          "md5": "eb2cddd7eefd42dfb86459ae5ae9ee37"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038014-SNAPSHOT.jar",
          "url": "embedded-mas-0.038014-SNAPSHOT.jar",
          "size": 74507,
          "sha512": "0f4afca8627a7f8728eae37cbd691e9706b3c9fb7015dc2c9f76f3e1dbc300a2a178654d5d030159780b7b90d9b3fd6c828c07baaba339351e4946919290d4df",
          "sha256": "093c55921f2f02563a0d5438e932553fc515bccaea737df203ac65ad263821b9",
          "sha1": "396054a939cb0f00960a6d8f02d1ba51e462e8fd",
          "md5": "eb2cddd7eefd42dfb86459ae5ae9ee37"
        }
      ]
    }
  ]
}
