{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.046-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.046-SNAPSHOT.jar",
          "url": "embedded-mas-0.046-SNAPSHOT.jar",
          "size": 74322,
          "sha512": "f936cc0a628ad2c5d1801c5d799d625fe54d436274f31f916d0bdd0c83755e1fb06c76f5960a76a76ed29068b3e4ccce0a4810d9860df8724baa0719c2f02b74",
          "sha256": "0507d89bb6f14dca30a05949b635596f9fcfb36ce44c94b8b44587c0c7306f65",
          "sha1": "9c8de4a68051bb358474577c579924c87ca63051",
          "md5": "9db268e7f82415e7c7676eded2379e39"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.046-SNAPSHOT.jar",
          "url": "embedded-mas-0.046-SNAPSHOT.jar",
          "size": 74322,
          "sha512": "f936cc0a628ad2c5d1801c5d799d625fe54d436274f31f916d0bdd0c83755e1fb06c76f5960a76a76ed29068b3e4ccce0a4810d9860df8724baa0719c2f02b74",
          "sha256": "0507d89bb6f14dca30a05949b635596f9fcfb36ce44c94b8b44587c0c7306f65",
          "sha1": "9c8de4a68051bb358474577c579924c87ca63051",
          "md5": "9db268e7f82415e7c7676eded2379e39"
        }
      ]
    }
  ]
}
