{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03207-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03207-SNAPSHOT.jar",
          "url": "embedded-mas-0.03207-SNAPSHOT.jar",
          "size": 62355,
          "sha512": "30a2b5eca6e1979248cbe49748f7bbe834486dd3dad23a3486f471a265f421e474bae397d18c61c3b1b163912ede1ae3164fdd8540be531dd7710b265c02b108",
          "sha256": "f4902851f21c2197172966cab36e0b5be904d7473692d89840cfe1b585a8d37d",
          "sha1": "4d6b05b721ad6a3574bcfb7980c89aa105671fd6",
          "md5": "d53be6ab13e52393ff703ed21fc899b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03207-SNAPSHOT.jar",
          "url": "embedded-mas-0.03207-SNAPSHOT.jar",
          "size": 62355,
          "sha512": "30a2b5eca6e1979248cbe49748f7bbe834486dd3dad23a3486f471a265f421e474bae397d18c61c3b1b163912ede1ae3164fdd8540be531dd7710b265c02b108",
          "sha256": "f4902851f21c2197172966cab36e0b5be904d7473692d89840cfe1b585a8d37d",
          "sha1": "4d6b05b721ad6a3574bcfb7980c89aa105671fd6",
          "md5": "d53be6ab13e52393ff703ed21fc899b4"
        }
      ]
    }
  ]
}
