{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.038001-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038001-SNAPSHOT.jar",
          "url": "embedded-mas-0.038001-SNAPSHOT.jar",
          "size": 67995,
          "sha512": "0053cc9fde641578c5c6496a11a8fc2a192177898274596026d7ddee2d640f26028431647de2ad1626d3423aae8f517f041fc1b7f5408e45ab08d83f26e976c8",
          "sha256": "f571a8045152fcefa60f716c4b11cef96937d5884ba97cd582a3d2fed92e63c8",
          "sha1": "1404755fa573cfe93907c52d663cc829718d2dad",
          "md5": "1233ebdf273833ea5a765770b3589211"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038001-SNAPSHOT.jar",
          "url": "embedded-mas-0.038001-SNAPSHOT.jar",
          "size": 67995,
          "sha512": "0053cc9fde641578c5c6496a11a8fc2a192177898274596026d7ddee2d640f26028431647de2ad1626d3423aae8f517f041fc1b7f5408e45ab08d83f26e976c8",
          "sha256": "f571a8045152fcefa60f716c4b11cef96937d5884ba97cd582a3d2fed92e63c8",
          "sha1": "1404755fa573cfe93907c52d663cc829718d2dad",
          "md5": "1233ebdf273833ea5a765770b3589211"
        }
      ]
    }
  ]
}
