{
  "formatVersion": "1.1",
  "component": {
    "group": "javard",
    "module": "javard",
    "version": "0.027-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "javard-0.033-SNAPSHOT.jar",
          "url": "javard-0.033-SNAPSHOT.jar",
          "size": 4690,
          "sha512": "423413890b5af7e5bba40924614e122ac95be05a6df427493c77b37bdc594e0a4f33cf1302fc3d897194d10cad5cc7f280736987b07dc200fdd0596fc24a9a81",
          "sha256": "9376a6a1f8d435e04dddf27ae4a3eccb846ed0205bc7a207abba52b8e081d19f",
          "sha1": "6afb2657eaf8548d883cc0056e300abc19413c24",
          "md5": "79c00c4ee89ed3e1560fdd2fe13efe9e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "javard-0.033-SNAPSHOT.jar",
          "url": "javard-0.033-SNAPSHOT.jar",
          "size": 4690,
          "sha512": "423413890b5af7e5bba40924614e122ac95be05a6df427493c77b37bdc594e0a4f33cf1302fc3d897194d10cad5cc7f280736987b07dc200fdd0596fc24a9a81",
          "sha256": "9376a6a1f8d435e04dddf27ae4a3eccb846ed0205bc7a207abba52b8e081d19f",
          "sha1": "6afb2657eaf8548d883cc0056e300abc19413c24",
          "md5": "79c00c4ee89ed3e1560fdd2fe13efe9e"
        }
      ]
    }
  ]
}
