{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04645-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04645-DEV.jar",
          "url": "embedded-mas-0.04645-DEV.jar",
          "size": 77979,
          "sha512": "36bf04c8a28d6a0a0c3ad03ff5836e0be587f1c0baf97b3fb8d0d6dbfbe67ece46345a8b9ec4a20b7060e14ff146b31a6ab0854093ac24dc183eb42e146a1807",
          "sha256": "fb14f41965134d52a80cb1e368c75210a2cc621e0fc89ea161f8fcde96a3b4f2",
          "sha1": "f214f2e1f26981e378cf28a75a4c0f3d77fc0e04",
          "md5": "8ec60a6027beffe15c5b6c3289514c6f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04645-DEV.jar",
          "url": "embedded-mas-0.04645-DEV.jar",
          "size": 77979,
          "sha512": "36bf04c8a28d6a0a0c3ad03ff5836e0be587f1c0baf97b3fb8d0d6dbfbe67ece46345a8b9ec4a20b7060e14ff146b31a6ab0854093ac24dc183eb42e146a1807",
          "sha256": "fb14f41965134d52a80cb1e368c75210a2cc621e0fc89ea161f8fcde96a3b4f2",
          "sha1": "f214f2e1f26981e378cf28a75a4c0f3d77fc0e04",
          "md5": "8ec60a6027beffe15c5b6c3289514c6f"
        }
      ]
    }
  ]
}
