{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04645-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04645-DEV.jar",
          "url": "embedded-mas-0.04645-DEV.jar",
          "size": 78001,
          "sha512": "dd43f9454f941ff2ddc614e82b435a5e1635073d153cd3eb43725dd5b9dbdab3fc75daee3a670dfca60c3079a55f3b06054b9a9dee0de20b46c989bbbe12aa98",
          "sha256": "06abb47a30abb23079e715621b6232608de1ad959fb247056df1e8e1f1e74127",
          "sha1": "96d32873a19ac2a0f08556dd03a5d1ef68452a1f",
          "md5": "37c1167110df11841472f105136584d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04645-DEV.jar",
          "url": "embedded-mas-0.04645-DEV.jar",
          "size": 78001,
          "sha512": "dd43f9454f941ff2ddc614e82b435a5e1635073d153cd3eb43725dd5b9dbdab3fc75daee3a670dfca60c3079a55f3b06054b9a9dee0de20b46c989bbbe12aa98",
          "sha256": "06abb47a30abb23079e715621b6232608de1ad959fb247056df1e8e1f1e74127",
          "sha1": "96d32873a19ac2a0f08556dd03a5d1ef68452a1f",
          "md5": "37c1167110df11841472f105136584d9"
        }
      ]
    }
  ]
}
