{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271203-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271203-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271203-SNAPSHOT.jar",
          "size": 30264,
          "sha512": "81150292cdaff10d4b5985256ed5ee7e930947b3aae2acf8e9591a53f82eee83ec0f72572383c3f748b85f7eda9dc77802dc0bf942c5fa1a93128ea76fa61a16",
          "sha256": "70130f3d964023f9de188cacbd1188f4b1537055693442cab419700e9a71ffe1",
          "sha1": "0741c60b84cd61cf9262a8bcb896a5f88b8c330e",
          "md5": "d3c42eaa4ecf2c5577f0f54432443be5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271203-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271203-SNAPSHOT.jar",
          "size": 30264,
          "sha512": "81150292cdaff10d4b5985256ed5ee7e930947b3aae2acf8e9591a53f82eee83ec0f72572383c3f748b85f7eda9dc77802dc0bf942c5fa1a93128ea76fa61a16",
          "sha256": "70130f3d964023f9de188cacbd1188f4b1537055693442cab419700e9a71ffe1",
          "sha1": "0741c60b84cd61cf9262a8bcb896a5f88b8c330e",
          "md5": "d3c42eaa4ecf2c5577f0f54432443be5"
        }
      ]
    }
  ]
}
