{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03602-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03602-SNAPSHOT.jar",
          "url": "embedded-mas-0.03602-SNAPSHOT.jar",
          "size": 64137,
          "sha512": "1b1e3398dbb9a70723f0a96729046664abcf63b223d8230f75946908a23b60c1ef276a5e954b1a7468fe71394818bb011af537085554c40b0f40aa2638225efc",
          "sha256": "dd9975dd2fba5b4da6f2f5fc8e6efead152dc735c40d079725d460fce64e0d0d",
          "sha1": "3a4aba40e0b382bd861edacfa8316d4b431e9481",
          "md5": "e20e1eda5a4dddadab7e6e18e32a440b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03602-SNAPSHOT.jar",
          "url": "embedded-mas-0.03602-SNAPSHOT.jar",
          "size": 64137,
          "sha512": "1b1e3398dbb9a70723f0a96729046664abcf63b223d8230f75946908a23b60c1ef276a5e954b1a7468fe71394818bb011af537085554c40b0f40aa2638225efc",
          "sha256": "dd9975dd2fba5b4da6f2f5fc8e6efead152dc735c40d079725d460fce64e0d0d",
          "sha1": "3a4aba40e0b382bd861edacfa8316d4b431e9481",
          "md5": "e20e1eda5a4dddadab7e6e18e32a440b"
        }
      ]
    }
  ]
}
