{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03603-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03603-SNAPSHOT.jar",
          "url": "embedded-mas-0.03603-SNAPSHOT.jar",
          "size": 64134,
          "sha512": "b62c528ca570ad33fb56531732439f99df9058b0084128fc4298dccb0894d0e3a13b6207233d469b89412f4368b8b381cc9d7b55407ca884f7221c954056c44b",
          "sha256": "7443dc244cb0ef7e66d79402ba0342f63cc63e6f7cc8a4fddb9abf1b52349469",
          "sha1": "b8f429fa1b259b4931d47ee22ff89aea76204d8a",
          "md5": "0aef95f42503c36b726265b7fd59d2c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03603-SNAPSHOT.jar",
          "url": "embedded-mas-0.03603-SNAPSHOT.jar",
          "size": 64134,
          "sha512": "b62c528ca570ad33fb56531732439f99df9058b0084128fc4298dccb0894d0e3a13b6207233d469b89412f4368b8b381cc9d7b55407ca884f7221c954056c44b",
          "sha256": "7443dc244cb0ef7e66d79402ba0342f63cc63e6f7cc8a4fddb9abf1b52349469",
          "sha1": "b8f429fa1b259b4931d47ee22ff89aea76204d8a",
          "md5": "0aef95f42503c36b726265b7fd59d2c9"
        }
      ]
    }
  ]
}
