{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.05412-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.05412-SNAPSHOT.jar",
          "url": "embedded-mas-0.05412-SNAPSHOT.jar",
          "size": 89639,
          "sha512": "3a325375530cd9f80596eb6150dada38a8f98a0c5fc41bce2e2405e08fea2fc3031b6b05780a1e74f498600a781f8ed3db8828e6612164b207dacc25b6e76287",
          "sha256": "d14a41dcbe654fc13318b7289d90929499e0697adfa6ba332a2ca3fa38fb76eb",
          "sha1": "5e29fc24affabd6df1677f91c9d725bf52a526ae",
          "md5": "214ed4bbb0317200f0b51c0b7dd2cacb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.30"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.05412-SNAPSHOT.jar",
          "url": "embedded-mas-0.05412-SNAPSHOT.jar",
          "size": 89639,
          "sha512": "3a325375530cd9f80596eb6150dada38a8f98a0c5fc41bce2e2405e08fea2fc3031b6b05780a1e74f498600a781f8ed3db8828e6612164b207dacc25b6e76287",
          "sha256": "d14a41dcbe654fc13318b7289d90929499e0697adfa6ba332a2ca3fa38fb76eb",
          "sha1": "5e29fc24affabd6df1677f91c9d725bf52a526ae",
          "md5": "214ed4bbb0317200f0b51c0b7dd2cacb"
        }
      ]
    }
  ]
}
