{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04660-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04660-DEV.jar",
          "url": "embedded-mas-0.04660-DEV.jar",
          "size": 70047,
          "sha512": "5219e2f3253b2f89e4b9db449f006ca3f379ff68e4d4effa2000d023eff5f24dc0eb82b8f503c685eae73f720b0a65c1304a8a540b9d5af30f4104d919ed7392",
          "sha256": "c6b05ec258dfb2dede9d8524e446000b2ba54ed893950c1abb8e26911f9e06a5",
          "sha1": "556214dd4ce9e34f5170cb7a544a00fff9efedee",
          "md5": "6342096d5c7fc109b885d624a26d0751"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04660-DEV.jar",
          "url": "embedded-mas-0.04660-DEV.jar",
          "size": 70047,
          "sha512": "5219e2f3253b2f89e4b9db449f006ca3f379ff68e4d4effa2000d023eff5f24dc0eb82b8f503c685eae73f720b0a65c1304a8a540b9d5af30f4104d919ed7392",
          "sha256": "c6b05ec258dfb2dede9d8524e446000b2ba54ed893950c1abb8e26911f9e06a5",
          "sha1": "556214dd4ce9e34f5170cb7a544a00fff9efedee",
          "md5": "6342096d5c7fc109b885d624a26d0751"
        }
      ]
    }
  ]
}
