{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04621-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04621-SNAPSHOT.jar",
          "url": "embedded-mas-0.04621-SNAPSHOT.jar",
          "size": 68990,
          "sha512": "6ab561478bb1665504fb5c5cabd9d5fe2ae3f119f45c92a3d2adfd25d1d22fa06233bd7875067364b1e0f734c6732e4e3d394d28551cceeff175d05acb8689c6",
          "sha256": "8eb12e4e7baf0ab4904fcf6aa50fd3c1579353d65179182f41a8b98834857db9",
          "sha1": "bde4d294ae9503eb4ec1bff73aa27b36cadb6ce9",
          "md5": "683776c18c0ad764f61126d4e52adee0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04621-SNAPSHOT.jar",
          "url": "embedded-mas-0.04621-SNAPSHOT.jar",
          "size": 68990,
          "sha512": "6ab561478bb1665504fb5c5cabd9d5fe2ae3f119f45c92a3d2adfd25d1d22fa06233bd7875067364b1e0f734c6732e4e3d394d28551cceeff175d05acb8689c6",
          "sha256": "8eb12e4e7baf0ab4904fcf6aa50fd3c1579353d65179182f41a8b98834857db9",
          "sha1": "bde4d294ae9503eb4ec1bff73aa27b36cadb6ce9",
          "md5": "683776c18c0ad764f61126d4e52adee0"
        }
      ]
    }
  ]
}
