{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04605-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04605-SNAPSHOT.jar",
          "url": "embedded-mas-0.04605-SNAPSHOT.jar",
          "size": 72962,
          "sha512": "45ed90a13afd2aebb3bd6a90460435111bb1d04ee6193a517bc9965af80e719161ca59b795be015dd39a3290b15e13985e0d94d8ed8068fffbb033349b3ed2a7",
          "sha256": "c60c166179a20777732ed4bf5878e92e2e6bd8a655e3dea0cca2c9a1b487d8e7",
          "sha1": "977de093600ec5e56d7a0753269c36c6b7b5fcd3",
          "md5": "ea8c42f6c231f9f59641dba2820c561b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04605-SNAPSHOT.jar",
          "url": "embedded-mas-0.04605-SNAPSHOT.jar",
          "size": 72962,
          "sha512": "45ed90a13afd2aebb3bd6a90460435111bb1d04ee6193a517bc9965af80e719161ca59b795be015dd39a3290b15e13985e0d94d8ed8068fffbb033349b3ed2a7",
          "sha256": "c60c166179a20777732ed4bf5878e92e2e6bd8a655e3dea0cca2c9a1b487d8e7",
          "sha1": "977de093600ec5e56d7a0753269c36c6b7b5fcd3",
          "md5": "ea8c42f6c231f9f59641dba2820c561b"
        }
      ]
    }
  ]
}
