{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.02709-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02709-SNAPSHOT.jar",
          "url": "embedded-mas-0.02709-SNAPSHOT.jar",
          "size": 30088,
          "sha512": "838e3120ee051e4e454af3f9d26754b6a4015234e384fd1105d9e02b5219516bfdf819ccc807634ece7226452fa2e24ea4d17611c31a2c923c2781aa0c1c8f51",
          "sha256": "51bf37b9940708a44d4e4e47bad92307737af396a051fc23b3b31f59d92a41a0",
          "sha1": "312532b05d26df1db0e13c976e0648eb8bd0a192",
          "md5": "71ffd35810d36ea0eb48e9af7b529787"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02709-SNAPSHOT.jar",
          "url": "embedded-mas-0.02709-SNAPSHOT.jar",
          "size": 30088,
          "sha512": "838e3120ee051e4e454af3f9d26754b6a4015234e384fd1105d9e02b5219516bfdf819ccc807634ece7226452fa2e24ea4d17611c31a2c923c2781aa0c1c8f51",
          "sha256": "51bf37b9940708a44d4e4e47bad92307737af396a051fc23b3b31f59d92a41a0",
          "sha1": "312532b05d26df1db0e13c976e0648eb8bd0a192",
          "md5": "71ffd35810d36ea0eb48e9af7b529787"
        }
      ]
    }
  ]
}
