{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04608-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04608-SNAPSHOT.jar",
          "url": "embedded-mas-0.04608-SNAPSHOT.jar",
          "size": 69068,
          "sha512": "24cb678402d712baea078cd59967fb9dbd2215c5c0e2885872b4be15453136c506f4290b1e3baa7b8073dcf739b49b7e64954d5f79d011c34b2f2feb967fbacb",
          "sha256": "911b27dc6177a8a0163a27a2524ca429ae9c55107757c320f28253e192f924b3",
          "sha1": "7172c1596014d7c5356d72ede8aff8b78ae4456f",
          "md5": "36bc6012df94ccb2c07029e3c6c8cef0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04608-SNAPSHOT.jar",
          "url": "embedded-mas-0.04608-SNAPSHOT.jar",
          "size": 69068,
          "sha512": "24cb678402d712baea078cd59967fb9dbd2215c5c0e2885872b4be15453136c506f4290b1e3baa7b8073dcf739b49b7e64954d5f79d011c34b2f2feb967fbacb",
          "sha256": "911b27dc6177a8a0163a27a2524ca429ae9c55107757c320f28253e192f924b3",
          "sha1": "7172c1596014d7c5356d72ede8aff8b78ae4456f",
          "md5": "36bc6012df94ccb2c07029e3c6c8cef0"
        }
      ]
    }
  ]
}
