{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04626-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04626-SNAPSHOT.jar",
          "url": "embedded-mas-0.04626-SNAPSHOT.jar",
          "size": 74054,
          "sha512": "7edff70532ee543141ec0673fd308c4f675bad5ff4501a9282e39931269bbd972f65cc3cede062540ddb849e476f5b44a0d3813a8df39a71223bfcdb45102841",
          "sha256": "1fbef01863d918bd08dd3e25f6b6f3f8a5b02213e6a7d2a2764d498c19927fbe",
          "sha1": "437e91847fbf55b6c3df71073ab01ebb85a43711",
          "md5": "7f16320d7a9490403b3524d0751cc3c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04626-SNAPSHOT.jar",
          "url": "embedded-mas-0.04626-SNAPSHOT.jar",
          "size": 74054,
          "sha512": "7edff70532ee543141ec0673fd308c4f675bad5ff4501a9282e39931269bbd972f65cc3cede062540ddb849e476f5b44a0d3813a8df39a71223bfcdb45102841",
          "sha256": "1fbef01863d918bd08dd3e25f6b6f3f8a5b02213e6a7d2a2764d498c19927fbe",
          "sha1": "437e91847fbf55b6c3df71073ab01ebb85a43711",
          "md5": "7f16320d7a9490403b3524d0751cc3c3"
        }
      ]
    }
  ]
}
