{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.036-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.036-SNAPSHOT.jar",
          "url": "embedded-mas-0.036-SNAPSHOT.jar",
          "size": 64076,
          "sha512": "0833c10e1f63d583b41d313f8d4459b4137e1c14118a4485e4aeee574379b8f5efc4c37fb73a5a864400450f0988210d7cd78397be2103aea8c113dd4327aa0a",
          "sha256": "6b49f3f2762897ceb82f340bff39ac1f4703af97e27619cc7671e7a73d0a942e",
          "sha1": "f6937664e82a01780c2928703a1e3f31ea37dcdc",
          "md5": "77a2be335db3f00a86761cc1c1d234fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.036-SNAPSHOT.jar",
          "url": "embedded-mas-0.036-SNAPSHOT.jar",
          "size": 64076,
          "sha512": "0833c10e1f63d583b41d313f8d4459b4137e1c14118a4485e4aeee574379b8f5efc4c37fb73a5a864400450f0988210d7cd78397be2103aea8c113dd4327aa0a",
          "sha256": "6b49f3f2762897ceb82f340bff39ac1f4703af97e27619cc7671e7a73d0a942e",
          "sha1": "f6937664e82a01780c2928703a1e3f31ea37dcdc",
          "md5": "77a2be335db3f00a86761cc1c1d234fc"
        }
      ]
    }
  ]
}
