{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.047-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.047-SNAPSHOT.jar",
          "url": "embedded-mas-0.047-SNAPSHOT.jar",
          "size": 73422,
          "sha512": "75135238f64237daab00c672c0f2deebb43e503f24ede04e40d6229f00d28a42406feaab14a52bcf902db99dd7a547e54babfa1890f2cbfd4412b4ed109b9674",
          "sha256": "e8c3d09cb11a86dd571876c6982578a62dc34a756e3439f0c1fffcd0e2d9fad0",
          "sha1": "489d84a70e565010c8844ddb35f68a41091717df",
          "md5": "198c8e00601f8c933cc4c57948ade7a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.047-SNAPSHOT.jar",
          "url": "embedded-mas-0.047-SNAPSHOT.jar",
          "size": 73422,
          "sha512": "75135238f64237daab00c672c0f2deebb43e503f24ede04e40d6229f00d28a42406feaab14a52bcf902db99dd7a547e54babfa1890f2cbfd4412b4ed109b9674",
          "sha256": "e8c3d09cb11a86dd571876c6982578a62dc34a756e3439f0c1fffcd0e2d9fad0",
          "sha1": "489d84a70e565010c8844ddb35f68a41091717df",
          "md5": "198c8e00601f8c933cc4c57948ade7a2"
        }
      ]
    }
  ]
}
