{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04203-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04203-SNAPSHOT.jar",
          "url": "embedded-mas-0.04203-SNAPSHOT.jar",
          "size": 72839,
          "sha512": "a877ccca4d9148b5630a2f9d6b7795e24ac5208cd095a8526dbbe14bee3079a0c530052ac0f8f2023a1fabe3195c71e9ccb1dce565fb7dca90c5944b4469e583",
          "sha256": "4c806206423dc5cd653a98e3941d0bec3904001ab14e64f750ea4b53bb794bb3",
          "sha1": "feab692b683a239c1305df5d0822c471642b645d",
          "md5": "c744ee426677a375341a259a40bc6a5c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04203-SNAPSHOT.jar",
          "url": "embedded-mas-0.04203-SNAPSHOT.jar",
          "size": 72839,
          "sha512": "a877ccca4d9148b5630a2f9d6b7795e24ac5208cd095a8526dbbe14bee3079a0c530052ac0f8f2023a1fabe3195c71e9ccb1dce565fb7dca90c5944b4469e583",
          "sha256": "4c806206423dc5cd653a98e3941d0bec3904001ab14e64f750ea4b53bb794bb3",
          "sha1": "feab692b683a239c1305df5d0822c471642b645d",
          "md5": "c744ee426677a375341a259a40bc6a5c"
        }
      ]
    }
  ]
}
