{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04655-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04655-DEV.jar",
          "url": "embedded-mas-0.04655-DEV.jar",
          "size": 70554,
          "sha512": "207cb5486268888071f2fd973ca89cc85c83ef6656fba9575a9c28f857b3a15bbc1c58426cc0597bace9043655c2d18fc2815ae1c3834f10ba488b1474431dae",
          "sha256": "ca8dd89d4129877ade72bd426e257ee9b57f6229ac47cb622e49a45372578f06",
          "sha1": "67bcd853f646ac167be55c2cf4e3316e97d14b36",
          "md5": "cda6b2c1a58ba86d0fc203447595af53"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04655-DEV.jar",
          "url": "embedded-mas-0.04655-DEV.jar",
          "size": 70554,
          "sha512": "207cb5486268888071f2fd973ca89cc85c83ef6656fba9575a9c28f857b3a15bbc1c58426cc0597bace9043655c2d18fc2815ae1c3834f10ba488b1474431dae",
          "sha256": "ca8dd89d4129877ade72bd426e257ee9b57f6229ac47cb622e49a45372578f06",
          "sha1": "67bcd853f646ac167be55c2cf4e3316e97d14b36",
          "md5": "cda6b2c1a58ba86d0fc203447595af53"
        }
      ]
    }
  ]
}
