{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04606-DEVX",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04606-DEVX.jar",
          "url": "embedded-mas-0.04606-DEVX.jar",
          "size": 69440,
          "sha512": "83d290e1a6a4ba171d7982ea3afa5702752d88403fd354341215ebf2fd08b2404a99b752c494f2743bd04c2ee4b9d9a62c3dbd8e4ecfb3a240edf441822ea1ef",
          "sha256": "d39c481b9c1fd066ab76b67751275c5ba4d332587a72156c1ae66401a18aa71f",
          "sha1": "c6d0e0be8d7d5216240462bad5300dadd6fc90e4",
          "md5": "80ddbe57aa9c523fd33b69164bfd242f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04606-DEVX.jar",
          "url": "embedded-mas-0.04606-DEVX.jar",
          "size": 69440,
          "sha512": "83d290e1a6a4ba171d7982ea3afa5702752d88403fd354341215ebf2fd08b2404a99b752c494f2743bd04c2ee4b9d9a62c3dbd8e4ecfb3a240edf441822ea1ef",
          "sha256": "d39c481b9c1fd066ab76b67751275c5ba4d332587a72156c1ae66401a18aa71f",
          "sha1": "c6d0e0be8d7d5216240462bad5300dadd6fc90e4",
          "md5": "80ddbe57aa9c523fd33b69164bfd242f"
        }
      ]
    }
  ]
}
