{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04619-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04619-SNAPSHOT.jar",
          "url": "embedded-mas-0.04619-SNAPSHOT.jar",
          "size": 69417,
          "sha512": "983b776c7e352940f41a9d5bfb9c5784005bcff064806610e31196da7b153216d0d8a17660630af85439f4ff28f2d2ba2b2a7c5f183abf4fd8afd488ed5f6336",
          "sha256": "8c6a37b3546ca8213cdb953fbb4cdb701f13a930b142dccfbc45ba0a0a659c25",
          "sha1": "4488409a0084a78889d40bd545f44ec20dd283ff",
          "md5": "b720d207003803516e694530064d55ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04619-SNAPSHOT.jar",
          "url": "embedded-mas-0.04619-SNAPSHOT.jar",
          "size": 69417,
          "sha512": "983b776c7e352940f41a9d5bfb9c5784005bcff064806610e31196da7b153216d0d8a17660630af85439f4ff28f2d2ba2b2a7c5f183abf4fd8afd488ed5f6336",
          "sha256": "8c6a37b3546ca8213cdb953fbb4cdb701f13a930b142dccfbc45ba0a0a659c25",
          "sha1": "4488409a0084a78889d40bd545f44ec20dd283ff",
          "md5": "b720d207003803516e694530064d55ad"
        }
      ]
    }
  ]
}
