{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.027060704-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.027060704-SNAPSHOT.jar",
          "url": "embedded-mas-0.027060704-SNAPSHOT.jar",
          "size": 29966,
          "sha512": "38394fdbfbe8ea411f0f6eb20ad787265dc901e387076ef6d87f74350c27436fdeb043e42982e82175ca6905455536b00defbfbe6074a7c70fba6933a1cab506",
          "sha256": "e50d190314b0775268a6d9a8170838a7b0eecf70e00417bfbef1e6e07e168a30",
          "sha1": "8552c8e8f763729538a256c0c9da5cefcddd9bf9",
          "md5": "165da42fdf90225dfd9d28efea4cb8c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.027060704-SNAPSHOT.jar",
          "url": "embedded-mas-0.027060704-SNAPSHOT.jar",
          "size": 29966,
          "sha512": "38394fdbfbe8ea411f0f6eb20ad787265dc901e387076ef6d87f74350c27436fdeb043e42982e82175ca6905455536b00defbfbe6074a7c70fba6933a1cab506",
          "sha256": "e50d190314b0775268a6d9a8170838a7b0eecf70e00417bfbef1e6e07e168a30",
          "sha1": "8552c8e8f763729538a256c0c9da5cefcddd9bf9",
          "md5": "165da42fdf90225dfd9d28efea4cb8c0"
        }
      ]
    }
  ]
}
