{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.038007-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038007-SNAPSHOT.jar",
          "url": "embedded-mas-0.038007-SNAPSHOT.jar",
          "size": 74512,
          "sha512": "502224b6ae92a8eb0153dcc805b9f1af643cf765fe2b2f5f955c657a604b78e2180833daec35b13883bd7d678ac077fd80ae003ca6fc663870fe35b1ded3a7d1",
          "sha256": "be113443afadd44681f179392338e8e63eb8a5c8bb763c4d49907f6d0ae9bd47",
          "sha1": "a8c571e29e217851120c39460f8053eef3a07c3f",
          "md5": "140bd80016c9f3b76a621c578499103a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.038007-SNAPSHOT.jar",
          "url": "embedded-mas-0.038007-SNAPSHOT.jar",
          "size": 74512,
          "sha512": "502224b6ae92a8eb0153dcc805b9f1af643cf765fe2b2f5f955c657a604b78e2180833daec35b13883bd7d678ac077fd80ae003ca6fc663870fe35b1ded3a7d1",
          "sha256": "be113443afadd44681f179392338e8e63eb8a5c8bb763c4d49907f6d0ae9bd47",
          "sha1": "a8c571e29e217851120c39460f8053eef3a07c3f",
          "md5": "140bd80016c9f3b76a621c578499103a"
        }
      ]
    }
  ]
}
