{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.048-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.048-SNAPSHOT.jar",
          "url": "embedded-mas-0.048-SNAPSHOT.jar",
          "size": 73638,
          "sha512": "15fe2cbb744cf93341595f18589250cd23f66000c68b13a9729834849ee01af143a0c66af1b8f88b827f9c77d3211f8a6071933a89ce1d7aedec9fc067ca59f0",
          "sha256": "aa23612b3e6058cb1667bb756e46e8039513a1ab7be2eb58a1afffd5a4bcbf84",
          "sha1": "e24bbc5751837dd04fd28f1cc89b3a0892655355",
          "md5": "3b694afb83ea4b378a5ee72cd2957ba1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.048-SNAPSHOT.jar",
          "url": "embedded-mas-0.048-SNAPSHOT.jar",
          "size": 73638,
          "sha512": "15fe2cbb744cf93341595f18589250cd23f66000c68b13a9729834849ee01af143a0c66af1b8f88b827f9c77d3211f8a6071933a89ce1d7aedec9fc067ca59f0",
          "sha256": "aa23612b3e6058cb1667bb756e46e8039513a1ab7be2eb58a1afffd5a4bcbf84",
          "sha1": "e24bbc5751837dd04fd28f1cc89b3a0892655355",
          "md5": "3b694afb83ea4b378a5ee72cd2957ba1"
        }
      ]
    }
  ]
}
