{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.044-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.044-SNAPSHOT.jar",
          "url": "embedded-mas-0.044-SNAPSHOT.jar",
          "size": 74321,
          "sha512": "a35b12593dd08aecbaaec059620bebc8b82cacfb52e3f5eaeec784a7f83b7bc2ea6aed9fea7f3a327a0b90cfa8c9b52cde74f88552b29c2b1daa63f7539ac096",
          "sha256": "c8e4d53581ae4f5bd5610d023ce26d2a336a660dfd1a841031df12158bc7f7b9",
          "sha1": "159c624b632c9ee366bff15af4dcc9374657a9bb",
          "md5": "85e548530708fa806515aa465a2f24dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.044-SNAPSHOT.jar",
          "url": "embedded-mas-0.044-SNAPSHOT.jar",
          "size": 74321,
          "sha512": "a35b12593dd08aecbaaec059620bebc8b82cacfb52e3f5eaeec784a7f83b7bc2ea6aed9fea7f3a327a0b90cfa8c9b52cde74f88552b29c2b1daa63f7539ac096",
          "sha256": "c8e4d53581ae4f5bd5610d023ce26d2a336a660dfd1a841031df12158bc7f7b9",
          "sha1": "159c624b632c9ee366bff15af4dcc9374657a9bb",
          "md5": "85e548530708fa806515aa465a2f24dc"
        }
      ]
    }
  ]
}
