{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03005-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03005-SNAPSHOT.jar",
          "url": "embedded-mas-0.03005-SNAPSHOT.jar",
          "size": 52731,
          "sha512": "3ecba53964d23a837000fcb6703d86e59636bb68ec9ce1cdaf715de6f607c8c7de4c621cee7480dd442c64cfdc2547c8879882b4fc02e69d0b3a47bb93e45621",
          "sha256": "b291a69609f9e2afb41af259f0b9d6771051c08956d004e45e8e104ff466c2c7",
          "sha1": "9d2f22afdd5328bb01e614eed0369e24dbffd401",
          "md5": "ae535451a33ffe4adce942fd03c7a79d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03005-SNAPSHOT.jar",
          "url": "embedded-mas-0.03005-SNAPSHOT.jar",
          "size": 52731,
          "sha512": "3ecba53964d23a837000fcb6703d86e59636bb68ec9ce1cdaf715de6f607c8c7de4c621cee7480dd442c64cfdc2547c8879882b4fc02e69d0b3a47bb93e45621",
          "sha256": "b291a69609f9e2afb41af259f0b9d6771051c08956d004e45e8e104ff466c2c7",
          "sha1": "9d2f22afdd5328bb01e614eed0369e24dbffd401",
          "md5": "ae535451a33ffe4adce942fd03c7a79d"
        }
      ]
    }
  ]
}
