{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03022-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03022-SNAPSHOT.jar",
          "url": "embedded-mas-0.03022-SNAPSHOT.jar",
          "size": 58572,
          "sha512": "b5812d983356f9dbe5f5ec54a8684b2cb1dfa5b40ebb69d40485a8a85e73b704a0ca5c80dc0e723559d22d3dde3ec8a2552f9b11076c8894bc05b984972df883",
          "sha256": "2ea6af2b91acc1cb66f6bcebb309feb03e82ae62c60c40c8ac4bd6ef7502bae6",
          "sha1": "b09350231a0cb851ef7ba7f96967f9d7f53824e0",
          "md5": "622bf79e0c3b4dc8507bf0f70210fa4c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03022-SNAPSHOT.jar",
          "url": "embedded-mas-0.03022-SNAPSHOT.jar",
          "size": 58572,
          "sha512": "b5812d983356f9dbe5f5ec54a8684b2cb1dfa5b40ebb69d40485a8a85e73b704a0ca5c80dc0e723559d22d3dde3ec8a2552f9b11076c8894bc05b984972df883",
          "sha256": "2ea6af2b91acc1cb66f6bcebb309feb03e82ae62c60c40c8ac4bd6ef7502bae6",
          "sha1": "b09350231a0cb851ef7ba7f96967f9d7f53824e0",
          "md5": "622bf79e0c3b4dc8507bf0f70210fa4c"
        }
      ]
    }
  ]
}
