{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03202-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03202-SNAPSHOT.jar",
          "url": "embedded-mas-0.03202-SNAPSHOT.jar",
          "size": 62141,
          "sha512": "479c19aff0872ee15761467f9060b11f0376ff05c4c35feea5b589f32ada63a9a8f585b5499d61589b9e785a30411db571016e18f29eb149ed3340b3c6ee778c",
          "sha256": "fc2e914abe49040de23f6372c09ee22970137b1994b908a25a02e12768a8a3ed",
          "sha1": "365fd8ab29b2fdfae170ac628adaf8564979361b",
          "md5": "5ecf1528801d0149d0ded19654586d4c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03202-SNAPSHOT.jar",
          "url": "embedded-mas-0.03202-SNAPSHOT.jar",
          "size": 62141,
          "sha512": "479c19aff0872ee15761467f9060b11f0376ff05c4c35feea5b589f32ada63a9a8f585b5499d61589b9e785a30411db571016e18f29eb149ed3340b3c6ee778c",
          "sha256": "fc2e914abe49040de23f6372c09ee22970137b1994b908a25a02e12768a8a3ed",
          "sha1": "365fd8ab29b2fdfae170ac628adaf8564979361b",
          "md5": "5ecf1528801d0149d0ded19654586d4c"
        }
      ]
    }
  ]
}
