{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03016-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03016-SNAPSHOT.jar",
          "url": "embedded-mas-0.03016-SNAPSHOT.jar",
          "size": 53730,
          "sha512": "6695ee5514ba8c2b37124a23ee7e67f6afbe4a7e4884fd408d2899787b6afe71b8ab61305e6ca0add7678f22b087406d59ce4ecc7f1702551356d0a0b7e31400",
          "sha256": "b2db93cccfe39b3cf433e8794d0fc0f8926855bacea7419addaf5f064bd68820",
          "sha1": "2451d486fdbf4126da89c1ad64dd1bf17d5b2adc",
          "md5": "5daa1a6b669447465d270df7d1ede247"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03016-SNAPSHOT.jar",
          "url": "embedded-mas-0.03016-SNAPSHOT.jar",
          "size": 53730,
          "sha512": "6695ee5514ba8c2b37124a23ee7e67f6afbe4a7e4884fd408d2899787b6afe71b8ab61305e6ca0add7678f22b087406d59ce4ecc7f1702551356d0a0b7e31400",
          "sha256": "b2db93cccfe39b3cf433e8794d0fc0f8926855bacea7419addaf5f064bd68820",
          "sha1": "2451d486fdbf4126da89c1ad64dd1bf17d5b2adc",
          "md5": "5daa1a6b669447465d270df7d1ede247"
        }
      ]
    }
  ]
}
