{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04638-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04638-DEV.jar",
          "url": "embedded-mas-0.04638-DEV.jar",
          "size": 77416,
          "sha512": "3dd4e9ce08cde68bae5ac56ec65921ffea5b069ef0adcb2c058ac688969a9a463ce395235a8d3823df6461b5e44cd764abd4ff3325fc447d5fc7fad64131c3b7",
          "sha256": "aaa3c0649f5f5603aa5ee9f745f86903eabe1e9faf2203b1e5ea74757d8a71e2",
          "sha1": "f81ae5347e8d0e210a94d9ec10c2b4efdbf1a94c",
          "md5": "aa3cb4172f26cb92b756b0d5acf4ba57"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04638-DEV.jar",
          "url": "embedded-mas-0.04638-DEV.jar",
          "size": 77416,
          "sha512": "3dd4e9ce08cde68bae5ac56ec65921ffea5b069ef0adcb2c058ac688969a9a463ce395235a8d3823df6461b5e44cd764abd4ff3325fc447d5fc7fad64131c3b7",
          "sha256": "aaa3c0649f5f5603aa5ee9f745f86903eabe1e9faf2203b1e5ea74757d8a71e2",
          "sha1": "f81ae5347e8d0e210a94d9ec10c2b4efdbf1a94c",
          "md5": "aa3cb4172f26cb92b756b0d5acf4ba57"
        }
      ]
    }
  ]
}
