{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04208-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04208-SNAPSHOT.jar",
          "url": "embedded-mas-0.04208-SNAPSHOT.jar",
          "size": 73227,
          "sha512": "3124d87196d23bc8f2155c44bebf5835f1bdc000a70c44f0c866237434e3d8705258050cdb4668d82a63d6bd6a7e8f28263b72a8e3f0a96e4221ed9ac01e4db3",
          "sha256": "aec42aad150ab78768f62d34f2252ad1b528ad8beb1413c3df33b41d43b405b4",
          "sha1": "8eca1419e67f88428759a14344751e58ea10852a",
          "md5": "c1698a5748be0b024bf07dce9adf4ebc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04208-SNAPSHOT.jar",
          "url": "embedded-mas-0.04208-SNAPSHOT.jar",
          "size": 73227,
          "sha512": "3124d87196d23bc8f2155c44bebf5835f1bdc000a70c44f0c866237434e3d8705258050cdb4668d82a63d6bd6a7e8f28263b72a8e3f0a96e4221ed9ac01e4db3",
          "sha256": "aec42aad150ab78768f62d34f2252ad1b528ad8beb1413c3df33b41d43b405b4",
          "sha1": "8eca1419e67f88428759a14344751e58ea10852a",
          "md5": "c1698a5748be0b024bf07dce9adf4ebc"
        }
      ]
    }
  ]
}
