{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04653-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04653-DEV.jar",
          "url": "embedded-mas-0.04653-DEV.jar",
          "size": 70463,
          "sha512": "29a473a7dbf8c2a62a0ce4388838e55cb0f5fd74bb508468924d6a04fda6c6c196c0f1013e6b99cbb32534252d4f398ac42a76837c5d211cf7d4deaa8ffd2108",
          "sha256": "e9277bf0fe71ca5438be4eb872ead0140bc417373422236d59fc40c6a0b4b58b",
          "sha1": "0adfcc1d94390c3f88e8fc56de6d50bc2bbc2af1",
          "md5": "34e74e77feac0b8ca4cb815db6b7c806"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.035-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04653-DEV.jar",
          "url": "embedded-mas-0.04653-DEV.jar",
          "size": 70463,
          "sha512": "29a473a7dbf8c2a62a0ce4388838e55cb0f5fd74bb508468924d6a04fda6c6c196c0f1013e6b99cbb32534252d4f398ac42a76837c5d211cf7d4deaa8ffd2108",
          "sha256": "e9277bf0fe71ca5438be4eb872ead0140bc417373422236d59fc40c6a0b4b58b",
          "sha1": "0adfcc1d94390c3f88e8fc56de6d50bc2bbc2af1",
          "md5": "34e74e77feac0b8ca4cb815db6b7c806"
        }
      ]
    }
  ]
}
