{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.04205-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04205-SNAPSHOT.jar",
          "url": "embedded-mas-0.04205-SNAPSHOT.jar",
          "size": 73095,
          "sha512": "794053ac32fc99639a0e96aada7fa9fcfb689f8289bd17aae59853d7bd162008a5fd2913d3151ef94ce1f0841058cc4bd7630a60506d3ff760efd44b37b69ff0",
          "sha256": "23d9046c59f00f2836eae4e2330f0b39346212148f52d95a0dc673a609c5481f",
          "sha1": "6221d1c48354107d1649e0387fe467aaab1efe59",
          "md5": "8bac827408a2cf702a29b53028d79c54"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.04205-SNAPSHOT.jar",
          "url": "embedded-mas-0.04205-SNAPSHOT.jar",
          "size": 73095,
          "sha512": "794053ac32fc99639a0e96aada7fa9fcfb689f8289bd17aae59853d7bd162008a5fd2913d3151ef94ce1f0841058cc4bd7630a60506d3ff760efd44b37b69ff0",
          "sha256": "23d9046c59f00f2836eae4e2330f0b39346212148f52d95a0dc673a609c5481f",
          "sha1": "6221d1c48354107d1649e0387fe467aaab1efe59",
          "md5": "8bac827408a2cf702a29b53028d79c54"
        }
      ]
    }
  ]
}
