{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.0271402-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271402-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271402-SNAPSHOT.jar",
          "size": 30279,
          "sha512": "7d9600d3acfb35c60f9eb1129ba72e0cf02f7b929997255e5d78fe279efbd45fca4fe1fed89d4bb600d4b0aa1e8f7a391ef8c23ba549b5bb0de49c8ceb47eebd",
          "sha256": "66f0e38b08ee55e28bc9dc87b11b1bfee9621058ad6e5ea3d422e11dca0141b8",
          "sha1": "7c4cdaa133dd9d9269f1587d336e5f4f63123336",
          "md5": "20b3da736bc1f6e5151c5d23ee58892b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.0271402-SNAPSHOT.jar",
          "url": "embedded-mas-0.0271402-SNAPSHOT.jar",
          "size": 30279,
          "sha512": "7d9600d3acfb35c60f9eb1129ba72e0cf02f7b929997255e5d78fe279efbd45fca4fe1fed89d4bb600d4b0aa1e8f7a391ef8c23ba549b5bb0de49c8ceb47eebd",
          "sha256": "66f0e38b08ee55e28bc9dc87b11b1bfee9621058ad6e5ea3d422e11dca0141b8",
          "sha1": "7c4cdaa133dd9d9269f1587d336e5f4f63123336",
          "md5": "20b3da736bc1f6e5151c5d23ee58892b"
        }
      ]
    }
  ]
}
