{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.02712-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02712-SNAPSHOT.jar",
          "url": "embedded-mas-0.02712-SNAPSHOT.jar",
          "size": 30090,
          "sha512": "37d4f6706822330ffac791be69313059aea99c443b4672855e24181b58934e3cb8238dadb976121e44ffedf699db9fe32179f74b7742e42ce78b823dc9f29e84",
          "sha256": "3f1a2a93d97749b4b21829846f6309da3b7c23f492b9bd66adba2fb1e7e48b76",
          "sha1": "e64ab5a3caaef1b65d9d5558a2b62d35e51325c8",
          "md5": "301e67c73df4d26025dc3193cae33649"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02712-SNAPSHOT.jar",
          "url": "embedded-mas-0.02712-SNAPSHOT.jar",
          "size": 30090,
          "sha512": "37d4f6706822330ffac791be69313059aea99c443b4672855e24181b58934e3cb8238dadb976121e44ffedf699db9fe32179f74b7742e42ce78b823dc9f29e84",
          "sha256": "3f1a2a93d97749b4b21829846f6309da3b7c23f492b9bd66adba2fb1e7e48b76",
          "sha1": "e64ab5a3caaef1b65d9d5558a2b62d35e51325c8",
          "md5": "301e67c73df4d26025dc3193cae33649"
        }
      ]
    }
  ]
}
