{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03901-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03901-SNAPSHOT.jar",
          "url": "embedded-mas-0.03901-SNAPSHOT.jar",
          "size": 71069,
          "sha512": "17a554630a6ad4436776d63d934f96106408a4fd4e8813334b8a65cf7825b9fbb20a1c2314593ca38261d7f5889382d03d64f9933dba8835b256c5b36439896e",
          "sha256": "acb7ee32a74e94f32bc07d0db4c9a2f75bdd8a196d38088ce15e516bb7d844b3",
          "sha1": "c9b817998029bb7c12bf058ad7ab308127c7ecb4",
          "md5": "cc84631cd4af40b5231d26b58756f0ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03901-SNAPSHOT.jar",
          "url": "embedded-mas-0.03901-SNAPSHOT.jar",
          "size": 71069,
          "sha512": "17a554630a6ad4436776d63d934f96106408a4fd4e8813334b8a65cf7825b9fbb20a1c2314593ca38261d7f5889382d03d64f9933dba8835b256c5b36439896e",
          "sha256": "acb7ee32a74e94f32bc07d0db4c9a2f75bdd8a196d38088ce15e516bb7d844b3",
          "sha1": "c9b817998029bb7c12bf058ad7ab308127c7ecb4",
          "md5": "cc84631cd4af40b5231d26b58756f0ff"
        }
      ]
    }
  ]
}
