{
  "formatVersion": "1.1",
  "component": {
    "group": "javard",
    "module": "javard",
    "version": "0.035b-NRJ",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.neuronrobotics",
          "module": "nrjavaserial",
          "version": {
            "requires": "5.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "javard-0.035b-NRJ.jar",
          "url": "javard-0.035b-NRJ.jar",
          "size": 7154,
          "sha512": "ac28eea3f54227c5abfa91aab9facb2f271a9c6952736b34c6b54d2e70bbd54f466bebb882cf80dcced69d2959bf79dcd4b3a1bcc1a78761b663cd7a0b214baf",
          "sha256": "4cc8229e76f06b3aeddfc9d795783686ce22bf4587d33718555409828dfcab64",
          "sha1": "c07e0af33e4d7baf51d6588875173126dd108f0d",
          "md5": "29f8b355e9a66ba5de416644f6348b12"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.neuronrobotics",
          "module": "nrjavaserial",
          "version": {
            "requires": "5.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "javard-0.035b-NRJ.jar",
          "url": "javard-0.035b-NRJ.jar",
          "size": 7154,
          "sha512": "ac28eea3f54227c5abfa91aab9facb2f271a9c6952736b34c6b54d2e70bbd54f466bebb882cf80dcced69d2959bf79dcd4b3a1bcc1a78761b663cd7a0b214baf",
          "sha256": "4cc8229e76f06b3aeddfc9d795783686ce22bf4587d33718555409828dfcab64",
          "sha1": "c07e0af33e4d7baf51d6588875173126dd108f0d",
          "md5": "29f8b355e9a66ba5de416644f6348b12"
        }
      ]
    }
  ]
}
