{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.02708-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02708-SNAPSHOT.jar",
          "url": "embedded-mas-0.02708-SNAPSHOT.jar",
          "size": 30004,
          "sha512": "bf927575610cf91999a04f03fad26678650da5418024ac8995c2bf83f2599a3a80f8ebb0429b2f443865bc5802549441f56992ef21c5c8deea402107d7cd2c88",
          "sha256": "2e9e0b5ccd2223849ac81695c5f7de9f9ba479cf023992a69ddb14cca3b830a6",
          "sha1": "42a43eb9053f422203a0c10fd4b9eddc2161cd75",
          "md5": "88e40a2db3f0661a59000e37ac4adcb1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.02708-SNAPSHOT.jar",
          "url": "embedded-mas-0.02708-SNAPSHOT.jar",
          "size": 30004,
          "sha512": "bf927575610cf91999a04f03fad26678650da5418024ac8995c2bf83f2599a3a80f8ebb0429b2f443865bc5802549441f56992ef21c5c8deea402107d7cd2c88",
          "sha256": "2e9e0b5ccd2223849ac81695c5f7de9f9ba479cf023992a69ddb14cca3b830a6",
          "sha1": "42a43eb9053f422203a0c10fd4b9eddc2161cd75",
          "md5": "88e40a2db3f0661a59000e37ac4adcb1"
        }
      ]
    }
  ]
}
