{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.03021SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03021SNAPSHOT.jar",
          "url": "embedded-mas-0.03021SNAPSHOT.jar",
          "size": 58238,
          "sha512": "e2a30abd36f4a956c7d86cda91c5977e7be7c7ed821dec238eb37410750e3fd22b662d788d7267da019c245ccb54b554f754e59f2280e73a12aadad45a20047b",
          "sha256": "35ddf8977c4ae6a178bcf03535a75e545b43c2055857e3da086a8370792698d7",
          "sha1": "f3d981ea734837a393c4dd2040544822357a5563",
          "md5": "13eba744a79096989bb10cf0176856e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.032-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "2.6-SNAPSHOT"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.03021SNAPSHOT.jar",
          "url": "embedded-mas-0.03021SNAPSHOT.jar",
          "size": 58238,
          "sha512": "e2a30abd36f4a956c7d86cda91c5977e7be7c7ed821dec238eb37410750e3fd22b662d788d7267da019c245ccb54b554f754e59f2280e73a12aadad45a20047b",
          "sha256": "35ddf8977c4ae6a178bcf03535a75e545b43c2055857e3da086a8370792698d7",
          "sha1": "f3d981ea734837a393c4dd2040544822357a5563",
          "md5": "13eba744a79096989bb10cf0176856e6"
        }
      ]
    }
  ]
}
