{
  "formatVersion": "1.1",
  "component": {
    "group": "embedded-mas",
    "module": "embedded-mas",
    "version": "0.061-JDK17-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.30"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.061-JDK17-SNAPSHOT.jar",
          "url": "embedded-mas-0.061-JDK17-SNAPSHOT.jar",
          "size": 131390,
          "sha512": "9e5f89c5d4f30fb6c624b4f08f78010d95913d5426e7902340a99643a8c0b7bc8e1ce61099f4a2fb55bdbcda299a1eae9d6a3b9242ab5cf8d6838ce10a188efb",
          "sha256": "a65ecce8d2f0438b11e583a9e57554903b6c438f1a642d3318c32458371a8ad6",
          "sha1": "5963ab10ab50443b015b813f6ffab06747f5fbfc",
          "md5": "a8911b8cd033772de67c53033a671c50"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.neuronrobotics",
          "module": "nrjavaserial",
          "version": {
            "requires": "5.2.1"
          }
        },
        {
          "group": "javard",
          "module": "javard",
          "version": {
            "requires": "0.036-SNAPSHOT"
          }
        },
        {
          "group": "org.jason",
          "module": "jason",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "javax.json",
          "module": "javax.json-api",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "org.glassfish",
          "module": "javax.json",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.rxtx",
          "module": "rxtx",
          "version": {
            "requires": "2.1.7"
          }
        },
        {
          "group": "edu.wpi.rail",
          "module": "jrosbridge",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        },
        {
          "group": "org.eclipse.jetty.websocket",
          "module": "websocket-server",
          "version": {
            "requires": "9.4.46.v20220331"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.30"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-mas-0.061-JDK17-SNAPSHOT.jar",
          "url": "embedded-mas-0.061-JDK17-SNAPSHOT.jar",
          "size": 131390,
          "sha512": "9e5f89c5d4f30fb6c624b4f08f78010d95913d5426e7902340a99643a8c0b7bc8e1ce61099f4a2fb55bdbcda299a1eae9d6a3b9242ab5cf8d6838ce10a188efb",
          "sha256": "a65ecce8d2f0438b11e583a9e57554903b6c438f1a642d3318c32458371a8ad6",
          "sha1": "5963ab10ab50443b015b813f6ffab06747f5fbfc",
          "md5": "a8911b8cd033772de67c53033a671c50"
        }
      ]
    }
  ]
}
